#!/usr/bin/env python3
"""
Run the SpiderNet simulation benchmark for one setting and one experiment replicate.

This script loads one simulated dataset generated by SimulationData_generation,
trains SpiderNet on that replicate, saves the SpiderNet outputs, and optionally
loads baseline method outputs for side-by-side in situ visualization.

Command-line arguments:
    --setting     Integer index into the six benchmark settings
    --experiment  Integer replicate index

Directory conventions:
    Input data:
        D:/SpiderNet/Data/Simulation/<setting>/Experiment_<idx>/
    SpiderNet outputs:
        D:/SpiderNet/Results/Simulation/SpiderNet/<setting>/Experiment_<idx>/
    Optional baseline inputs:
        D:/SpiderNet/Results/Simulation/ScCChain/...
        D:/SpiderNet/Results/Simulation/Spacia/...
"""

import os
import math
import time
import gc
import argparse
import json
import pickle
from pathlib import Path
from itertools import chain

import commot as ct
import matplotlib as mpl
import matplotlib.cm as cm
import matplotlib.patches as patches
import matplotlib.pyplot as plt
import networkx as nx
import numpy as np
import pandas as pd
import scanpy
import scanpy as sc
import scipy.sparse as sp
import seaborn as sns
import sklearn.metrics
import statsmodels.api as sm
import torch
import torch.nn as nn
import umap

from matplotlib.colors import LinearSegmentedColormap, Normalize
from scipy import stats
from scipy.cluster.hierarchy import linkage, fcluster
from scipy.spatial.distance import cdist, squareform
from scipy.stats import rankdata
from sklearn.decomposition import NMF, PCA
from sklearn.linear_model import LinearRegression
from sklearn.metrics import silhouette_score
from sklearn.neighbors import NearestNeighbors
from sklearn.preprocessing import StandardScaler
from torch import optim
from torch.cuda.amp import autocast, GradScaler
from torch.optim.lr_scheduler import ReduceLROnPlateau
from torch_geometric.data import Data
from torch_scatter import scatter_add, scatter_mean, scatter_max


# Use the same model/training API as HGSOC_modeltraining.
# The simulation script only prepares a one-batch processed bundle; model
# construction, initialization, training, inference and export are delegated
# to the SpiderNet package API.
try:
    from SpiderNet.api import (
        build_model,
        run_training,
        infer_meta_interactions,
        normalize_outputs,
        export_results,
    )
    from SpiderNet.config import TrainingConfig
    from SpiderNet.io import load_processed_data
except ImportError as exc:
    raise ImportError(
        "Could not import the SpiderNet package API. Please run this script "
        "inside the same environment used by HGSOC_modeltraining, where "
        "SpiderNet.api, SpiderNet.config and SpiderNet.io are available."
    ) from exc

cuda_available = torch.cuda.is_available()
if cuda_available:
    num_gpus = torch.cuda.device_count()
    print(f"Number of GPUs available: {num_gpus}")
    for i in range(num_gpus):
        print(f"GPU {i}: {torch.cuda.get_device_name(i)}")
    device = "cuda"
else:
    print("No GPU available, using CPU instead.")
    device = "cpu"

if_showinsitu = False

def set_figure_style():
    mpl.rcParams["pdf.fonttype"] = 42
    mpl.rcParams["ps.fonttype"] = 42
    mpl.rcParams["font.family"] = "Arial"
    mpl.rcParams["axes.linewidth"] = 0.8
    mpl.rcParams["xtick.major.width"] = 0.8
    mpl.rcParams["ytick.major.width"] = 0.8
    mpl.rcParams["xtick.major.size"] = 3
    mpl.rcParams["ytick.major.size"] = 3


def save_ai_pdf(fig, out_path, transparent=True):
    fig.savefig(
        out_path,
        format="pdf",
        bbox_inches="tight",
        transparent=transparent,
    )


def make_linear_cmap(color_list, cmap_name):
    return LinearSegmentedColormap.from_list(cmap_name, color_list, N=256)


def plot_matrix_heatmap(
    mat,
    row_labels,
    out_path,
    xlabel,
    ylabel,
    cmap,
    fig_w,
    fig_h,
    x_tick_labels=None,
    max_xticks=25,
    show_x_ticks=True,
    cbar_fraction=0.03,
    cbar_pad=0.02,
):
    set_figure_style()
    plt.close("all")

    fig, ax = plt.subplots(figsize=(fig_w, fig_h))
    im = ax.imshow(mat, aspect="auto", interpolation="nearest", cmap=cmap)

    ax.set_yticks(np.arange(len(row_labels)))
    ax.set_yticklabels(row_labels, fontsize=8)
    ax.set_ylabel(ylabel, fontsize=9)
    ax.set_xlabel(xlabel, fontsize=9)

    if show_x_ticks:
        if x_tick_labels is None:
            x_tick_labels = [str(i + 1) for i in range(mat.shape[1])]
        step = max(1, int(np.ceil(mat.shape[1] / max_xticks)))
        xticks = np.arange(0, mat.shape[1], step)
        ax.set_xticks(xticks)
        ax.set_xticklabels([x_tick_labels[i] for i in xticks], rotation=45, ha="right", fontsize=7)
    else:
        ax.set_xticks([])

    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)

    cbar = fig.colorbar(im, ax=ax, fraction=cbar_fraction, pad=cbar_pad)
    cbar.ax.tick_params(labelsize=8, width=0.8, length=3)
    cbar.outline.set_linewidth(0.8)

    fig.tight_layout()
    save_ai_pdf(fig, out_path, transparent=True)
    plt.close(fig)


def spatial_neighborindex_generation(cell_spatial, num_neighbor_available):
    spatialnn_use = NearestNeighbors(n_neighbors=num_neighbor_available + 1, algorithm="auto")
    spatialnn_use.fit(cell_spatial)
    spatialdist, spatial_neighborindex = spatialnn_use.kneighbors(cell_spatial)

    for i in range(spatial_neighborindex.shape[0]):
        if spatial_neighborindex[i, 0] != i:
            spatial_neighborindex[i, :] = np.hstack((i, np.setdiff1d(spatial_neighborindex[i, :], i)))

    spatial_neighborindex_further = spatial_neighborindex[:, 1:]
    centralindex = spatial_neighborindex[:, 0]
    edge_index = np.vstack(
        (
            np.repeat(centralindex, spatial_neighborindex_further.shape[1]),
            spatial_neighborindex_further.flatten(),
        )
    )
    return spatial_neighborindex, edge_index.T


def count_parameters(model):
    trainable_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
    non_trainable_params = sum(p.numel() for p in model.parameters() if not p.requires_grad)
    return trainable_params, non_trainable_params


def _get_logger(name, log_dir):
    import logging

    logger = logging.getLogger(name)
    if not logger.hasHandlers():
        logger.setLevel(logging.INFO)
        fh = logging.FileHandler(os.path.join(log_dir, f"{name}.log"))
        fh.setLevel(logging.INFO)
        formatter = logging.Formatter("%(asctime)s - %(name)s - %(levelname)s - %(message)s")
        fh.setFormatter(formatter)
        logger.addHandler(fh)
    return logger


def vis_NMF(assignment_cur, level_index):
    adata = scanpy.AnnData(
        X=np.array(SpiderNet_data["expression_normalized"]),
        obs={"cells": SpiderNet_data["cellnames"]},
        var={"genes": SpiderNet_data["genenames"]},
    )
    adata.obs_names = SpiderNet_data["cellnames"]
    adata.var_names = SpiderNet_data["genenames"]
    adata.obs["xcoord"] = SpiderNet_data["spatial_location"][:, 0]
    adata.obs["ycoord"] = SpiderNet_data["spatial_location"][:, 1]
    adata.obsm["spatial"] = SpiderNet_data["spatial_location"]
    adata.obs["class"] = SpiderNet_data["cell_class"]

    top_index_rel = 0
    plt.close()
    for top_index in range(assignment_cur.shape[1]):
        top_index_rel += 1
        adata.obs["assignment_top"] = assignment_cur[:, top_index]
        print(
            "Top "
            + str(top_index + 1)
            + " assignment_sum "
            + str(np.sum(assignment_cur[:, top_index]))
            + " assignment_sum (dominant) "
            + str(np.sum((assignment_cur > 0.1)[:, top_index]))
        )
        sc.pl.spatial(adata, color="assignment_top", spot_size=0.05, show=False)
        plt.savefig(
            os.path.join(save_path_main_cur, "NMF", f"level_{level_index}_{top_index_rel}.pdf"),
            format="pdf",
            bbox_inches="tight",
        )


def vis_NMF_LR(assignment_cur, level_index, LR_type):
    adata = scanpy.AnnData(
        X=np.array(SpiderNet_data["expression_normalized"]),
        obs={"cells": SpiderNet_data["cellnames"]},
        var={"genes": SpiderNet_data["genenames"]},
    )
    adata.obs_names = SpiderNet_data["cellnames"]
    adata.var_names = SpiderNet_data["genenames"]
    adata.obs["xcoord"] = SpiderNet_data["spatial_location"][:, 0]
    adata.obs["ycoord"] = SpiderNet_data["spatial_location"][:, 1]
    adata.obsm["spatial"] = SpiderNet_data["spatial_location"]
    adata.obs["class"] = SpiderNet_data["cell_class"]

    top_index_rel = 0
    plt.close()
    for top_index in range(assignment_cur.shape[1]):
        top_index_rel += 1
        adata.obs["assignment_top"] = assignment_cur[:, top_index]
        print(
            "Top "
            + str(top_index + 1)
            + " assignment_sum "
            + str(np.sum(assignment_cur[:, top_index]))
            + " assignment_sum (dominant) "
            + str(np.sum((assignment_cur > 0.1)[:, top_index]))
        )
        sc.pl.spatial(adata, color="assignment_top", spot_size=0.05, show=False)
        plt.savefig(
            os.path.join(save_path_main_cur, f"NMF_{LR_type}", f"level_{level_index}_{top_index_rel}.pdf"),
            format="pdf",
            bbox_inches="tight",
        )


def Ligand_Receptor_gene_extraction(cellchat_ligand_receptor_filedir, adata):
    cellchat_ligand_receptor = pd.read_csv(cellchat_ligand_receptor_filedir, header=None)
    cellchat_ligand_receptor = np.array(cellchat_ligand_receptor.iloc[:, 0]).tolist()

    for i in range(len(cellchat_ligand_receptor)):
        cellchat_ligand_receptor[i] = cellchat_ligand_receptor[i].replace(" ", "")

    Ligand_list = [cellchat_ligand_receptor[i].split("-")[0] for i in range(len(cellchat_ligand_receptor))]
    Ligand_list_unique = np.unique(np.array(Ligand_list)).tolist()

    Receptor_list0 = [cellchat_ligand_receptor[i].split("-")[1] for i in range(len(cellchat_ligand_receptor))]
    Receptor_list = []
    for j in range(len(Receptor_list0)):
        if "+" in Receptor_list0[j]:
            Receptor_list.append(Receptor_list0[j].replace("(", "").replace(")", "").split("+"))
        else:
            Receptor_list.append([Receptor_list0[j]])

    Receptor_list_unique = np.unique(np.array(list(chain.from_iterable(Receptor_list)))).tolist()
    print("The Ligand-encoding genes in data:", np.sum(np.isin(adata.var_names, Ligand_list_unique)))
    print("The Receptor-encoding genes in data:", np.sum(np.isin(adata.var_names, Receptor_list_unique)))

    Ligand_output = list(adata.var_names[np.isin(adata.var_names, Ligand_list_unique)])
    Receptor_output = list(adata.var_names[np.isin(adata.var_names, Receptor_list_unique)])

    Ligand_list_extend = []
    for i in range(len(Ligand_list)):
        Ligand_list_extend.extend([Ligand_list[i]] * len(Receptor_list[i]))

    Receptor_list_extend = list(chain.from_iterable(Receptor_list))
    LR_both_index = np.where(
        np.isin(Ligand_list_extend, adata.var_names) * np.isin(Receptor_list_extend, adata.var_names)
    )[0]
    Ligand_list_extend = np.array(Ligand_list_extend)[LR_both_index]
    Receptor_list_extend = np.array(Receptor_list_extend)[LR_both_index]
    LR_list_extend = np.vstack((Ligand_list_extend, Receptor_list_extend)).T
    LR_list_extend = LR_list_extend[np.where(~(LR_list_extend[:, 0] == LR_list_extend[:, 1]))[0], :]
    LR_list_extend_unique = np.unique(LR_list_extend, axis=0)

    return Ligand_output, Receptor_output, LR_list_extend_unique


def top_k_elements_indices(tensor, K):
    if K > tensor.size:
        raise ValueError("K cannot be larger than the total number of elements in the tensor.")

    flat_indices = np.argpartition(tensor.flatten(), -K)[-K:]
    top_k_values = tensor.flatten()[flat_indices]
    top_k_coords = np.unravel_index(flat_indices, tensor.shape)

    sorted_indices = np.argsort(top_k_values)[::-1]
    top_k_values = top_k_values[sorted_indices]
    top_k_coords = [coords[sorted_indices] for coords in top_k_coords]
    top_k_indices = list(zip(*top_k_coords))

    return top_k_values, top_k_indices


def cosine_similarity(A, B):
    dot_product = np.dot(A.T, B)
    norm_A = np.linalg.norm(A, axis=0)
    norm_B = np.linalg.norm(B, axis=0)
    similarity = dot_product / (norm_A[:, np.newaxis] * norm_B[np.newaxis, :])
    return similarity


def spearman_corr_matrix(A, B):
    A_ranked = np.apply_along_axis(rankdata, 1, A)
    B_ranked = np.apply_along_axis(rankdata, 1, B)

    A_centered = A_ranked - A_ranked.mean(axis=1, keepdims=True)
    B_centered = B_ranked - B_ranked.mean(axis=1, keepdims=True)

    A_norm = A_centered / np.linalg.norm(A_centered, axis=1, keepdims=True)
    B_norm = B_centered / np.linalg.norm(B_centered, axis=1, keepdims=True)

    spearman_matrix = np.dot(A_norm, B_norm.T)
    return spearman_matrix


def compute_coexpression_simple(edge_index, exp_use_sparse):
    edge_index_hstack = edge_index[:, 0]
    edge_index_hstack_reversed = edge_index[:, 1]

    exp_target = exp_use_sparse
    selector_matrix = sp.csr_matrix(
        (np.ones_like(edge_index_hstack), (np.arange(len(edge_index_hstack)), edge_index_hstack)),
        shape=(len(edge_index_hstack), exp_target.shape[0]),
        dtype=np.int16,
    )
    exp_target_extend = selector_matrix.dot(exp_target)
    del selector_matrix, exp_target

    exp_neigh = exp_use_sparse
    selector_matrix = sp.csr_matrix(
        (np.ones_like(edge_index_hstack_reversed), (np.arange(len(edge_index_hstack_reversed)), edge_index_hstack_reversed)),
        shape=(len(edge_index_hstack_reversed), exp_neigh.shape[0]),
        dtype=np.int16,
    )
    exp_neigh_extend = selector_matrix.dot(exp_neigh)
    del selector_matrix, exp_neigh

    exp_target_dense = exp_target_extend.toarray() if sp.issparse(exp_target_extend) else exp_target_extend
    exp_neigh_dense = exp_neigh_extend.toarray() if sp.issparse(exp_neigh_extend) else exp_neigh_extend

    outer_product_list = []
    for i in range(exp_target_dense.shape[0]):
        outer_product = np.outer(exp_target_dense[i], exp_neigh_dense[i])
        outer_product_list.append(outer_product.flatten())

    exp_coexpression_extend = np.vstack(outer_product_list)
    exp_coexpression_extend = np.sqrt(exp_coexpression_extend)
    exp_coexpression_extend = exp_coexpression_extend[:, np.sum(exp_coexpression_extend, axis=0) > 0]
    return exp_coexpression_extend


## Model-related code is intentionally not defined in this script.
## Consistent with HGSOC_modeltraining, we use the package API from
## SpiderNet.api instead of local Initial_model / SpiderNet_V1 / model.fit code.


def _write_pickle(obj, path):
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "wb") as handle:
        pickle.dump(obj, handle)


def _safe_to_cpu_data(data):
    """Return a CPU copy of a PyG Data object for portable processed-bundle IO."""
    try:
        return data.clone().cpu()
    except Exception:
        return data.to("cpu")


def _make_simulation_adata(exp_nor_pd, spatial_location, cellmeta_data, setting_name, experiment_index):
    """Build an AnnData object matching the fields expected by SpiderNet IO/API."""
    adata = sc.AnnData(X=exp_nor_pd.values.astype(np.float32))
    adata.obs_names = exp_nor_pd.index.astype(str)
    adata.var_names = exp_nor_pd.columns.astype(str)
    adata.obsm["spatial"] = np.asarray(spatial_location.values, dtype=np.float32)

    if "Celltype" not in cellmeta_data.columns:
        raise KeyError("cellmeta_data must contain a 'Celltype' column for simulation training.")

    if pd.Index(exp_nor_pd.index).isin(cellmeta_data.index).all():
        celltype = cellmeta_data.loc[exp_nor_pd.index, "Celltype"].astype(str).values
    else:
        # Fall back to row order, matching the original simulation script.
        celltype = cellmeta_data["Celltype"].astype(str).values
        if celltype.shape[0] != exp_nor_pd.shape[0]:
            raise ValueError(
                "cellmeta_data does not align with gene_exp.csv by index or row order."
            )

    adata.obs["Celltype"] = celltype
    adata.obs["cell_type"] = celltype
    adata.obs["cell.type"] = celltype
    adata.obs["cell_class"] = celltype
    adata.obs["sample_name"] = f"{setting_name}_Experiment_{experiment_index}"
    adata.obs["batch"] = f"{setting_name}_Experiment_{experiment_index}"
    adata.obs["xcoord"] = adata.obsm["spatial"][:, 0]
    adata.obs["ycoord"] = adata.obsm["spatial"][:, 1]
    return adata


def _prepare_simulation_processed_bundle(
    processed_data_dir,
    SpiderNet_data_pyg,
    exp_nor_pd,
    spatial_location,
    cellmeta_data,
    LR_list,
    Setting_cur,
    experiment_index,
):
    """Save a one-batch processed bundle compatible with HGSOC_modeltraining."""
    processed_data_dir = Path(processed_data_dir)
    processed_data_dir.mkdir(parents=True, exist_ok=True)

    sample_name = f"{Setting_cur}_Experiment_{experiment_index}"
    adata = _make_simulation_adata(
        exp_nor_pd=exp_nor_pd,
        spatial_location=spatial_location,
        cellmeta_data=cellmeta_data,
        setting_name=Setting_cur,
        experiment_index=experiment_index,
    )

    spidernet_data_cpu = _safe_to_cpu_data(SpiderNet_data_pyg)
    lr_array = np.asarray(LR_list).astype(str)
    genenames_train = np.asarray(exp_nor_pd.columns).astype(str)
    cellclass_unique = np.sort(cellmeta_data["Celltype"].astype(str).unique())
    batch_cell = np.zeros(adata.n_obs, dtype=np.int64)
    batch_cell_unique = np.asarray([sample_name])

    _write_pickle([spidernet_data_cpu], processed_data_dir / "SpiderNet_data_pyg_list.pkl")
    _write_pickle(lr_array, processed_data_dir / "LR_list.pkl")

    # The HGSOC bundle includes these database-derived LR metadata files.
    # The simulation LR list is synthetic, so we provide minimal compatible
    # placeholders that preserve the same file contract.
    _write_pickle(lr_array, processed_data_dir / "LR_list_cellchatdb.pkl")
    lr_meta = pd.DataFrame({
        "ligand": lr_array[:, 0] if lr_array.size else [],
        "receptor": lr_array[:, 1] if lr_array.size else [],
        "pathway_name": ["Simulation"] * lr_array.shape[0],
    })
    _write_pickle(lr_meta, processed_data_dir / "LR_meta_cellchatdb.pkl")

    _write_pickle(batch_cell_unique, processed_data_dir / "batch_cell_unique.pkl")
    _write_pickle(batch_cell, processed_data_dir / "batch_cell.pkl")
    _write_pickle(genenames_train, processed_data_dir / "genenames_train.pkl")
    _write_pickle([adata], processed_data_dir / "adata_list.pkl")
    _write_pickle(cellclass_unique, processed_data_dir / "cellclass_unique.pkl")
    adata.write_h5ad(processed_data_dir / "adata_all.h5ad")

    metadata_sample = pd.DataFrame({
        "sample_name": [sample_name],
        "setting": [Setting_cur],
        "experiment": [experiment_index],
        "n_cells": [adata.n_obs],
        "n_genes": [adata.n_vars],
        "n_lr_pairs": [lr_array.shape[0]],
    })
    metadata_sample.to_csv(processed_data_dir / "metadata_sample.csv", index=False)

    bundle_summary = {
        "dataset": "Simulation",
        "setting": Setting_cur,
        "experiment": int(experiment_index),
        "n_batches": 1,
        "n_cells": int(adata.n_obs),
        "n_genes": int(adata.n_vars),
        "n_lr_pairs": int(lr_array.shape[0]),
    }
    with open(processed_data_dir / "bundle_summary.json", "w", encoding="utf-8") as handle:
        json.dump(bundle_summary, handle, indent=2)

    return processed_data_dir


def _make_training_config_for_simulation():
    """Create a TrainingConfig and keep simulation hyperparameters if supported."""
    train_cfg = TrainingConfig(
        dim_envir=dim_envir,
        n_jobs=n_jobs,
        max_epoch=max_epoch,
        version=VERSION,
    )

    # Newer SpiderNet.config versions expose these as dataclass fields; older
    # versions may keep them as defaults inside build_model/run_training. Set
    # only fields that exist so this script remains compatible across versions.
    optional_cfg_values = {
        "factor_mode": Factor_mode,
        "Factor_mode": Factor_mode,
        "hidden_channels": hidden_channels,
        "lr": lr,
        "weight_decay": weight_decay,
        "loss_fn": loss_fn,
        "warmup": warmup,
        "LR_loss_weight": LR_loss_weight,
        "threshold_crosscorr": threshold_crosscorr,
        "initial_regression": Initial_regression,
        "Initial_regression": Initial_regression,
        "agg_type": "mean",
        "act_factor": "sigmoid",
    }
    if Factor_mode == "NMF":
        optional_cfg_values["dim_intri"] = dim_intri

    for key, value in optional_cfg_values.items():
        if hasattr(train_cfg, key):
            setattr(train_cfg, key, value)
    return train_cfg


def _get_processed_spidernet_data_list(processed):
    if hasattr(processed, "spidernet_data"):
        return processed.spidernet_data
    if hasattr(processed, "spidernet_data_pyg_list"):
        return processed.spidernet_data_pyg_list
    if hasattr(processed, "SpiderNet_data_pyg_list"):
        return processed.SpiderNet_data_pyg_list
    raise AttributeError("The processed object does not contain a SpiderNet_data_pyg list.")


def _result_array(results, aliases, required=True):
    for key in aliases:
        if key in results:
            value = results[key]
            if torch.is_tensor(value):
                return value.detach().cpu().numpy()
            return np.asarray(value)
    if required:
        raise KeyError(f"None of the result keys were found: {aliases}")
    return None


def _model_parameter_array(model, aliases, required=False):
    if not hasattr(model, "named_parameters"):
        if required:
            raise AttributeError("Model has no named_parameters method.")
        return None

    for name, param in model.named_parameters():
        for alias in aliases:
            if name == alias or name.endswith(alias) or alias in name:
                arr = param.detach().cpu().numpy()
                # Loading parameters are constrained as non-negative in SpiderNet.
                return np.maximum(arr, 0)

    if required:
        raise KeyError(f"None of the model parameter aliases were found: {aliases}")
    return None


def _result_or_model_array(results, model, result_aliases, model_aliases, required=True):
    arr = _result_array(results, result_aliases, required=False)
    if arr is not None:
        return arr
    arr = _model_parameter_array(model, model_aliases, required=False)
    if arr is not None:
        return arr
    if required:
        raise KeyError(
            "Could not locate output in normalized inference results or model parameters. "
            f"Result aliases: {result_aliases}; model aliases: {model_aliases}"
        )
    return None


def _as_device_tensor(arr):
    return torch.as_tensor(np.asarray(arr), dtype=torch.float32, device=device)


def _write_training_provenance(run_dir, processed_data_dir, train_cfg):
    provenance = {
        "processed_data_dir": str(processed_data_dir),
        "run_dir": str(run_dir),
        "model_dir": str(Path(run_dir) / "Model"),
        "dataset": "Simulation",
        "setting": Setting_cur,
        "experiment": int(experiment_index),
        "dim_envir": dim_envir,
        "factor_mode": Factor_mode,
        "n_jobs": n_jobs,
        "max_epoch": max_epoch,
        "version": VERSION,
        "model_training_source": "SpiderNet.api pipeline used by HGSOC_modeltraining",
    }
    if hasattr(train_cfg, "to_dict"):
        provenance["train_cfg"] = train_cfg.to_dict()

    with open(Path(run_dir) / "SpiderNet_training_provenance.json", "w", encoding="utf-8") as handle:
        json.dump(provenance, handle, indent=2)



num_neigh = 10
Factor_mode = "cell_class"
if Factor_mode == "NMF":
    dim_intri = 25

dim_envir = 2
hidden_channels = 128
lr = 5e-4
weight_decay = 1e-5
loss_fn = "mse"
warmup = 1000
max_epoch = 30000
LR_loss_weight = 1
if_addselfloop = False
threshold_crosscorr = 0.1
numtop = 300
num_celltypes = 3
n_jobs = 5
Initial_regression = "Linear"
If_simple = True

SETTING_LIST = ["Dropout1", "Dropout2", "Dropout3", "Sd_use1", "Sd_use2", "Sd_use3"]
DATA_ROOT = r"D:/SpiderNet/Data/Simulation"
RESULT_ROOT = r"D:/SpiderNet/Results/Simulation"
SPIDERNET_RESULT_ROOT = os.path.join(RESULT_ROOT, "SpiderNet")
SCCCHAIN_RESULT_ROOT = os.path.join(RESULT_ROOT, "ScCChain")
SPACIA_RESULT_ROOT = os.path.join(RESULT_ROOT, "Spacia")

parser = argparse.ArgumentParser(description="Experiment arguments")
parser.add_argument("--setting", type=int, default=0, help="Setting index")
parser.add_argument("--experiment", type=int, default=0, help="Experiment index")
args = parser.parse_args()

Setting_cur = SETTING_LIST[args.setting]
experiment_index = args.experiment

print("Setting:", Setting_cur, "Experiment index:", experiment_index)

data_path_main_cur = os.path.join(DATA_ROOT, Setting_cur, f"Experiment_{experiment_index}") + "/"
save_path_main_cur = os.path.join(SPIDERNET_RESULT_ROOT, Setting_cur, f"Experiment_{experiment_index}") + "/"
os.makedirs(save_path_main_cur, exist_ok=True)

cellmeta_data_dir = os.path.join(data_path_main_cur, "cell_metadf.csv")
genemeta_data_dir = os.path.join(data_path_main_cur, "gene_metadf.csv")
edgemeta_data_dir = os.path.join(data_path_main_cur, "edge_metadf.csv")
cell_neigh_metaIprop_dir = os.path.join(data_path_main_cur, "cell_neigh_metaIprop.csv")
location_data_dir = os.path.join(data_path_main_cur, "spatial_location.csv")

file_savepath_main = os.path.join(save_path_main_cur, f"SpiderNet_Result_Mode_{Factor_mode}") + "/"
file_savepath_MI_main = os.path.join(file_savepath_main, "MetaInteraction") + "/"
file_savepath_model_main = os.path.join(file_savepath_main, "Model") + "/"
file_savepath_log_main = os.path.join(file_savepath_main, "log") + "/"

os.makedirs(file_savepath_main, exist_ok=True)
os.makedirs(file_savepath_MI_main, exist_ok=True)
os.makedirs(file_savepath_model_main, exist_ok=True)
os.makedirs(file_savepath_log_main, exist_ok=True)

print("Step 1: load data and prepare inputs")
exp_nor_pd = pd.read_csv(os.path.join(data_path_main_cur, "gene_exp.csv"), index_col=0)
cellmeta_data = pd.read_csv(cellmeta_data_dir, index_col=0)
genemeta_data = pd.read_csv(genemeta_data_dir, index_col=0)
edgemeta_data = pd.read_csv(edgemeta_data_dir, index_col=0)
cell_neigh_metaIprop = pd.read_csv(cell_neigh_metaIprop_dir, index_col=0)
spatial_location = pd.read_csv(location_data_dir, index_col=0)

Ligand_output = list(genemeta_data.index[np.where(genemeta_data["Gene_type"] == "Ligand")[0]])
Receptor_output = list(genemeta_data.index[np.where(genemeta_data["Gene_type"] == "Receptor")[0]])
LR_list = np.vstack((Ligand_output, Receptor_output)).T

SpiderNet_data = {}
SpiderNet_data["num_cells"] = exp_nor_pd.shape[0]
SpiderNet_data["cellnames"] = np.array(list(exp_nor_pd.index))
SpiderNet_data["num_genes"] = exp_nor_pd.shape[1]
SpiderNet_data["genenames"] = np.array(list(exp_nor_pd.columns))
SpiderNet_data["spatial_location"] = spatial_location.values
SpiderNet_data["expression_normalized"] = exp_nor_pd.values
SpiderNet_data["cell_class"] = cellmeta_data["Celltype"]

spatial_neighborindex_use, edge_index = spatial_neighborindex_generation(
    cell_spatial=SpiderNet_data["spatial_location"],
    num_neighbor_available=num_neigh,
)
del spatial_neighborindex_use

if if_addselfloop:
    edge_index = np.vstack(
        (
            edge_index,
            np.vstack(
                (
                    np.arange(0, SpiderNet_data["num_cells"]),
                    np.arange(0, SpiderNet_data["num_cells"]),
                )
            ).T,
        )
    )

edge_index = torch.tensor(edge_index, dtype=torch.long).to(device)
print("The number of edges:", edge_index.shape[0])

adj_matrix = torch.sparse_coo_tensor(
    torch.tensor(edge_index).T.to(device),
    torch.ones(edge_index.shape[0]).to(device),
    torch.Size([SpiderNet_data["num_cells"], SpiderNet_data["num_cells"]]),
).to(device)
torch.cuda.empty_cache()

cellclass = SpiderNet_data["cell_class"].astype("category")
cellclass_unique = np.sort(np.array(cellclass.unique()))
cellclass_onehot = np.zeros((SpiderNet_data["num_cells"], cellclass_unique.shape[0]))
for i in range(cellclass_unique.shape[0]):
    cellclass_onehot[cellclass == cellclass_unique[i], i] = 1

cellclass_onehot_pd = pd.DataFrame(cellclass_onehot, columns=cellclass_unique)
cellclass_onehot_pd.index = SpiderNet_data["cellnames"]

SpiderNet_data_pyg = Data(
    x=torch.tensor(SpiderNet_data["expression_normalized"], dtype=torch.float),
    edge_index=edge_index,
    adj_matrix_sparse=adj_matrix,
    pos=torch.tensor(SpiderNet_data["spatial_location"], dtype=torch.float),
    cell_class_onehot=torch.tensor(cellclass_onehot, dtype=torch.float),
    cell_class_unique=np.array(cellclass_onehot_pd.columns).tolist(),
    cellnames=np.array(SpiderNet_data["cellnames"]),
    genenames=np.array(SpiderNet_data["genenames"]),
    num_cells=SpiderNet_data["num_cells"],
    num_genes=SpiderNet_data["num_genes"],
)

del adj_matrix, cellclass_onehot, cellclass_onehot_pd, edge_index

edge_index1 = SpiderNet_data_pyg.edge_index.to("cpu")
cellpair_LRpair_neigh = np.zeros((edge_index1.shape[0], LR_list.shape[0]))

for LRpair_index in range(LR_list.shape[0]):
    ligand_index_cur = np.where(SpiderNet_data["genenames"] == LR_list[LRpair_index, 0])[0][0]
    receptor_index_cur = np.where(SpiderNet_data["genenames"] == LR_list[LRpair_index, 1])[0][0]
    exp_ligand = np.array(SpiderNet_data["expression_normalized"][:, ligand_index_cur])
    exp_receptor = np.array(SpiderNet_data["expression_normalized"][:, receptor_index_cur])

    cellpair_LRpair_neigh[:, LRpair_index] = np.power(
        exp_ligand[edge_index1[:, 0]] * exp_receptor[edge_index1[:, 1]],
        0.5,
    )

SpiderNet_data_pyg["edge_index"] = torch.tensor(edge_index1, dtype=torch.long)
SpiderNet_data_pyg["cellpair_LRpair_neigh"] = torch.tensor(cellpair_LRpair_neigh)
del edge_index1, cellpair_LRpair_neigh

SpiderNet_data_pyg = SpiderNet_data_pyg.to(device)

exp_nor = SpiderNet_data["expression_normalized"]
exp_nor_T = exp_nor.T
del exp_nor
genenames = SpiderNet_data["genenames"]
cellnames = SpiderNet_data["cellnames"]
cellmetadata = pd.DataFrame(
    {
        "Cell_ID": cellnames,
        "Cluster_ID": SpiderNet_data["cell_class"],
    }
)

# Prepare a one-batch processed bundle and run the same model API used by HGSOC_modeltraining.
VERSION = "V1"
processed_data_dir = Path(save_path_main_cur) / "ProcessedData"
processed_data_dir = _prepare_simulation_processed_bundle(
    processed_data_dir=processed_data_dir,
    SpiderNet_data_pyg=SpiderNet_data_pyg,
    exp_nor_pd=exp_nor_pd,
    spatial_location=spatial_location,
    cellmeta_data=cellmeta_data,
    LR_list=LR_list,
    Setting_cur=Setting_cur,
    experiment_index=experiment_index,
)

processed = load_processed_data(processed_data_dir)
print("Processed directory:", processed_data_dir)
print("Number of batches:", len(_get_processed_spidernet_data_list(processed)))
if hasattr(processed, "lr_list"):
    print("Number of LR pairs:", len(processed.lr_list))
if hasattr(processed, "genenames_train"):
    print("Number of training genes:", processed.genenames_train.shape[0])

train_cfg = _make_training_config_for_simulation()
print("Training config:", train_cfg)

model = build_model(
    processed=processed,
    train_cfg=train_cfg,
    device=device,
)

print(model)
for name, param in model.named_parameters():
    print(name, param.size(), "Trainable:", param.requires_grad)

trainable, non_trainable = count_parameters(model)
print("Total trainable parameters:", trainable)
print("Total non-trainable parameters:", non_trainable)

model = run_training(
    model=model,
    processed=processed,
    train_cfg=train_cfg,
    model_dir=Path(file_savepath_model_main),
    device=device,
)

results_raw = infer_meta_interactions(model=model, processed=processed)
results = normalize_outputs(results_raw)

export_results(
    results=results,
    processed=processed,
    precessed_data_dir=processed_data_dir,
    output_dir=Path(file_savepath_main),
)

with open(Path(file_savepath_model_main) / "SpiderNet_model_config.json", "w", encoding="utf-8") as handle:
    if hasattr(train_cfg, "to_dict"):
        json.dump(train_cfg.to_dict(), handle, indent=2)
    else:
        json.dump(vars(train_cfg), handle, indent=2, default=str)
_write_training_provenance(file_savepath_main, processed_data_dir, train_cfg)
print(f"Results saved to: {file_savepath_main}")

# Keep old downstream plotting/benchmark code working by exposing the same tensor names.
Factor_envir = _as_device_tensor(
    _result_or_model_array(
        results,
        model,
        result_aliases=["factor_envir", "Factor_envir", "Factor_envir_use"],
        model_aliases=[],
    )
)
loading_LR = _as_device_tensor(
    _result_or_model_array(
        results,
        model,
        result_aliases=["loading_lr", "loading_LR", "Loading_LR", "loading_LR_use"],
        model_aliases=["loading_LR_ori", "loading_lr_ori"],
    )
)
loading_receiver = _as_device_tensor(
    _result_or_model_array(
        results,
        model,
        result_aliases=["loading_receiver", "Loading_receiver", "loading_receiver_use"],
        model_aliases=["loading_receiver_ori"],
    )
)
loading_sender = _as_device_tensor(
    _result_or_model_array(
        results,
        model,
        result_aliases=["loading_sender", "Loading_sender", "loading_sender_use"],
        model_aliases=["loading_sender_ori"],
    )
)
Loading_intrinsic = _as_device_tensor(
    _result_or_model_array(
        results,
        model,
        result_aliases=["loading_intrinsic", "Loading_intrinsic", "loading_intrinsic_use"],
        model_aliases=["Loading_intrinsic_ori", "loading_intrinsic_ori"],
    )
)

SpiderNet_data_pyg = _get_processed_spidernet_data_list(processed)[0].to(device)
print("Available normalized result keys:", list(results.keys()))



def _normalize_loading_rows_for_summary(arr):
    arr = np.asarray(arr, dtype=float)
    if arr.ndim == 1:
        row_sum = np.nansum(arr)
        if (not np.isfinite(row_sum)) or row_sum <= 0:
            return np.zeros_like(arr, dtype=float)
        out = arr / row_sum
        out[~np.isfinite(out)] = 0.0
        return out

    out = arr.copy()
    if out.size == 0:
        return out
    row_sum = np.nansum(out, axis=1, keepdims=True)
    row_sum[(~np.isfinite(row_sum)) | (row_sum <= 0)] = 1.0
    out = out / row_sum
    out[~np.isfinite(out)] = 0.0
    return out



def _normalize_loading_columns_for_summary(arr):
    arr = np.asarray(arr, dtype=float)
    if arr.ndim == 1:
        col_sum = np.nansum(arr)
        if (not np.isfinite(col_sum)) or col_sum <= 0:
            return np.zeros_like(arr, dtype=float)
        out = arr / col_sum
        out[~np.isfinite(out)] = 0.0
        return out

    out = arr.copy()
    if out.size == 0:
        return out
    col_sum = np.nansum(out, axis=0, keepdims=True)
    col_sum[(~np.isfinite(col_sum)) | (col_sum <= 0)] = 1.0
    out = out / col_sum
    out[~np.isfinite(out)] = 0.0
    return out



def _build_loading_truth_index_dict(n_lr, n_gene):
    lr_split = max(1, n_lr // 2)
    return {
        "lr_idx_mi1": np.arange(0, lr_split),
        "lr_idx_mi2": np.arange(lr_split, n_lr),
        "sender_idx_mi1": np.arange(min(40, n_gene), min(50, n_gene)),
        "sender_idx_mi2": np.arange(min(50, n_gene), min(60, n_gene)),
        "receiver_idx_mi1": np.arange(min(60, n_gene), min(70, n_gene)),
        "receiver_idx_mi2": np.arange(min(70, n_gene), min(80, n_gene)),
    }



def _mean_component_share_on_block(arr_colnorm, row_idx, col_idx):
    if row_idx is None or arr_colnorm.ndim != 2 or arr_colnorm.shape[0] == 0:
        return np.nan
    if row_idx >= arr_colnorm.shape[0] or col_idx.size == 0:
        return np.nan
    vals = arr_colnorm[row_idx, col_idx]
    if vals.size == 0:
        return np.nan
    return float(np.nanmean(vals))



def _top1_hit_ratio_on_block(arr_colnorm, row_idx, col_idx):
    if row_idx is None or arr_colnorm.ndim != 2 or arr_colnorm.shape[0] == 0:
        return np.nan
    if row_idx >= arr_colnorm.shape[0] or col_idx.size == 0:
        return np.nan
    sub = arr_colnorm[:, col_idx]
    if sub.size == 0:
        return np.nan
    top_rows = np.nanargmax(sub, axis=0)
    return float(np.mean(top_rows == row_idx))



def _rank_ratio_on_block(arr_colnorm, row_idx, col_idx):
    mean_share = _mean_component_share_on_block(arr_colnorm, row_idx, col_idx)
    top1_ratio = _top1_hit_ratio_on_block(arr_colnorm, row_idx, col_idx)
    return float(np.nanmean([mean_share, top1_ratio]))



def _match_components_by_lr_block(loading_lr):
    loading_lr_colnorm = _normalize_loading_columns_for_summary(loading_lr)
    if loading_lr_colnorm.ndim == 1:
        loading_lr_colnorm = loading_lr_colnorm.reshape(1, -1)

    n_comp = loading_lr_colnorm.shape[0]
    truth_idx = _build_loading_truth_index_dict(n_lr=loading_lr_colnorm.shape[1], n_gene=0)
    lr_idx_mi1 = truth_idx["lr_idx_mi1"]
    lr_idx_mi2 = truth_idx["lr_idx_mi2"]

    mi1_scores = np.array([
        _rank_ratio_on_block(loading_lr_colnorm, i, lr_idx_mi1)
        for i in range(n_comp)
    ], dtype=float)
    mi2_scores = np.array([
        _rank_ratio_on_block(loading_lr_colnorm, i, lr_idx_mi2)
        for i in range(n_comp)
    ], dtype=float)

    if n_comp == 0:
        return {
            "mi1_component": None,
            "mi2_component": None,
            "mi1_scores": mi1_scores,
            "mi2_scores": mi2_scores,
        }

    if n_comp == 1:
        mi1_component = 0
        mi2_component = 0
    else:
        best_pair = None
        best_score = -np.inf
        for i in range(n_comp):
            for j in range(n_comp):
                if i == j:
                    continue
                score = np.nan_to_num(mi1_scores[i], nan=-np.inf) + np.nan_to_num(mi2_scores[j], nan=-np.inf)
                if score > best_score:
                    best_score = score
                    best_pair = (i, j)
        if best_pair is None:
            mi1_component = int(np.nanargmax(np.nan_to_num(mi1_scores, nan=-np.inf)))
            remaining = [k for k in range(n_comp) if k != mi1_component]
            if len(remaining) == 0:
                mi2_component = mi1_component
            else:
                rem_scores = mi2_scores[remaining]
                mi2_component = int(remaining[int(np.nanargmax(np.nan_to_num(rem_scores, nan=-np.inf)))])
        else:
            mi1_component, mi2_component = best_pair

    return {
        "mi1_component": int(mi1_component),
        "mi2_component": int(mi2_component),
        "mi1_scores": mi1_scores,
        "mi2_scores": mi2_scores,
    }



def _build_ordered_loading_component_labels(n_comp, mi1_component, mi2_component):
    ordered_components = []
    if mi1_component is not None:
        ordered_components.append(mi1_component)
    if mi2_component is not None and mi2_component not in ordered_components:
        ordered_components.append(mi2_component)
    ordered_components.extend([i for i in range(n_comp) if i not in ordered_components])

    labels = []
    for comp_idx in ordered_components:
        if comp_idx == mi1_component:
            labels.append("Matched MI-1")
        elif comp_idx == mi2_component:
            labels.append("Matched MI-2")
        else:
            labels.append(f"Component {comp_idx + 1}")
    return ordered_components, labels

Loading_intrinsic_use = Loading_intrinsic.to("cpu").detach().numpy()
Loading_intrinsic_use_colSums = np.sum(Loading_intrinsic_use, axis=0)
Loading_intrinsic_use_colSums[Loading_intrinsic_use_colSums == 0] = 1
Loading_intrinsic_norm = Loading_intrinsic_use / Loading_intrinsic_use_colSums

loading_LR_use = loading_LR.to("cpu").detach().numpy()
loading_sender_use = loading_sender.to("cpu").detach().numpy()
loading_receiver_use = loading_receiver.to("cpu").detach().numpy()

loading_match_info = _match_components_by_lr_block(loading_LR_use)
mi1_component = loading_match_info["mi1_component"]
mi2_component = loading_match_info["mi2_component"]
ordered_components, ordered_component_labels = _build_ordered_loading_component_labels(
    n_comp=loading_LR_use.shape[0],
    mi1_component=mi1_component,
    mi2_component=mi2_component,
)

set_figure_style()
plt.close("all")
fig, ax = plt.subplots()
cax = ax.imshow(Loading_intrinsic_norm, aspect="auto")
plt.colorbar(cax)
plt.xlabel("Gene")
plt.ylabel("Cell type")
plt.title("Normalized loading matrix of intrinsic genes")
celltype_labels = ["Celltype A", "Celltype B", "Celltype C"]
ax.set_yticks(np.arange(len(celltype_labels)))
ax.set_yticklabels(celltype_labels)
ax.set_xticks([])
save_ai_pdf(fig, os.path.join(file_savepath_main, "Normalized_loading_intrinsic.pdf"), transparent=True)
plt.close(fig)

loading_LR_plot = loading_LR_use[ordered_components, :]
loading_LR_use_colSums = np.sum(loading_LR_plot, axis=0)
loading_LR_use_colSums[loading_LR_use_colSums == 0] = 1
loading_LR_norm = loading_LR_plot / loading_LR_use_colSums
lr_loading_cmap = make_linear_cmap(
    ["#FFFFFF", "#636491"],
    "lr_loading_cmap",
)

mat = loading_LR_norm
n_rows, n_cols = mat.shape
fig_w = max(4.5, min(12, 0.18 * n_cols))
fig_h = 1.6 + 0.35 * n_rows
lr_labels = [f"LR-{i+1}" for i in range(n_cols)]

plot_matrix_heatmap(
    mat=mat,
    row_labels=ordered_component_labels,
    out_path=os.path.join(file_savepath_main, "Normalized_loading_LR.pdf"),
    xlabel="LR pair",
    ylabel="Meta-interaction",
    cmap=lr_loading_cmap,
    fig_w=fig_w,
    fig_h=fig_h,
    x_tick_labels=lr_labels,
    max_xticks=25,
    show_x_ticks=True,
)

loading_envir_use = np.vstack(
    [
        loading_sender_use[mi1_component, :],
        loading_receiver_use[mi1_component, :],
        loading_sender_use[mi2_component, :],
        loading_receiver_use[mi2_component, :],
    ]
)
loading_envir_use = pd.DataFrame(
    loading_envir_use,
    columns=SpiderNet_data_pyg["genenames"],
    index=["MI-1_sending", "MI-1_receiving", "MI-2_sending", "MI-2_receiving"],
)

loading_envir_use = loading_envir_use.to_numpy()
loading_envir_use_colSums = np.sum(loading_envir_use, axis=0)
loading_envir_use_colSums[loading_envir_use_colSums == 0] = 1
loading_envir_use_norm = loading_envir_use / loading_envir_use_colSums
loading_envir_use_norm = pd.DataFrame(
    loading_envir_use_norm,
    columns=SpiderNet_data_pyg["genenames"],
    index=["MI-1_sending", "MI-1_receiving", "MI-2_sending", "MI-2_receiving"],
)

full_loading_cmap = make_linear_cmap(["#FFFFFF", "#BDBDBD", "#4D4D4D"], "full_loading_cmap")

plot_matrix_heatmap(
    mat=loading_envir_use_norm.values,
    row_labels=list(loading_envir_use_norm.index),
    out_path=os.path.join(file_savepath_main, "Normalized_loading_envir.pdf"),
    xlabel="Genes",
    ylabel="",
    cmap=full_loading_cmap,
    fig_w=6.0,
    fig_h=1.6,
    x_tick_labels=None,
    show_x_ticks=False,
)

regulator_col_start = 40
regulator_col_end = 60
target_col_start = 60
target_col_end = 80

regulator_loading_norm = loading_envir_use_norm.iloc[:, regulator_col_start:regulator_col_end].copy()
target_loading_norm = loading_envir_use_norm.iloc[:, target_col_start:target_col_end].copy()

regulator_cmap = make_linear_cmap(["#FFFFFF", "#43C5E3"], "regulator_loading_cmap")
target_cmap = make_linear_cmap(["#FFFFFF", "#E5352A"], "target_loading_cmap")

plot_matrix_heatmap(
    mat=regulator_loading_norm.values,
    row_labels=list(regulator_loading_norm.index),
    out_path=os.path.join(file_savepath_main, "Normalized_loading_envir_regulator_genes.pdf"),
    xlabel="Regulator genes",
    ylabel="",
    cmap=regulator_cmap,
    fig_w=max(4.5, 0.22 * regulator_loading_norm.shape[1]),
    fig_h=1.6,
    x_tick_labels=list(regulator_loading_norm.columns),
    max_xticks=20,
    show_x_ticks=True,
)

plot_matrix_heatmap(
    mat=target_loading_norm.values,
    row_labels=list(target_loading_norm.index),
    out_path=os.path.join(file_savepath_main, "Normalized_loading_envir_target_genes.pdf"),
    xlabel="Target genes",
    ylabel="",
    cmap=target_cmap,
    fig_w=max(4.5, 0.22 * target_loading_norm.shape[1]),
    fig_h=1.6,
    x_tick_labels=list(target_loading_norm.columns),
    max_xticks=20,
    show_x_ticks=True,
)

# Additional heatmaps for selected rows and columns of loading_envir_use_norm
# Select columns 41-80 from loading_envir_use first, then normalize within this subset

import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
from matplotlib.colors import Normalize
from matplotlib.patches import Rectangle

def plot_matrix_heatmap_vector(
    mat,
    row_labels,
    out_path,
    xlabel,
    ylabel,
    cmap,
    fig_w,
    fig_h,
    x_tick_labels=None,
    max_xticks=25,
    show_x_ticks=True,
    cbar_fraction=0.03,
    cbar_pad=0.02,
    cell_edgecolor="none",
    cell_linewidth=0.0,
):
    set_figure_style()
    plt.close("all")

    mat = np.asarray(mat, dtype=float)
    n_rows, n_cols = mat.shape

    fig, ax = plt.subplots(figsize=(fig_w, fig_h))

    vmin = np.nanmin(mat)
    vmax = np.nanmax(mat)
    if vmin == vmax:
        vmax = vmin + 1e-8

    norm = Normalize(vmin=vmin, vmax=vmax)
    cmap_obj = mpl.colormaps[cmap] if isinstance(cmap, str) else cmap

    # Draw each heatmap cell as an individual vector rectangle
    for i in range(n_rows):
        for j in range(n_cols):
            val = mat[i, j]
            facecolor = cmap_obj(norm(val))
            rect = Rectangle(
                (j, i), 1, 1,
                facecolor=facecolor,
                edgecolor=cell_edgecolor,
                linewidth=cell_linewidth
            )
            ax.add_patch(rect)

    # Set axis limits and invert y-axis to match heatmap convention
    ax.set_xlim(0, n_cols)
    ax.set_ylim(n_rows, 0)

    # Y-axis labels
    ax.set_yticks(np.arange(n_rows) + 0.5)
    ax.set_yticklabels(row_labels, fontsize=8)
    ax.set_ylabel(ylabel, fontsize=9)
    ax.set_xlabel(xlabel, fontsize=9)

    # X-axis labels
    if show_x_ticks:
        if x_tick_labels is None:
            x_tick_labels = [str(i + 1) for i in range(n_cols)]
        step = max(1, int(np.ceil(n_cols / max_xticks)))
        xticks = np.arange(0, n_cols, step) + 0.5
        ax.set_xticks(xticks)
        ax.set_xticklabels(
            [x_tick_labels[i] for i in range(0, n_cols, step)],
            rotation=45,
            ha="right",
            fontsize=7
        )
    else:
        ax.set_xticks([])

    # Clean frame
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)

    # ScalarMappable only for colorbar
    sm = mpl.cm.ScalarMappable(norm=norm, cmap=cmap_obj)
    sm.set_array([])
    cbar = fig.colorbar(sm, ax=ax, fraction=cbar_fraction, pad=cbar_pad)
    cbar.ax.tick_params(labelsize=8, width=0.8, length=3)
    cbar.outline.set_linewidth(0.8)

    fig.tight_layout()
    save_ai_pdf(fig, out_path, transparent=True)
    plt.close(fig)

loading_envir_use_subset_41_80 = loading_envir_use[:, 40:80].copy()

loading_envir_use_subset_41_80_colSums = np.sum(loading_envir_use_subset_41_80, axis=0)
loading_envir_use_subset_41_80_colSums[loading_envir_use_subset_41_80_colSums == 0] = 1

loading_envir_use_subset_41_80_norm = (
    loading_envir_use_subset_41_80 / loading_envir_use_subset_41_80_colSums
)

loading_envir_use_subset_41_80_norm = pd.DataFrame(
    loading_envir_use_subset_41_80_norm,
    columns=SpiderNet_data_pyg["genenames"][40:80],
    index=["MI-1_sending", "MI-1_receiving", "MI-2_sending", "MI-2_receiving"],
)

# Select rows 1 and 3 (human counting) after subset normalization
sending_rows_loading_norm = loading_envir_use_subset_41_80_norm.iloc[[0, 2], :].copy()

# Select rows 2 and 4 (human counting) after subset normalization
receiving_rows_loading_norm = loading_envir_use_subset_41_80_norm.iloc[[1, 3], :].copy()

sending_rows_cmap = make_linear_cmap(["#FFFFFF", "#43C5E3"], "sending_rows_loading_cmap")
receiving_rows_cmap = make_linear_cmap(["#FFFFFF", "#E5352A"], "receiving_rows_loading_cmap")

plot_matrix_heatmap_vector(
    mat=sending_rows_loading_norm.values,
    row_labels=list(sending_rows_loading_norm.index),
    out_path=os.path.join(file_savepath_main, "Normalized_loading_envir_rows1_3_cols41_80.pdf"),
    xlabel="Genes",
    ylabel="",
    cmap=sending_rows_cmap,
    fig_w=max(5.5, 0.20 * sending_rows_loading_norm.shape[1]),
    fig_h=1.25,
    x_tick_labels=list(sending_rows_loading_norm.columns),
    max_xticks=20,
    show_x_ticks=True,
    cell_edgecolor="none",
    cell_linewidth=0.0,
)

plot_matrix_heatmap_vector(
    mat=receiving_rows_loading_norm.values,
    row_labels=list(receiving_rows_loading_norm.index),
    out_path=os.path.join(file_savepath_main, "Normalized_loading_envir_rows2_4_cols41_80.pdf"),
    xlabel="Genes",
    ylabel="",
    cmap=receiving_rows_cmap,
    fig_w=max(5.5, 0.20 * receiving_rows_loading_norm.shape[1]),
    fig_h=1.25,
    x_tick_labels=list(receiving_rows_loading_norm.columns),
    max_xticks=20,
    show_x_ticks=True,
    cell_edgecolor="none",
    cell_linewidth=0.0,
)

if if_showinsitu:
    # ============================================================
    # Additional baseline in situ plots across methods
    # ============================================================

    def _safe_column_max_normalize(arr):
        arr = np.asarray(arr, dtype=float)
        if arr.ndim == 1:
            max_val = np.nanmax(arr)
            if (not np.isfinite(max_val)) or max_val <= 0:
                return np.zeros_like(arr, dtype=float)
            return arr / max_val

        arr_norm = arr.copy()
        col_max = np.nanmax(arr_norm, axis=0)
        col_max[(~np.isfinite(col_max)) | (col_max <= 0)] = 1.0
        arr_norm = arr_norm / col_max
        arr_norm[~np.isfinite(arr_norm)] = 0.0
        return arr_norm


    def find_sccchain_csv(sample_result_root):
        import glob

        pattern = os.path.join(sample_result_root, "*_ScCChain_edge_program_scores.csv")
        files = sorted(glob.glob(pattern))
        if len(files) == 0:
            raise FileNotFoundError(f"No ScCChain result file found in: {sample_result_root}")
        return files[0]


    def load_sccchain_scores_to_reference_edges(sc_csv_path, edge_index):
        sc_df = pd.read_csv(sc_csv_path)
        if sc_df.shape[1] < 3:
            raise ValueError(f"Unexpected ScCChain CSV format: {sc_csv_path}")

        sender_col = sc_df.columns[0]
        receiver_col = sc_df.columns[1]
        program_cols = sc_df.columns.tolist()[2:]

        sc_df = sc_df.rename(columns={
            sender_col: "sender_index",
            receiver_col: "receiver_index",
        }).copy()

        sc_df["sender_index"] = pd.to_numeric(sc_df["sender_index"], errors="coerce").astype("Int64")
        sc_df["receiver_index"] = pd.to_numeric(sc_df["receiver_index"], errors="coerce").astype("Int64")
        sc_df = sc_df.dropna(subset=["sender_index", "receiver_index"]).copy()
        sc_df["sender_index"] = sc_df["sender_index"].astype(np.int64)
        sc_df["receiver_index"] = sc_df["receiver_index"].astype(np.int64)

        # Julia output is 1-based.
        sc_df["sender_index"] -= 1
        sc_df["receiver_index"] -= 1

        edge_index_df = pd.DataFrame(edge_index, columns=["sender_index", "receiver_index"])
        edge_mi = pd.MultiIndex.from_frame(edge_index_df[["sender_index", "receiver_index"]])

        sc_df = sc_df.drop_duplicates(subset=["sender_index", "receiver_index"], keep="first").copy()
        sc_df_indexed = sc_df.set_index(["sender_index", "receiver_index"])[program_cols]

        aligned_scores = (
            sc_df_indexed.reindex(edge_mi)
            .fillna(0.0)
            .to_numpy(dtype=np.float32, copy=False)
        )
        return aligned_scores, program_cols


    def compute_commot_scores(SpiderNet_data_pyg, edge_index_np):
        exp_nor = SpiderNet_data_pyg["x"].to("cpu").detach().numpy()
        gene_names = SpiderNet_data_pyg["genenames"]
        cell_names = SpiderNet_data_pyg["cellnames"]
        spatial_pos = SpiderNet_data_pyg["pos"].to("cpu").detach().numpy()

        adata_commot = sc.AnnData(
            X=exp_nor,
            obs=pd.DataFrame(index=cell_names),
            var=pd.DataFrame(index=gene_names),
        )
        adata_commot.obsm["spatial"] = spatial_pos

        LR = np.array([
            ["L1", "R1", "MI1_pathway"],
            ["L2", "R2", "MI1_pathway"],
            ["L3", "R3", "MI1_pathway"],
            ["L4", "R4", "MI1_pathway"],
            ["L5", "R5", "MI1_pathway"],
            ["L6", "R6", "MI1_pathway"],
            ["L7", "R7", "MI1_pathway"],
            ["L8", "R8", "MI1_pathway"],
            ["L9", "R9", "MI1_pathway"],
            ["L10", "R10", "MI2_pathway"],
            ["L11", "R11", "MI2_pathway"],
            ["L12", "R12", "MI2_pathway"],
            ["L13", "R13", "MI2_pathway"],
            ["L14", "R14", "MI2_pathway"],
            ["L15", "R15", "MI2_pathway"],
            ["L16", "R16", "MI2_pathway"],
            ["L17", "R17", "MI2_pathway"],
            ["L18", "R18", "MI2_pathway"],
            ["L19", "R19", "MI2_pathway"],
            ["L20", "R20", "MI2_pathway"],
        ], dtype=str)
        df_ligrec = pd.DataFrame(LR)

        spatial_coords = np.asarray(adata_commot.obsm["spatial"], dtype=np.float32)
        n = spatial_coords.shape[0]
        k = 10
        if n <= k:
            raise ValueError("Not enough cells to build the COMMOT distance threshold.")

        nn = NearestNeighbors(n_neighbors=k + 1, algorithm="auto", metric="euclidean")
        nn.fit(spatial_coords)
        dists, _ = nn.kneighbors(spatial_coords, return_distance=True)
        dists_k = dists[:, 1:]
        dist_vec = dists_k.mean(axis=1).astype(np.float32)
        dist_median = float(np.median(dist_vec[~np.isnan(dist_vec)]))

        ct.tl.spatial_communication(
            adata_commot,
            database_name="cellchat",
            df_ligrec=df_ligrec,
            dis_thr=dist_median,
            heteromeric=True,
            pathway_sum=True,
            cot_nitermax=2000,
        )

        factor_commot = np.vstack([
            adata_commot.obsp["commot-cellchat-MI1_pathway"].toarray()[edge_index_np[:, 0], edge_index_np[:, 1]],
            adata_commot.obsp["commot-cellchat-MI2_pathway"].toarray()[edge_index_np[:, 0], edge_index_np[:, 1]],
        ]).T
        return _safe_column_max_normalize(factor_commot)


    def get_best_component_scores(factor_matrix, edge_MI1, edge_MI2, mi_index):
        factor_matrix = np.asarray(factor_matrix, dtype=float)
        if factor_matrix.ndim == 1:
            return _safe_column_max_normalize(factor_matrix)

        if mi_index == 0:
            ref_edges = edge_MI1
        else:
            ref_edges = edge_MI2

        best_idx = int(np.argmax(np.mean(factor_matrix[ref_edges, :], axis=0)))
        scores = factor_matrix[:, best_idx]
        return _safe_column_max_normalize(scores)


    def build_truth_weighted_edge_scores(factor_matrix, edgemeta_data, edge_MI1, edge_MI2):
        edge_index_use_pd_order_list = []
        MI_strength_complex_order_list = []
        edge_index_np = SpiderNet_data_pyg["edge_index"].to("cpu").detach().numpy()
        edge_index_use_pd = pd.DataFrame(edge_index_np, columns=["sender", "receiver"])

        for MI_index in range(2):
            MI_strength_truth = np.array(
                (edgemeta_data["MetaItype"] == f"MI-{MI_index + 1}").astype(np.int32)
            )
            factor_method_cur = get_best_component_scores(factor_matrix, edge_MI1, edge_MI2, MI_index)

            MI_strength_complex = ((MI_strength_truth - 0.5) * 2) * factor_method_cur
            MI_strength_complex[MI_strength_truth == 0] = (-1) * np.power(
                np.abs(MI_strength_complex[MI_strength_truth == 0]), 3
            )
            MI_strength_complex[MI_strength_truth == 1] = np.power(
                np.abs(MI_strength_complex[MI_strength_truth == 1]), 3
            )

            edge_index_use_pd_order = edge_index_use_pd.iloc[np.argsort(MI_strength_complex), :]
            MI_strength_complex_order = MI_strength_complex[np.argsort(MI_strength_complex)]
            edge_index_use_pd_order_list.append(edge_index_use_pd_order)
            MI_strength_complex_order_list.append(MI_strength_complex_order)

        edge_index_use_pd_order_merged = pd.concat(edge_index_use_pd_order_list, axis=0)
        MI_strength_complex_order_merged = np.concatenate(MI_strength_complex_order_list, axis=0)

        order = np.argsort(MI_strength_complex_order_merged)
        edge_index_use_pd_order_merged = edge_index_use_pd_order_merged.iloc[order, :]
        MI_strength_complex_order_merged = MI_strength_complex_order_merged[order]
        return edge_index_use_pd_order_merged, MI_strength_complex_order_merged


    def plot_insitu_compare_for_method(method_name, factor_matrix, edgemeta_data, edge_MI1, edge_MI2):
        edge_index_use_pd_order_merged, MI_strength_complex_order_merged = build_truth_weighted_edge_scores(
            factor_matrix=factor_matrix,
            edgemeta_data=edgemeta_data,
            edge_MI1=edge_MI1,
            edge_MI2=edge_MI2,
        )

        cmap = LinearSegmentedColormap.from_list(
            "blue_white_red",
            ["#3D3BF3", "white", "#FF2929"],
            N=256,
        )
        norm = Normalize(vmin=-1, vmax=1)

        set_figure_style()
        plt.close("all")
        fig, ax = plt.subplots(figsize=(6, 5))

        ax.scatter(
            SpiderNet_data["spatial_location"][:, 0],
            SpiderNet_data["spatial_location"][:, 1],
            c="grey",
            s=1,
        )
        ax.set_xlabel("X")
        ax.set_ylabel("Y")

        for edge_index0 in range(edge_index_use_pd_order_merged.shape[0]):
            sender_index = int(edge_index_use_pd_order_merged.iloc[edge_index0, 0])
            receiver_index = int(edge_index_use_pd_order_merged.iloc[edge_index0, 1])
            edge_color = cmap(norm(MI_strength_complex_order_merged[edge_index0]))

            ax.annotate(
                "",
                xy=(
                    SpiderNet_data["spatial_location"][:, 0][receiver_index],
                    SpiderNet_data["spatial_location"][:, 1][receiver_index],
                ),
                xytext=(
                    SpiderNet_data["spatial_location"][:, 0][sender_index],
                    SpiderNet_data["spatial_location"][:, 1][sender_index],
                ),
                arrowprops=dict(
                    arrowstyle="->,head_length=0.06,head_width=0.06",
                    color=edge_color,
                    lw=1.5,
                ),
            )

        ax.set_title("")
        out_path = os.path.join(file_savepath_main, f"Insitu_MIall_compare_{method_name}.pdf")
        save_ai_pdf(fig, out_path, transparent=True)
        plt.close(fig)
        print(f"Saved in situ plot: {out_path}")


    print("Running additional in situ comparison across methods")

    edge_index_np = SpiderNet_data_pyg["edge_index"].to("cpu").detach().numpy()
    Factor_envir_use = Factor_envir.to("cpu").detach().numpy()
    Factor_envir_use = _safe_column_max_normalize(Factor_envir_use)

    edge_MI1 = np.where(edgemeta_data["MetaItype"] == "MI-1")[0]
    edge_MI2 = np.where(edgemeta_data["MetaItype"] == "MI-2")[0]

    baseline_factor_dict = {"SpiderNet": Factor_envir_use}

    print("Computing NMF+LR baseline")
    LR_cur = SpiderNet_data_pyg["cellpair_LRpair_neigh"].to("cpu").detach().numpy()
    nmf_LR = NMF(n_components=dim_envir, init="nndsvda", random_state=0, max_iter=10000)
    factor_nmf_LR = nmf_LR.fit_transform(LR_cur)
    loading_nmf_LR = nmf_LR.components_
    factor_nmf_LR_colmax = np.max(factor_nmf_LR, axis=0)
    factor_nmf_LR_colmax[factor_nmf_LR_colmax <= 0] = 1
    for j in range(factor_nmf_LR.shape[1]):
        factor_nmf_LR[:, j] = factor_nmf_LR[:, j] / factor_nmf_LR_colmax[j]
        loading_nmf_LR[j, :] = loading_nmf_LR[j, :] * factor_nmf_LR_colmax[j]
    baseline_factor_dict["NMF+LR"] = factor_nmf_LR

    # print("Computing NMF_coexp baseline")
    # gene2gene_coexp_cur = compute_coexpression_simple(
    #     edge_index=edge_index_np,
    #     exp_use_sparse=sp.csr_matrix(SpiderNet_data_pyg["x"].to("cpu").detach().numpy()),
    # )
    # nmf_gene2gene_coexp = NMF(n_components=dim_envir, init="nndsvda", random_state=0, max_iter=10000)
    # factor_nmf_gene2gene_coexp = nmf_gene2gene_coexp.fit_transform(gene2gene_coexp_cur)
    # loading_nmf_gene2gene_coexp = nmf_gene2gene_coexp.components_
    # factor_nmf_gene2gene_coexp_colmax = np.max(factor_nmf_gene2gene_coexp, axis=0)
    # factor_nmf_gene2gene_coexp_colmax[factor_nmf_gene2gene_coexp_colmax <= 0] = 1
    # for j in range(factor_nmf_gene2gene_coexp.shape[1]):
    #     factor_nmf_gene2gene_coexp[:, j] = factor_nmf_gene2gene_coexp[:, j] / factor_nmf_gene2gene_coexp_colmax[j]
    #     loading_nmf_gene2gene_coexp[j, :] = (
    #         loading_nmf_gene2gene_coexp[j, :] * factor_nmf_gene2gene_coexp_colmax[j]
    #     )
    # baseline_factor_dict["NMF_coexp"] = factor_nmf_gene2gene_coexp

    print("Computing COMMOT baseline")
    try:
        factor_commot = compute_commot_scores(SpiderNet_data_pyg=SpiderNet_data_pyg, edge_index_np=edge_index_np)
        baseline_factor_dict["COMMOT"] = factor_commot
    except Exception as e:
        print(f"[Warning] COMMOT baseline failed: {e}")

    print("Loading ScCChain baseline")
    try:
        sample_result_root = os.path.join(SCCCHAIN_RESULT_ROOT, Setting_cur, f"Experiment_{experiment_index}")
        sc_csv_path = find_sccchain_csv(sample_result_root)
        factor_scchain, scchain_program_cols = load_sccchain_scores_to_reference_edges(
            sc_csv_path=sc_csv_path,
            edge_index=edge_index_np,
        )
        factor_scchain = _safe_column_max_normalize(factor_scchain)
        baseline_factor_dict["ScCChain"] = factor_scchain
    except Exception as e:
        print(f"[Warning] ScCChain baseline failed: {e}")

    print("Loading Spacia baseline")
    try:
        Setting_cur_export = Setting_cur + "_export"
        sample_result_path = os.path.join(SPACIA_RESULT_ROOT, Setting_cur_export,
                                          f"Experiment_{experiment_index}_compiled_spacia_output.h5ad")
        Spacia_adata = sc.read_h5ad(sample_result_path)

        factor_Spacia_dim1 = np.mean(Spacia_adata.obsp['interaction_scores'][:, :, 0:10], axis=2)
        factor_Spacia_dim2 = np.mean(Spacia_adata.obsp['interaction_scores'][:, :, 10:20], axis=2)
        factor_Spacia_dim1_long = factor_Spacia_dim1[edge_index_np[:, 0], edge_index_np[:, 1]]
        factor_Spacia_dim2_long = factor_Spacia_dim2[edge_index_np[:, 0], edge_index_np[:, 1]]
        factor_Spacia_long = np.vstack([factor_Spacia_dim1_long, factor_Spacia_dim2_long]).T
        factor_Spacia_long = _safe_column_max_normalize(factor_Spacia_long)

        baseline_factor_dict["Spacia"] = factor_Spacia_long
    except Exception as e:
        print(f"[Warning] Spacia baseline failed: {e}")

    # ##Calculate the correlation matrix for Spacia_adata.obsp['interaction_scores'][edge_index_np[:, 0], edge_index_np[:, 1],:]
    # mat_1 = Spacia_adata.obsp['interaction_scores'][edge_index_np[:, 0], edge_index_np[:, 1],:]
    # corr_matrix = np.corrcoef(mat_1.T)
    # ##Show the heatmap of corr_matrix
    # set_figure_style()
    # plt.close("all")
    # fig, ax = plt.subplots(figsize=(6, 5))
    # cax = ax.imshow(corr_matrix, aspect="auto", cmap="viridis")
    # plt.colorbar(cax)
    # plt.title("Correlation matrix of Spacia interaction scores")
    # plt.xlabel("Interaction score dimension")
    # plt.ylabel("Interaction score dimension")
    # out_path = os.path.join(file_savepath_main, f"Spacia_interaction_scores_correlation_matrix.pdf")
    # save_ai_pdf(fig, out_path, transparent=True)
    for method_name, factor_matrix in baseline_factor_dict.items():
        try:
            plot_insitu_compare_for_method(
                method_name=method_name,
                factor_matrix=factor_matrix,
                edgemeta_data=edgemeta_data,
                edge_MI1=edge_MI1,
                edge_MI2=edge_MI2,
            )
        except Exception as e:
            print(f"[Warning] Failed to generate in situ plot for {method_name}: {e}")


# ============================================================
# Export benchmark tables required by Simulation_Benchmark_Pipeline
# ============================================================

def _safe_column_max_normalize_export(arr):
    arr = np.asarray(arr, dtype=float)
    if arr.ndim == 1:
        max_val = np.nanmax(arr) if arr.size > 0 else np.nan
        if (not np.isfinite(max_val)) or max_val <= 0:
            return np.zeros_like(arr, dtype=float)
        out = arr / max_val
        out[~np.isfinite(out)] = 0.0
        return out

    out = arr.copy()
    if out.size == 0:
        return out
    col_max = np.nanmax(out, axis=0)
    col_max[(~np.isfinite(col_max)) | (col_max <= 0)] = 1.0
    out = out / col_max
    out[~np.isfinite(out)] = 0.0
    return out


def _safe_row_normalize_export(arr):
    arr = np.asarray(arr, dtype=float)
    if arr.ndim == 1:
        row_sum = np.nansum(arr)
        if (not np.isfinite(row_sum)) or row_sum <= 0:
            return np.zeros_like(arr, dtype=float)
        out = arr / row_sum
        out[~np.isfinite(out)] = 0.0
        return out

    out = arr.copy()
    if out.size == 0:
        return out
    row_sum = np.nansum(out, axis=1, keepdims=True)
    row_sum[(~np.isfinite(row_sum)) | (row_sum <= 0)] = 1.0
    out = out / row_sum
    out[~np.isfinite(out)] = 0.0
    return out


def _safe_binary_metrics_export(y_true, y_score):
    y_true = np.asarray(y_true, dtype=np.int32)
    y_score = np.asarray(y_score, dtype=float)
    y_score = np.nan_to_num(y_score, nan=0.0, posinf=0.0, neginf=0.0)

    if y_true.size == 0 or np.unique(y_true).shape[0] < 2:
        return np.nan, np.nan

    try:
        auroc = sklearn.metrics.roc_auc_score(y_true, y_score)
    except Exception:
        auroc = np.nan

    try:
        auprc = sklearn.metrics.average_precision_score(y_true, y_score)
    except Exception:
        auprc = np.nan

    return auroc, auprc


def _find_sccchain_csv_export(sample_result_root):
    import glob

    pattern = os.path.join(sample_result_root, "*_ScCChain_edge_program_scores.csv")
    files = sorted(glob.glob(pattern))
    if len(files) == 0:
        raise FileNotFoundError(f"No ScCChain result file found in: {sample_result_root}")
    return files[0]


def _load_sccchain_scores_to_reference_edges_export(sc_csv_path, edge_index):
    sc_df = pd.read_csv(sc_csv_path)
    if sc_df.shape[1] < 3:
        raise ValueError(f"Unexpected ScCChain CSV format: {sc_csv_path}")

    sender_col = sc_df.columns[0]
    receiver_col = sc_df.columns[1]
    program_cols = sc_df.columns.tolist()[2:]

    sc_df = sc_df.rename(columns={
        sender_col: "sender_index",
        receiver_col: "receiver_index",
    }).copy()

    sc_df["sender_index"] = pd.to_numeric(sc_df["sender_index"], errors="coerce").astype("Int64")
    sc_df["receiver_index"] = pd.to_numeric(sc_df["receiver_index"], errors="coerce").astype("Int64")
    sc_df = sc_df.dropna(subset=["sender_index", "receiver_index"]).copy()
    sc_df["sender_index"] = sc_df["sender_index"].astype(np.int64)
    sc_df["receiver_index"] = sc_df["receiver_index"].astype(np.int64)

    # Julia output is 1-based.
    sc_df["sender_index"] -= 1
    sc_df["receiver_index"] -= 1

    edge_index_df = pd.DataFrame(edge_index, columns=["sender_index", "receiver_index"])
    edge_mi = pd.MultiIndex.from_frame(edge_index_df[["sender_index", "receiver_index"]])

    sc_df = sc_df.drop_duplicates(subset=["sender_index", "receiver_index"], keep="first").copy()
    sc_df_indexed = sc_df.set_index(["sender_index", "receiver_index"])[program_cols]

    aligned_scores = (
        sc_df_indexed.reindex(edge_mi)
        .fillna(0.0)
        .to_numpy(dtype=np.float32, copy=False)
    )
    return aligned_scores


def _compute_commot_scores_export(SpiderNet_data_pyg, edge_index_np):
    exp_nor = SpiderNet_data_pyg["x"].to("cpu").detach().numpy()
    gene_names = SpiderNet_data_pyg["genenames"]
    cell_names = SpiderNet_data_pyg["cellnames"]
    spatial_pos = SpiderNet_data_pyg["pos"].to("cpu").detach().numpy()

    adata_commot = sc.AnnData(
        X=exp_nor,
        obs=pd.DataFrame(index=cell_names),
        var=pd.DataFrame(index=gene_names),
    )
    adata_commot.obsm["spatial"] = spatial_pos

    LR = np.array([
        ["L1", "R1", "MI1_pathway"],
        ["L2", "R2", "MI1_pathway"],
        ["L3", "R3", "MI1_pathway"],
        ["L4", "R4", "MI1_pathway"],
        ["L5", "R5", "MI1_pathway"],
        ["L6", "R6", "MI1_pathway"],
        ["L7", "R7", "MI1_pathway"],
        ["L8", "R8", "MI1_pathway"],
        ["L9", "R9", "MI1_pathway"],
        ["L10", "R10", "MI2_pathway"],
        ["L11", "R11", "MI2_pathway"],
        ["L12", "R12", "MI2_pathway"],
        ["L13", "R13", "MI2_pathway"],
        ["L14", "R14", "MI2_pathway"],
        ["L15", "R15", "MI2_pathway"],
        ["L16", "R16", "MI2_pathway"],
        ["L17", "R17", "MI2_pathway"],
        ["L18", "R18", "MI2_pathway"],
        ["L19", "R19", "MI2_pathway"],
        ["L20", "R20", "MI2_pathway"],
    ], dtype=str)
    df_ligrec = pd.DataFrame(LR)

    spatial_coords = np.asarray(adata_commot.obsm["spatial"], dtype=np.float32)
    n = spatial_coords.shape[0]
    k = 10
    if n <= k:
        raise ValueError("Not enough cells to build the COMMOT distance threshold.")

    nn = NearestNeighbors(n_neighbors=k + 1, algorithm="auto", metric="euclidean")
    nn.fit(spatial_coords)
    dists, _ = nn.kneighbors(spatial_coords, return_distance=True)
    dists_k = dists[:, 1:]
    dist_vec = dists_k.mean(axis=1).astype(np.float32)
    dist_median = float(np.median(dist_vec[~np.isnan(dist_vec)]))

    ct.tl.spatial_communication(
        adata_commot,
        database_name="cellchat",
        df_ligrec=df_ligrec,
        dis_thr=dist_median,
        heteromeric=True,
        pathway_sum=True,
        cot_nitermax=2000,
    )

    factor_commot = np.vstack([
        adata_commot.obsp["commot-cellchat-MI1_pathway"].toarray()[edge_index_np[:, 0], edge_index_np[:, 1]],
        adata_commot.obsp["commot-cellchat-MI2_pathway"].toarray()[edge_index_np[:, 0], edge_index_np[:, 1]],
    ]).T
    return _safe_column_max_normalize_export(factor_commot)


def _get_best_component_scores_export(factor_matrix, edge_MI1, edge_MI2, mi_index):
    factor_matrix = np.asarray(factor_matrix, dtype=float)
    if factor_matrix.ndim == 1:
        return _safe_column_max_normalize_export(factor_matrix)

    if factor_matrix.shape[1] == 0:
        return np.zeros(factor_matrix.shape[0], dtype=float)

    ref_edges = edge_MI1 if mi_index == 0 else edge_MI2
    if ref_edges.size == 0:
        best_idx = 0
    else:
        best_idx = int(np.argmax(np.mean(factor_matrix[ref_edges, :], axis=0)))
    scores = factor_matrix[:, best_idx]
    return _safe_column_max_normalize_export(scores)


def _build_baseline_factor_dict_export():
    Factor_envir_use = Factor_envir.to("cpu").detach().numpy()
    Factor_envir_use = _safe_column_max_normalize_export(Factor_envir_use)
    baseline_factor_dict = {"SpiderNet": Factor_envir_use}
    return baseline_factor_dict



def _save_edge_metric_tables_export(file_savepath_main):
    edge_MI1 = np.where(edgemeta_data["MetaItype"] == "MI-1")[0]
    edge_MI2 = np.where(edgemeta_data["MetaItype"] == "MI-2")[0]
    y_true_mi1 = (edgemeta_data["MetaItype"].values == "MI-1").astype(np.int32)
    y_true_mi2 = (edgemeta_data["MetaItype"].values == "MI-2").astype(np.int32)

    baseline_factor_dict = _build_baseline_factor_dict_export()

    roc_rows = []
    prc_rows = []

    for method_name, factor_matrix in baseline_factor_dict.items():
        mi1_scores = _get_best_component_scores_export(factor_matrix, edge_MI1=edge_MI1, edge_MI2=edge_MI2, mi_index=0)
        mi2_scores = _get_best_component_scores_export(factor_matrix, edge_MI1=edge_MI1, edge_MI2=edge_MI2, mi_index=1)

        auroc_mi1, auprc_mi1 = _safe_binary_metrics_export(y_true_mi1, mi1_scores)
        auroc_mi2, auprc_mi2 = _safe_binary_metrics_export(y_true_mi2, mi2_scores)

        roc_rows.append({
            "Method": method_name,
            "MI-1": auroc_mi1,
            "MI-2": auroc_mi2,
        })
        prc_rows.append({
            "Method": method_name,
            "MI-1": auprc_mi1,
            "MI-2": auprc_mi2,
        })

    roc_df = pd.DataFrame(roc_rows)
    prc_df = pd.DataFrame(prc_rows)

    roc_df.to_csv(os.path.join(file_savepath_main, "ROC_AUROC_all.csv"), index=False)
    prc_df.to_csv(os.path.join(file_savepath_main, "PUC_AUPRC_all.csv"), index=False)

    macro_rows = []
    for roc_row, prc_row in zip(roc_rows, prc_rows):
        macro_rows.append({
            "Method": roc_row["Method"],
            "Macro_AUROC": np.nanmean([roc_row["MI-1"], roc_row["MI-2"]]),
            "Macro_AUPRC": np.nanmean([prc_row["MI-1"], prc_row["MI-2"]]),
        })
    pd.DataFrame(macro_rows).to_csv(
        os.path.join(file_savepath_main, "Benchmark_MacroMetrics.csv"),
        index=False,
    )

    print("Saved benchmark ROC/AUPRC tables to:", file_savepath_main)


def _save_loadingrank_summary_export(file_savepath_main):
    loading_lr_raw = loading_LR.to("cpu").detach().numpy()
    loading_sender_raw = loading_sender.to("cpu").detach().numpy()
    loading_receiver_raw = loading_receiver.to("cpu").detach().numpy()

    # Old-style loading-ratio export: use trained loadings, but evaluate them after
    # column normalization so each LR pair / gene distributes unit mass across
    # components, matching the normalization logic used in the legacy loading plots.
    loading_lr_colnorm = _normalize_loading_columns_for_summary(loading_lr_raw)
    loading_sender_colnorm = _normalize_loading_columns_for_summary(loading_sender_raw)
    loading_receiver_colnorm = _normalize_loading_columns_for_summary(loading_receiver_raw)

    component_match = _match_components_by_lr_block(loading_lr_raw)
    mi1_component = component_match["mi1_component"]
    mi2_component = component_match["mi2_component"]

    truth_idx = _build_loading_truth_index_dict(
        n_lr=loading_lr_colnorm.shape[1],
        n_gene=loading_sender_colnorm.shape[1],
    )

    lr_ratio = np.nanmean([
        _rank_ratio_on_block(loading_lr_colnorm, mi1_component, truth_idx["lr_idx_mi1"]),
        _rank_ratio_on_block(loading_lr_colnorm, mi2_component, truth_idx["lr_idx_mi2"]),
    ])
    sender_ratio = np.nanmean([
        _rank_ratio_on_block(loading_sender_colnorm, mi1_component, truth_idx["sender_idx_mi1"]),
        _rank_ratio_on_block(loading_sender_colnorm, mi2_component, truth_idx["sender_idx_mi2"]),
    ])
    receiver_ratio = np.nanmean([
        _rank_ratio_on_block(loading_receiver_colnorm, mi1_component, truth_idx["receiver_idx_mi1"]),
        _rank_ratio_on_block(loading_receiver_colnorm, mi2_component, truth_idx["receiver_idx_mi2"]),
    ])

    loading_summary_df = pd.DataFrame([{
        "Method": "SpiderNet",
        "LR_loading_ratio": lr_ratio,
        "Sender_loading_ratio": sender_ratio,
        "Receiver_loading_ratio": receiver_ratio,
        "MI1_component": mi1_component,
        "MI2_component": mi2_component,
        "Metric_definition": "Trained loading rank ratio using legacy-style column normalization, matched components, and correct-block rank/share scoring",
        "Normalization": "column_normalized_trained_loading",
        "Scoring": "mean(correct_component_share, top1_hit_ratio)_averaged_across_MI1_MI2",
    }])
    loading_summary_df.to_csv(
        os.path.join(file_savepath_main, "LoadingRank_Ratio_Summary.csv"),
        index=False,
    )
    print("Saved loading rank-ratio summary table to:", os.path.join(file_savepath_main, "LoadingRank_Ratio_Summary.csv"))

    # Also keep the previous block-mass style export as a separate file for reference.
    loading_lr_rownorm = _normalize_loading_rows_for_summary(loading_lr_raw)
    loading_sender_rownorm = _normalize_loading_rows_for_summary(loading_sender_raw)
    loading_receiver_rownorm = _normalize_loading_rows_for_summary(loading_receiver_raw)

    def _block_mass(arr, row_idx, col_idx):
        if row_idx is None or arr.shape[0] == 0 or row_idx >= arr.shape[0] or col_idx.size == 0:
            return np.nan
        return float(np.nansum(arr[row_idx, col_idx]))

    blockmass_df = pd.DataFrame([{
        "Method": "SpiderNet",
        "LR_loading_ratio": np.nanmean([
            _block_mass(loading_lr_rownorm, mi1_component, truth_idx["lr_idx_mi1"]),
            _block_mass(loading_lr_rownorm, mi2_component, truth_idx["lr_idx_mi2"]),
        ]),
        "Sender_loading_ratio": np.nanmean([
            _block_mass(loading_sender_rownorm, mi1_component, truth_idx["sender_idx_mi1"]),
            _block_mass(loading_sender_rownorm, mi2_component, truth_idx["sender_idx_mi2"]),
        ]),
        "Receiver_loading_ratio": np.nanmean([
            _block_mass(loading_receiver_rownorm, mi1_component, truth_idx["receiver_idx_mi1"]),
            _block_mass(loading_receiver_rownorm, mi2_component, truth_idx["receiver_idx_mi2"]),
        ]),
        "MI1_component": mi1_component,
        "MI2_component": mi2_component,
        "Metric_definition": "Row-normalized final trained loading mass within matched ground-truth blocks",
    }])
    blockmass_df.to_csv(
        os.path.join(file_savepath_main, "LoadingBlockMass_Ratio_Summary.csv"),
        index=False,
    )
    print("Saved loading block-mass summary table to:", os.path.join(file_savepath_main, "LoadingBlockMass_Ratio_Summary.csv"))


def _save_spidernet_edge_scores_export(file_savepath_main):
    edge_index_np = SpiderNet_data_pyg["edge_index"].to("cpu").detach().numpy()
    edge_MI1 = np.where(edgemeta_data["MetaItype"] == "MI-1")[0]
    edge_MI2 = np.where(edgemeta_data["MetaItype"] == "MI-2")[0]
    factor_use = Factor_envir.to("cpu").detach().numpy()
    factor_use = _safe_column_max_normalize_export(factor_use)
    mi1_scores = _get_best_component_scores_export(factor_use, edge_MI1=edge_MI1, edge_MI2=edge_MI2, mi_index=0)
    mi2_scores = _get_best_component_scores_export(factor_use, edge_MI1=edge_MI1, edge_MI2=edge_MI2, mi_index=1)
    edge_scores_df = pd.DataFrame({
        "sender_index": edge_index_np[:, 0],
        "receiver_index": edge_index_np[:, 1],
        "MI-1": mi1_scores,
        "MI-2": mi2_scores,
    })
    edge_scores_df.to_csv(os.path.join(file_savepath_main, "EdgeProgramScores.csv"), index=False)
    print("Saved SpiderNet edge scores to:", os.path.join(file_savepath_main, "EdgeProgramScores.csv"))


try:
    _save_edge_metric_tables_export(file_savepath_main=file_savepath_main)
    _save_loadingrank_summary_export(file_savepath_main=file_savepath_main)
    _save_spidernet_edge_scores_export(file_savepath_main=file_savepath_main)
except Exception as e:
    print(f"[Warning] Failed to export benchmark summary tables: {e}")
