#!/usr/bin/env python3
"""
Run the SpiderNet simulation benchmark for one setting and one experiment replicate.

This script loads one simulated dataset generated by SimulationData_generation,
trains SpiderNet on that replicate, saves the SpiderNet outputs, and exports benchmark metrics and molecular loading plots.
Use the in-situ notebook for method comparisons.

Command-line arguments:
    --setting     Integer index into the six benchmark settings
    --experiment  Integer replicate index

Directory conventions:
    Input data:
        D:/SpiderNet/Data/Simulation/<setting>/Experiment_<idx>/
    SpiderNet outputs:
        D:/SpiderNet/Results/Simulation/SpiderNet/<setting>/Experiment_<idx>/
    Published plots and tables:
        run_benchmarks.py --stage train also publishes them under output/SpiderNet/.
"""

import os
import argparse
import json
import pickle
from pathlib import Path
from simulation_sample_plots import (
    plot_trained_loadings,
    _normalize_loading_rows_for_summary,
    _normalize_loading_columns_for_summary,
    _build_loading_truth_index_dict,
    _rank_ratio_on_block,
    _match_components_by_lr_block,
)

import numpy as np
import pandas as pd
import scanpy as sc
import sklearn.metrics
import torch

from sklearn.neighbors import NearestNeighbors
from torch_geometric.data import Data


# Use the same model/training API as HGSOC_modeltraining.
# The simulation script only prepares a one-batch processed bundle; model
# construction, initialization, training, inference and export are delegated
# to the SpiderNet package API.
try:
    from SpiderNet.api import (
        build_model,
        run_training,
        infer_meta_interactions,
        normalize_outputs,
        export_results,
    )
    from SpiderNet.config import TrainingConfig
    from SpiderNet.io import load_processed_data
except ImportError as exc:
    raise ImportError(
        "Could not import the SpiderNet package API. Please run this script "
        "inside the same environment used by HGSOC_modeltraining, where "
        "SpiderNet.api, SpiderNet.config and SpiderNet.io are available."
    ) from exc

cuda_available = torch.cuda.is_available()
if cuda_available:
    num_gpus = torch.cuda.device_count()
    print(f"Number of GPUs available: {num_gpus}")
    for i in range(num_gpus):
        print(f"GPU {i}: {torch.cuda.get_device_name(i)}")
    device = "cuda"
else:
    print("No GPU available, using CPU instead.")
    device = "cpu"


def spatial_neighborindex_generation(cell_spatial, num_neighbor_available):
    spatialnn_use = NearestNeighbors(n_neighbors=num_neighbor_available + 1, algorithm="auto")
    spatialnn_use.fit(cell_spatial)
    spatialdist, spatial_neighborindex = spatialnn_use.kneighbors(cell_spatial)

    for i in range(spatial_neighborindex.shape[0]):
        if spatial_neighborindex[i, 0] != i:
            spatial_neighborindex[i, :] = np.hstack((i, np.setdiff1d(spatial_neighborindex[i, :], i)))

    spatial_neighborindex_further = spatial_neighborindex[:, 1:]
    centralindex = spatial_neighborindex[:, 0]
    edge_index = np.vstack(
        (
            np.repeat(centralindex, spatial_neighborindex_further.shape[1]),
            spatial_neighborindex_further.flatten(),
        )
    )
    return spatial_neighborindex, edge_index.T


def count_parameters(model):
    trainable_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
    non_trainable_params = sum(p.numel() for p in model.parameters() if not p.requires_grad)
    return trainable_params, non_trainable_params


## Model-related code is intentionally not defined in this script.
## Consistent with HGSOC_modeltraining, we use the package API from
## SpiderNet.api instead of local Initial_model / SpiderNet_V1 / model.fit code.


def _write_pickle(obj, path):
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "wb") as handle:
        pickle.dump(obj, handle)


def _safe_to_cpu_data(data):
    """Return a CPU copy of a PyG Data object for portable processed-bundle IO."""
    try:
        return data.clone().cpu()
    except Exception:
        return data.to("cpu")


def _make_simulation_adata(exp_nor_pd, spatial_location, cellmeta_data, setting_name, experiment_index):
    """Build an AnnData object matching the fields expected by SpiderNet IO/API."""
    adata = sc.AnnData(X=exp_nor_pd.values.astype(np.float32))
    adata.obs_names = exp_nor_pd.index.astype(str)
    adata.var_names = exp_nor_pd.columns.astype(str)
    adata.obsm["spatial"] = np.asarray(spatial_location.values, dtype=np.float32)

    if "Celltype" not in cellmeta_data.columns:
        raise KeyError("cellmeta_data must contain a 'Celltype' column for simulation training.")

    if pd.Index(exp_nor_pd.index).isin(cellmeta_data.index).all():
        celltype = cellmeta_data.loc[exp_nor_pd.index, "Celltype"].astype(str).values
    else:
        # Fall back to row order, matching the original simulation script.
        celltype = cellmeta_data["Celltype"].astype(str).values
        if celltype.shape[0] != exp_nor_pd.shape[0]:
            raise ValueError(
                "cellmeta_data does not align with gene_exp.csv by index or row order."
            )

    adata.obs["Celltype"] = celltype
    adata.obs["cell_type"] = celltype
    adata.obs["cell.type"] = celltype
    adata.obs["cell_class"] = celltype
    adata.obs["sample_name"] = f"{setting_name}_Experiment_{experiment_index}"
    adata.obs["batch"] = f"{setting_name}_Experiment_{experiment_index}"
    adata.obs["xcoord"] = adata.obsm["spatial"][:, 0]
    adata.obs["ycoord"] = adata.obsm["spatial"][:, 1]
    return adata


def _prepare_simulation_processed_bundle(
    processed_data_dir,
    SpiderNet_data_pyg,
    exp_nor_pd,
    spatial_location,
    cellmeta_data,
    LR_list,
    Setting_cur,
    experiment_index,
):
    """Save a one-batch processed bundle compatible with HGSOC_modeltraining."""
    processed_data_dir = Path(processed_data_dir)
    processed_data_dir.mkdir(parents=True, exist_ok=True)

    sample_name = f"{Setting_cur}_Experiment_{experiment_index}"
    adata = _make_simulation_adata(
        exp_nor_pd=exp_nor_pd,
        spatial_location=spatial_location,
        cellmeta_data=cellmeta_data,
        setting_name=Setting_cur,
        experiment_index=experiment_index,
    )

    spidernet_data_cpu = _safe_to_cpu_data(SpiderNet_data_pyg)
    lr_array = np.asarray(LR_list).astype(str)
    genenames_train = np.asarray(exp_nor_pd.columns).astype(str)
    cellclass_unique = np.sort(cellmeta_data["Celltype"].astype(str).unique())
    batch_cell = np.zeros(adata.n_obs, dtype=np.int64)
    batch_cell_unique = np.asarray([sample_name])

    _write_pickle([spidernet_data_cpu], processed_data_dir / "SpiderNet_data_pyg_list.pkl")
    _write_pickle(lr_array, processed_data_dir / "LR_list.pkl")

    # The HGSOC bundle includes these database-derived LR metadata files.
    # The simulation LR list is synthetic, so we provide minimal compatible
    # placeholders that preserve the same file contract.
    _write_pickle(lr_array, processed_data_dir / "LR_list_cellchatdb.pkl")
    lr_meta = pd.DataFrame({
        "ligand": lr_array[:, 0] if lr_array.size else [],
        "receptor": lr_array[:, 1] if lr_array.size else [],
        "pathway_name": ["Simulation"] * lr_array.shape[0],
    })
    _write_pickle(lr_meta, processed_data_dir / "LR_meta_cellchatdb.pkl")

    _write_pickle(batch_cell_unique, processed_data_dir / "batch_cell_unique.pkl")
    _write_pickle(batch_cell, processed_data_dir / "batch_cell.pkl")
    _write_pickle(genenames_train, processed_data_dir / "genenames_train.pkl")
    _write_pickle([adata], processed_data_dir / "adata_list.pkl")
    _write_pickle(cellclass_unique, processed_data_dir / "cellclass_unique.pkl")
    adata.write_h5ad(processed_data_dir / "adata_all.h5ad")

    metadata_sample = pd.DataFrame({
        "sample_name": [sample_name],
        "setting": [Setting_cur],
        "experiment": [experiment_index],
        "n_cells": [adata.n_obs],
        "n_genes": [adata.n_vars],
        "n_lr_pairs": [lr_array.shape[0]],
    })
    metadata_sample.to_csv(processed_data_dir / "metadata_sample.csv", index=False)

    bundle_summary = {
        "dataset": "Simulation",
        "setting": Setting_cur,
        "experiment": int(experiment_index),
        "n_batches": 1,
        "n_cells": int(adata.n_obs),
        "n_genes": int(adata.n_vars),
        "n_lr_pairs": int(lr_array.shape[0]),
    }
    with open(processed_data_dir / "bundle_summary.json", "w", encoding="utf-8") as handle:
        json.dump(bundle_summary, handle, indent=2)

    return processed_data_dir


def _make_training_config_for_simulation():
    """Create a TrainingConfig and keep simulation hyperparameters if supported."""
    train_cfg = TrainingConfig(
        dim_envir=dim_envir,
        n_jobs=n_jobs,
        max_epoch=max_epoch,
        version=VERSION,
    )

    # Newer SpiderNet.config versions expose these as dataclass fields; older
    # versions may keep them as defaults inside build_model/run_training. Set
    # only fields that exist so this script remains compatible across versions.
    optional_cfg_values = {
        "factor_mode": Factor_mode,
        "Factor_mode": Factor_mode,
        "hidden_channels": hidden_channels,
        "lr": lr,
        "weight_decay": weight_decay,
        "loss_fn": loss_fn,
        "warmup": warmup,
        "LR_loss_weight": LR_loss_weight,
        "threshold_crosscorr": threshold_crosscorr,
        "initial_regression": Initial_regression,
        "Initial_regression": Initial_regression,
        "agg_type": "mean",
        "act_factor": "sigmoid",
    }
    if Factor_mode == "NMF":
        optional_cfg_values["dim_intri"] = dim_intri

    for key, value in optional_cfg_values.items():
        if hasattr(train_cfg, key):
            setattr(train_cfg, key, value)
    return train_cfg


def _get_processed_spidernet_data_list(processed):
    if hasattr(processed, "spidernet_data"):
        return processed.spidernet_data
    if hasattr(processed, "spidernet_data_pyg_list"):
        return processed.spidernet_data_pyg_list
    if hasattr(processed, "SpiderNet_data_pyg_list"):
        return processed.SpiderNet_data_pyg_list
    raise AttributeError("The processed object does not contain a SpiderNet_data_pyg list.")


def _result_array(results, aliases, required=True):
    for key in aliases:
        if key in results:
            value = results[key]
            if torch.is_tensor(value):
                return value.detach().cpu().numpy()
            return np.asarray(value)
    if required:
        raise KeyError(f"None of the result keys were found: {aliases}")
    return None


def _model_parameter_array(model, aliases, required=False):
    if not hasattr(model, "named_parameters"):
        if required:
            raise AttributeError("Model has no named_parameters method.")
        return None

    for name, param in model.named_parameters():
        for alias in aliases:
            if name == alias or name.endswith(alias) or alias in name:
                arr = param.detach().cpu().numpy()
                # Loading parameters are constrained as non-negative in SpiderNet.
                return np.maximum(arr, 0)

    if required:
        raise KeyError(f"None of the model parameter aliases were found: {aliases}")
    return None


def _result_or_model_array(results, model, result_aliases, model_aliases, required=True):
    arr = _result_array(results, result_aliases, required=False)
    if arr is not None:
        return arr
    arr = _model_parameter_array(model, model_aliases, required=False)
    if arr is not None:
        return arr
    if required:
        raise KeyError(
            "Could not locate output in normalized inference results or model parameters. "
            f"Result aliases: {result_aliases}; model aliases: {model_aliases}"
        )
    return None


def _as_device_tensor(arr):
    return torch.as_tensor(np.asarray(arr), dtype=torch.float32, device=device)


def _write_training_provenance(run_dir, processed_data_dir, train_cfg):
    provenance = {
        "processed_data_dir": str(processed_data_dir),
        "run_dir": str(run_dir),
        "model_dir": str(Path(run_dir) / "Model"),
        "dataset": "Simulation",
        "setting": Setting_cur,
        "experiment": int(experiment_index),
        "dim_envir": dim_envir,
        "factor_mode": Factor_mode,
        "n_jobs": n_jobs,
        "max_epoch": max_epoch,
        "version": VERSION,
        "model_training_source": "SpiderNet.api pipeline used by HGSOC_modeltraining",
    }
    if hasattr(train_cfg, "to_dict"):
        provenance["train_cfg"] = train_cfg.to_dict()

    with open(Path(run_dir) / "SpiderNet_training_provenance.json", "w", encoding="utf-8") as handle:
        json.dump(provenance, handle, indent=2)


num_neigh = 10
Factor_mode = "cell_class"
if Factor_mode == "NMF":
    dim_intri = 25

dim_envir = 2
hidden_channels = 128
lr = 5e-4
weight_decay = 1e-5
loss_fn = "mse"
warmup = 1000
max_epoch = 30000
LR_loss_weight = 1
if_addselfloop = False
threshold_crosscorr = 0.1
numtop = 300
num_celltypes = 3
n_jobs = 5
Initial_regression = "Linear"
If_simple = True

SETTING_LIST = ["Dropout1", "Dropout2", "Dropout3", "Sd_use1", "Sd_use2", "Sd_use3"]
DATA_ROOT = os.environ.get("SIMULATION_DATA_ROOT", "D:/SpiderNet/Data/Simulation")
RESULT_ROOT = os.environ.get("SIMULATION_RESULT_ROOT", "D:/SpiderNet/Results/Simulation")
SPIDERNET_RESULT_ROOT = os.path.join(RESULT_ROOT, "SpiderNet")
SCCCHAIN_RESULT_ROOT = os.path.join(RESULT_ROOT, "ScCChain")
SPACIA_RESULT_ROOT = os.path.join(RESULT_ROOT, "Spacia")

parser = argparse.ArgumentParser(description="Experiment arguments")
parser.add_argument("--setting", type=int, default=0, help="Setting index")
parser.add_argument("--experiment", type=int, default=0, help="Experiment index")
args = parser.parse_args()

Setting_cur = SETTING_LIST[args.setting]
experiment_index = args.experiment

print("Setting:", Setting_cur, "Experiment index:", experiment_index)

data_path_main_cur = os.path.join(DATA_ROOT, Setting_cur, f"Experiment_{experiment_index}") + "/"
save_path_main_cur = os.path.join(SPIDERNET_RESULT_ROOT, Setting_cur, f"Experiment_{experiment_index}") + "/"
os.makedirs(save_path_main_cur, exist_ok=True)

cellmeta_data_dir = os.path.join(data_path_main_cur, "cell_metadf.csv")
genemeta_data_dir = os.path.join(data_path_main_cur, "gene_metadf.csv")
edgemeta_data_dir = os.path.join(data_path_main_cur, "edge_metadf.csv")
cell_neigh_metaIprop_dir = os.path.join(data_path_main_cur, "cell_neigh_metaIprop.csv")
location_data_dir = os.path.join(data_path_main_cur, "spatial_location.csv")

file_savepath_main = os.path.join(save_path_main_cur, f"SpiderNet_Result_Mode_{Factor_mode}") + "/"
file_savepath_MI_main = os.path.join(file_savepath_main, "MetaInteraction") + "/"
file_savepath_model_main = os.path.join(file_savepath_main, "Model") + "/"
file_savepath_log_main = os.path.join(file_savepath_main, "log") + "/"

os.makedirs(file_savepath_main, exist_ok=True)
os.makedirs(file_savepath_MI_main, exist_ok=True)
os.makedirs(file_savepath_model_main, exist_ok=True)
os.makedirs(file_savepath_log_main, exist_ok=True)

print("Step 1: load data and prepare inputs")
exp_nor_pd = pd.read_csv(os.path.join(data_path_main_cur, "gene_exp.csv"), index_col=0)
cellmeta_data = pd.read_csv(cellmeta_data_dir, index_col=0)
genemeta_data = pd.read_csv(genemeta_data_dir, index_col=0)
edgemeta_data = pd.read_csv(edgemeta_data_dir, index_col=0)
cell_neigh_metaIprop = pd.read_csv(cell_neigh_metaIprop_dir, index_col=0)
spatial_location = pd.read_csv(location_data_dir, index_col=0)

Ligand_output = list(genemeta_data.index[np.where(genemeta_data["Gene_type"] == "Ligand")[0]])
Receptor_output = list(genemeta_data.index[np.where(genemeta_data["Gene_type"] == "Receptor")[0]])
LR_list = np.vstack((Ligand_output, Receptor_output)).T

SpiderNet_data = {}
SpiderNet_data["num_cells"] = exp_nor_pd.shape[0]
SpiderNet_data["cellnames"] = np.array(list(exp_nor_pd.index))
SpiderNet_data["num_genes"] = exp_nor_pd.shape[1]
SpiderNet_data["genenames"] = np.array(list(exp_nor_pd.columns))
SpiderNet_data["spatial_location"] = spatial_location.values
SpiderNet_data["expression_normalized"] = exp_nor_pd.values
SpiderNet_data["cell_class"] = cellmeta_data["Celltype"]

spatial_neighborindex_use, edge_index = spatial_neighborindex_generation(
    cell_spatial=SpiderNet_data["spatial_location"],
    num_neighbor_available=num_neigh,
)
del spatial_neighborindex_use

if if_addselfloop:
    edge_index = np.vstack(
        (
            edge_index,
            np.vstack(
                (
                    np.arange(0, SpiderNet_data["num_cells"]),
                    np.arange(0, SpiderNet_data["num_cells"]),
                )
            ).T,
        )
    )

edge_index = torch.tensor(edge_index, dtype=torch.long).to(device)
print("The number of edges:", edge_index.shape[0])

adj_matrix = torch.sparse_coo_tensor(
    torch.tensor(edge_index).T.to(device),
    torch.ones(edge_index.shape[0]).to(device),
    torch.Size([SpiderNet_data["num_cells"], SpiderNet_data["num_cells"]]),
).to(device)
torch.cuda.empty_cache()

cellclass = SpiderNet_data["cell_class"].astype("category")
cellclass_unique = np.sort(np.array(cellclass.unique()))
cellclass_onehot = np.zeros((SpiderNet_data["num_cells"], cellclass_unique.shape[0]))
for i in range(cellclass_unique.shape[0]):
    cellclass_onehot[cellclass == cellclass_unique[i], i] = 1

cellclass_onehot_pd = pd.DataFrame(cellclass_onehot, columns=cellclass_unique)
cellclass_onehot_pd.index = SpiderNet_data["cellnames"]

SpiderNet_data_pyg = Data(
    x=torch.tensor(SpiderNet_data["expression_normalized"], dtype=torch.float),
    edge_index=edge_index,
    adj_matrix_sparse=adj_matrix,
    pos=torch.tensor(SpiderNet_data["spatial_location"], dtype=torch.float),
    cell_class_onehot=torch.tensor(cellclass_onehot, dtype=torch.float),
    cell_class_unique=np.array(cellclass_onehot_pd.columns).tolist(),
    cellnames=np.array(SpiderNet_data["cellnames"]),
    genenames=np.array(SpiderNet_data["genenames"]),
    num_cells=SpiderNet_data["num_cells"],
    num_genes=SpiderNet_data["num_genes"],
)

del adj_matrix, cellclass_onehot, cellclass_onehot_pd, edge_index

edge_index1 = SpiderNet_data_pyg.edge_index.to("cpu")
cellpair_LRpair_neigh = np.zeros((edge_index1.shape[0], LR_list.shape[0]))

for LRpair_index in range(LR_list.shape[0]):
    ligand_index_cur = np.where(SpiderNet_data["genenames"] == LR_list[LRpair_index, 0])[0][0]
    receptor_index_cur = np.where(SpiderNet_data["genenames"] == LR_list[LRpair_index, 1])[0][0]
    exp_ligand = np.array(SpiderNet_data["expression_normalized"][:, ligand_index_cur])
    exp_receptor = np.array(SpiderNet_data["expression_normalized"][:, receptor_index_cur])

    cellpair_LRpair_neigh[:, LRpair_index] = np.power(
        exp_ligand[edge_index1[:, 0]] * exp_receptor[edge_index1[:, 1]],
        0.5,
    )

SpiderNet_data_pyg["edge_index"] = torch.tensor(edge_index1, dtype=torch.long)
SpiderNet_data_pyg["cellpair_LRpair_neigh"] = torch.tensor(cellpair_LRpair_neigh)
del edge_index1, cellpair_LRpair_neigh

SpiderNet_data_pyg = SpiderNet_data_pyg.to(device)

exp_nor = SpiderNet_data["expression_normalized"]
exp_nor_T = exp_nor.T
del exp_nor
genenames = SpiderNet_data["genenames"]
cellnames = SpiderNet_data["cellnames"]
cellmetadata = pd.DataFrame(
    {
        "Cell_ID": cellnames,
        "Cluster_ID": SpiderNet_data["cell_class"],
    }
)

# Prepare a one-batch processed bundle and run the same model API used by HGSOC_modeltraining.
VERSION = "V1"
processed_data_dir = Path(save_path_main_cur) / "ProcessedData"
processed_data_dir = _prepare_simulation_processed_bundle(
    processed_data_dir=processed_data_dir,
    SpiderNet_data_pyg=SpiderNet_data_pyg,
    exp_nor_pd=exp_nor_pd,
    spatial_location=spatial_location,
    cellmeta_data=cellmeta_data,
    LR_list=LR_list,
    Setting_cur=Setting_cur,
    experiment_index=experiment_index,
)

processed = load_processed_data(processed_data_dir)
print("Processed directory:", processed_data_dir)
print("Number of batches:", len(_get_processed_spidernet_data_list(processed)))
if hasattr(processed, "lr_list"):
    print("Number of LR pairs:", len(processed.lr_list))
if hasattr(processed, "genenames_train"):
    print("Number of training genes:", processed.genenames_train.shape[0])

train_cfg = _make_training_config_for_simulation()
print("Training config:", train_cfg)

model = build_model(
    processed=processed,
    train_cfg=train_cfg,
    device=device,
)

print(model)
for name, param in model.named_parameters():
    print(name, param.size(), "Trainable:", param.requires_grad)

trainable, non_trainable = count_parameters(model)
print("Total trainable parameters:", trainable)
print("Total non-trainable parameters:", non_trainable)

model = run_training(
    model=model,
    processed=processed,
    train_cfg=train_cfg,
    model_dir=Path(file_savepath_model_main),
    device=device,
)

results_raw = infer_meta_interactions(model=model, processed=processed)
results = normalize_outputs(results_raw)

export_results(
    results=results,
    processed=processed,
    precessed_data_dir=processed_data_dir,
    output_dir=Path(file_savepath_main),
)

with open(Path(file_savepath_model_main) / "SpiderNet_model_config.json", "w", encoding="utf-8") as handle:
    if hasattr(train_cfg, "to_dict"):
        json.dump(train_cfg.to_dict(), handle, indent=2)
    else:
        json.dump(vars(train_cfg), handle, indent=2, default=str)
_write_training_provenance(file_savepath_main, processed_data_dir, train_cfg)
print(f"Results saved to: {file_savepath_main}")

# Keep old downstream plotting/benchmark code working by exposing the same tensor names.
Factor_envir = _as_device_tensor(
    _result_or_model_array(
        results,
        model,
        result_aliases=["factor_envir", "Factor_envir", "Factor_envir_use"],
        model_aliases=[],
    )
)
loading_LR = _as_device_tensor(
    _result_or_model_array(
        results,
        model,
        result_aliases=["loading_lr", "loading_LR", "Loading_LR", "loading_LR_use"],
        model_aliases=["loading_LR_ori", "loading_lr_ori"],
    )
)
loading_receiver = _as_device_tensor(
    _result_or_model_array(
        results,
        model,
        result_aliases=["loading_receiver", "Loading_receiver", "loading_receiver_use"],
        model_aliases=["loading_receiver_ori"],
    )
)
loading_sender = _as_device_tensor(
    _result_or_model_array(
        results,
        model,
        result_aliases=["loading_sender", "Loading_sender", "loading_sender_use"],
        model_aliases=["loading_sender_ori"],
    )
)
Loading_intrinsic = _as_device_tensor(
    _result_or_model_array(
        results,
        model,
        result_aliases=["loading_intrinsic", "Loading_intrinsic", "loading_intrinsic_use"],
        model_aliases=["Loading_intrinsic_ori", "loading_intrinsic_ori"],
    )
)

SpiderNet_data_pyg = _get_processed_spidernet_data_list(processed)[0].to(device)
print("Available normalized result keys:", list(results.keys()))


plot_trained_loadings(Loading_intrinsic, loading_LR, loading_sender, loading_receiver,
                      SpiderNet_data_pyg, file_savepath_main)

# ============================================================
# Export benchmark tables required by Simulation_Benchmark_Pipeline
# ============================================================

def _safe_column_max_normalize_export(arr):
    arr = np.asarray(arr, dtype=float)
    if arr.ndim == 1:
        max_val = np.nanmax(arr) if arr.size > 0 else np.nan
        if (not np.isfinite(max_val)) or max_val <= 0:
            return np.zeros_like(arr, dtype=float)
        out = arr / max_val
        out[~np.isfinite(out)] = 0.0
        return out

    out = arr.copy()
    if out.size == 0:
        return out
    col_max = np.nanmax(out, axis=0)
    col_max[(~np.isfinite(col_max)) | (col_max <= 0)] = 1.0
    out = out / col_max
    out[~np.isfinite(out)] = 0.0
    return out


def _safe_binary_metrics_export(y_true, y_score):
    y_true = np.asarray(y_true, dtype=np.int32)
    y_score = np.asarray(y_score, dtype=float)
    y_score = np.nan_to_num(y_score, nan=0.0, posinf=0.0, neginf=0.0)

    if y_true.size == 0 or np.unique(y_true).shape[0] < 2:
        return np.nan, np.nan

    try:
        auroc = sklearn.metrics.roc_auc_score(y_true, y_score)
    except Exception:
        auroc = np.nan

    try:
        auprc = sklearn.metrics.average_precision_score(y_true, y_score)
    except Exception:
        auprc = np.nan

    return auroc, auprc


def _get_best_component_scores_export(factor_matrix, edge_MI1, edge_MI2, mi_index):
    factor_matrix = np.asarray(factor_matrix, dtype=float)
    if factor_matrix.ndim == 1:
        return _safe_column_max_normalize_export(factor_matrix)

    if factor_matrix.shape[1] == 0:
        return np.zeros(factor_matrix.shape[0], dtype=float)

    ref_edges = edge_MI1 if mi_index == 0 else edge_MI2
    if ref_edges.size == 0:
        best_idx = 0
    else:
        best_idx = int(np.argmax(np.mean(factor_matrix[ref_edges, :], axis=0)))
    scores = factor_matrix[:, best_idx]
    return _safe_column_max_normalize_export(scores)


def _build_baseline_factor_dict_export():
    Factor_envir_use = Factor_envir.to("cpu").detach().numpy()
    Factor_envir_use = _safe_column_max_normalize_export(Factor_envir_use)
    baseline_factor_dict = {"SpiderNet": Factor_envir_use}
    return baseline_factor_dict


def _save_edge_metric_tables_export(file_savepath_main):
    edge_MI1 = np.where(edgemeta_data["MetaItype"] == "MI-1")[0]
    edge_MI2 = np.where(edgemeta_data["MetaItype"] == "MI-2")[0]
    y_true_mi1 = (edgemeta_data["MetaItype"].values == "MI-1").astype(np.int32)
    y_true_mi2 = (edgemeta_data["MetaItype"].values == "MI-2").astype(np.int32)

    baseline_factor_dict = _build_baseline_factor_dict_export()

    roc_rows = []
    prc_rows = []

    for method_name, factor_matrix in baseline_factor_dict.items():
        mi1_scores = _get_best_component_scores_export(factor_matrix, edge_MI1=edge_MI1, edge_MI2=edge_MI2, mi_index=0)
        mi2_scores = _get_best_component_scores_export(factor_matrix, edge_MI1=edge_MI1, edge_MI2=edge_MI2, mi_index=1)

        auroc_mi1, auprc_mi1 = _safe_binary_metrics_export(y_true_mi1, mi1_scores)
        auroc_mi2, auprc_mi2 = _safe_binary_metrics_export(y_true_mi2, mi2_scores)

        roc_rows.append({
            "Method": method_name,
            "MI-1": auroc_mi1,
            "MI-2": auroc_mi2,
        })
        prc_rows.append({
            "Method": method_name,
            "MI-1": auprc_mi1,
            "MI-2": auprc_mi2,
        })

    roc_df = pd.DataFrame(roc_rows)
    prc_df = pd.DataFrame(prc_rows)

    roc_df.to_csv(os.path.join(file_savepath_main, "ROC_AUROC_all.csv"), index=False)
    prc_df.to_csv(os.path.join(file_savepath_main, "PUC_AUPRC_all.csv"), index=False)

    macro_rows = []
    for roc_row, prc_row in zip(roc_rows, prc_rows):
        macro_rows.append({
            "Method": roc_row["Method"],
            "Macro_AUROC": np.nanmean([roc_row["MI-1"], roc_row["MI-2"]]),
            "Macro_AUPRC": np.nanmean([prc_row["MI-1"], prc_row["MI-2"]]),
        })
    pd.DataFrame(macro_rows).to_csv(
        os.path.join(file_savepath_main, "Benchmark_MacroMetrics.csv"),
        index=False,
    )

    print("Saved benchmark ROC/AUPRC tables to:", file_savepath_main)


def _save_loadingrank_summary_export(file_savepath_main):
    loading_lr_raw = loading_LR.to("cpu").detach().numpy()
    loading_sender_raw = loading_sender.to("cpu").detach().numpy()
    loading_receiver_raw = loading_receiver.to("cpu").detach().numpy()

    # Old-style loading-ratio export: use trained loadings, but evaluate them after
    # column normalization so each LR pair / gene distributes unit mass across
    # components, matching the normalization logic used in the legacy loading plots.
    loading_lr_colnorm = _normalize_loading_columns_for_summary(loading_lr_raw)
    loading_sender_colnorm = _normalize_loading_columns_for_summary(loading_sender_raw)
    loading_receiver_colnorm = _normalize_loading_columns_for_summary(loading_receiver_raw)

    component_match = _match_components_by_lr_block(loading_lr_raw)
    mi1_component = component_match["mi1_component"]
    mi2_component = component_match["mi2_component"]

    truth_idx = _build_loading_truth_index_dict(
        n_lr=loading_lr_colnorm.shape[1],
        n_gene=loading_sender_colnorm.shape[1],
    )

    lr_ratio = np.nanmean([
        _rank_ratio_on_block(loading_lr_colnorm, mi1_component, truth_idx["lr_idx_mi1"]),
        _rank_ratio_on_block(loading_lr_colnorm, mi2_component, truth_idx["lr_idx_mi2"]),
    ])
    sender_ratio = np.nanmean([
        _rank_ratio_on_block(loading_sender_colnorm, mi1_component, truth_idx["sender_idx_mi1"]),
        _rank_ratio_on_block(loading_sender_colnorm, mi2_component, truth_idx["sender_idx_mi2"]),
    ])
    receiver_ratio = np.nanmean([
        _rank_ratio_on_block(loading_receiver_colnorm, mi1_component, truth_idx["receiver_idx_mi1"]),
        _rank_ratio_on_block(loading_receiver_colnorm, mi2_component, truth_idx["receiver_idx_mi2"]),
    ])

    loading_summary_df = pd.DataFrame([{
        "Method": "SpiderNet",
        "LR_loading_ratio": lr_ratio,
        "Sender_loading_ratio": sender_ratio,
        "Receiver_loading_ratio": receiver_ratio,
        "MI1_component": mi1_component,
        "MI2_component": mi2_component,
        "Metric_definition": "Trained loading rank ratio using legacy-style column normalization, matched components, and correct-block rank/share scoring",
        "Normalization": "column_normalized_trained_loading",
        "Scoring": "mean(correct_component_share, top1_hit_ratio)_averaged_across_MI1_MI2",
    }])
    loading_summary_df.to_csv(
        os.path.join(file_savepath_main, "LoadingRank_Ratio_Summary.csv"),
        index=False,
    )
    print("Saved loading rank-ratio summary table to:", os.path.join(file_savepath_main, "LoadingRank_Ratio_Summary.csv"))

    # Also keep the previous block-mass style export as a separate file for reference.
    loading_lr_rownorm = _normalize_loading_rows_for_summary(loading_lr_raw)
    loading_sender_rownorm = _normalize_loading_rows_for_summary(loading_sender_raw)
    loading_receiver_rownorm = _normalize_loading_rows_for_summary(loading_receiver_raw)

    def _block_mass(arr, row_idx, col_idx):
        if row_idx is None or arr.shape[0] == 0 or row_idx >= arr.shape[0] or col_idx.size == 0:
            return np.nan
        return float(np.nansum(arr[row_idx, col_idx]))

    blockmass_df = pd.DataFrame([{
        "Method": "SpiderNet",
        "LR_loading_ratio": np.nanmean([
            _block_mass(loading_lr_rownorm, mi1_component, truth_idx["lr_idx_mi1"]),
            _block_mass(loading_lr_rownorm, mi2_component, truth_idx["lr_idx_mi2"]),
        ]),
        "Sender_loading_ratio": np.nanmean([
            _block_mass(loading_sender_rownorm, mi1_component, truth_idx["sender_idx_mi1"]),
            _block_mass(loading_sender_rownorm, mi2_component, truth_idx["sender_idx_mi2"]),
        ]),
        "Receiver_loading_ratio": np.nanmean([
            _block_mass(loading_receiver_rownorm, mi1_component, truth_idx["receiver_idx_mi1"]),
            _block_mass(loading_receiver_rownorm, mi2_component, truth_idx["receiver_idx_mi2"]),
        ]),
        "MI1_component": mi1_component,
        "MI2_component": mi2_component,
        "Metric_definition": "Row-normalized final trained loading mass within matched ground-truth blocks",
    }])
    blockmass_df.to_csv(
        os.path.join(file_savepath_main, "LoadingBlockMass_Ratio_Summary.csv"),
        index=False,
    )
    print("Saved loading block-mass summary table to:", os.path.join(file_savepath_main, "LoadingBlockMass_Ratio_Summary.csv"))


def _save_spidernet_edge_scores_export(file_savepath_main):
    edge_index_np = SpiderNet_data_pyg["edge_index"].to("cpu").detach().numpy()
    edge_MI1 = np.where(edgemeta_data["MetaItype"] == "MI-1")[0]
    edge_MI2 = np.where(edgemeta_data["MetaItype"] == "MI-2")[0]
    factor_use = Factor_envir.to("cpu").detach().numpy()
    factor_use = _safe_column_max_normalize_export(factor_use)
    mi1_scores = _get_best_component_scores_export(factor_use, edge_MI1=edge_MI1, edge_MI2=edge_MI2, mi_index=0)
    mi2_scores = _get_best_component_scores_export(factor_use, edge_MI1=edge_MI1, edge_MI2=edge_MI2, mi_index=1)
    edge_scores_df = pd.DataFrame({
        "sender_index": edge_index_np[:, 0],
        "receiver_index": edge_index_np[:, 1],
        "MI-1": mi1_scores,
        "MI-2": mi2_scores,
    })
    edge_scores_df.to_csv(os.path.join(file_savepath_main, "EdgeProgramScores.csv"), index=False)
    print("Saved SpiderNet edge scores to:", os.path.join(file_savepath_main, "EdgeProgramScores.csv"))


try:
    _save_edge_metric_tables_export(file_savepath_main=file_savepath_main)
    _save_loadingrank_summary_export(file_savepath_main=file_savepath_main)
    _save_spidernet_edge_scores_export(file_savepath_main=file_savepath_main)
except Exception as e:
    print(f"[Warning] Failed to export benchmark summary tables: {e}")
