module ScCChainPancancerRunnerResumeV7

using ScCChain
using DataFrames
using CSV
using Statistics
using Printf
using Dates

# ============================================================
# ScCChain runner for pan-cancer CCC baseline benchmark
# ------------------------------------------------------------
# Resume-safe + Windows-path-safe version.
#
# Input manifest columns generated by the spatial notebook's CCC stage:
#   sample_index,sample_id,sample_name,sample_tag,h5ad_path,radius,
#   n_obs,n_edges,sample_outdir,score_csv,legacy_score_csv
#
# Output per sample, by default:
#   <result-root>/s000/s000_ScCChain_edge_program_scores.csv
#
# The CSV contains:
#   sender_index, receiver_index, program_1, ..., program_K
#
# Why short output paths?
#   On Windows, long nested sample_name paths can fail at CSV.write with
#   SystemError: opening file ... No such file or directory.
#   This runner therefore uses sample_tag-based short output paths.
# ============================================================

const DEFAULT_MANIFEST = "D:/SpiderNet/Results/Pancancer/V1/SpiderNet_Result_dim11/Pancancer_Fibroblast_to_tumor_CCC_method_CancerSEA_SMD_comparison/baseline_CCC_outputs/ScCChain_input_manifest.csv"
const DEFAULT_LR_DB_CSV = "D:/SpiderNet/Results/Pancancer/V1/SpiderNet_Result_dim11/Pancancer_Fibroblast_to_tumor_CCC_method_CancerSEA_SMD_comparison/baseline_CCC_outputs/Pancancer_lr_db_for_scCChain.csv"
const DEFAULT_RESULT_ROOT = "D:/SpiderNet/Results/Pancancer/V1/SpiderNet_Result_dim11/Pancancer_Fibroblast_to_tumor_CCC_method_CancerSEA_SMD_comparison/baseline_CCC_outputs/ScCChain"
const DEFAULT_N_PROGRAMS = 11
const DEFAULT_SEED = 42
const DEFAULT_KNN_K = 10
const DEFAULT_ALPHA = 0.00002
const DEFAULT_SAMPLE_START = 1
const DEFAULT_SAMPLE_END = typemax(Int)

# If true, ignore sample_start/sample_end and only run the first manifest row.
# This is useful for a quick smoke test before launching all slices.
const DEFAULT_IF_TEST = false

function parse_cli_args(args::Vector{String})
    manifest = DEFAULT_MANIFEST
    lr_db_csv = DEFAULT_LR_DB_CSV
    result_root = DEFAULT_RESULT_ROOT
    n_programs = DEFAULT_N_PROGRAMS
    seed = DEFAULT_SEED
    knn_k = DEFAULT_KNN_K
    alpha = DEFAULT_ALPHA
    sample_start = DEFAULT_SAMPLE_START
    sample_end = DEFAULT_SAMPLE_END
    overwrite = false
    continue_on_error = true
    if_test = DEFAULT_IF_TEST

    i = 1
    while i <= length(args)
        flag = args[i]
        if flag in ["--manifest", "--lr-db-csv", "--result-root", "--n-programs", "--seed", "--knn-k", "--alpha", "--sample-start", "--sample-end"]
            if i == length(args)
                error("Missing value after $flag")
            end
            value = args[i + 1]
            if flag == "--manifest"
                manifest = value
            elseif flag == "--lr-db-csv"
                lr_db_csv = value
            elseif flag == "--result-root"
                result_root = value
            elseif flag == "--n-programs"
                n_programs = parse(Int, value)
            elseif flag == "--seed"
                seed = parse(Int, value)
            elseif flag == "--knn-k"
                knn_k = parse(Int, value)
            elseif flag == "--alpha"
                alpha = parse(Float64, value)
            elseif flag == "--sample-start"
                sample_start = parse(Int, value)
            elseif flag == "--sample-end"
                sample_end = parse(Int, value)
            end
            i += 2
        elseif flag == "--overwrite"
            overwrite = true
            i += 1
        elseif flag in ["--if-test", "--if_test"]
            if_test = true
            i += 1
        elseif flag in ["--no-if-test", "--no_if_test"]
            if_test = false
            i += 1
        elseif flag in ["--if-test-value", "--if_test_value"]
            if i == length(args)
                error("Missing value after $flag")
            end
            value = lowercase(strip(args[i + 1]))
            if_test = value in ["true", "t", "1", "yes", "y"]
            i += 2
        elseif flag == "--fail-fast"
            continue_on_error = false
            i += 1
        elseif flag == "--continue-on-error"
            continue_on_error = true
            i += 1
        elseif flag in ["-h", "--help"]
            println("""
ScCChain pan-cancer runner.

Options:
  --manifest PATH       CSV with sample_name,h5ad_path and optional radius/score_csv. Default: $DEFAULT_MANIFEST
  --lr-db-csv PATH      CSV with ligand,receptor,pathway. Default: $DEFAULT_LR_DB_CSV
  --result-root PATH    Output root. Default: $DEFAULT_RESULT_ROOT
  --n-programs INT      Number of ScCChain programs. Default: $DEFAULT_N_PROGRAMS
  --seed INT            Random seed. Default: $DEFAULT_SEED
  --knn-k INT           k used only if manifest radius is absent. Default: $DEFAULT_KNN_K
  --alpha FLOAT         build_cell_graph alpha. Default: $DEFAULT_ALPHA
  --sample-start INT    1-based first manifest row to run. Default: 1
  --sample-end INT      1-based last manifest row to run. Default: all
  --if-test             Test mode: ignore sample range and run only the first sample. Default: false
  --no-if-test          Disable test mode.
  --if-test-value BOOL  Set test mode explicitly: true/false.
  --overwrite           Re-run samples even if usable output CSV exists.
  --continue-on-error   Continue after failed samples. Default behavior.
  --fail-fast           Stop immediately when a sample fails.
""")
            exit(0)
        else
            error("Unknown argument: $flag")
        end
    end

    return (
        manifest = normpath_string(manifest),
        lr_db_csv = normpath_string(lr_db_csv),
        result_root = normpath_string(result_root),
        n_programs = n_programs,
        seed = seed,
        knn_k = knn_k,
        alpha = alpha,
        sample_start = sample_start,
        sample_end = sample_end,
        if_test = if_test,
        overwrite = overwrite,
        continue_on_error = continue_on_error,
    )
end

function normpath_string(x::AbstractString)
    # Use forward slashes consistently; Julia/Windows accepts them and this avoids mixed slash paths.
    return replace(String(x), "\\" => "/")
end

function sanitize_sample_name(x::AbstractString)
    y = replace(String(x), r"[^\w\-.]+" => "_")
    y = replace(y, r"_+" => "_")
    y = strip(y, ['_', ' ', '\t', '\n', '\r'])
    return isempty(y) ? "sample" : y
end

function sample_tag_from_index(sample_index::Integer)
    return @sprintf("s%03d", sample_index)
end

function parse_optional_float(x)
    if x === nothing || ismissing(x)
        return nothing
    end
    if x isa AbstractFloat || x isa Integer
        y = Float64(x)
        return isfinite(y) && y > 0 ? y : nothing
    end
    s = strip(String(x))
    if isempty(s) || lowercase(s) in ["nan", "none", "missing", "null"]
        return nothing
    end
    try
        y = parse(Float64, s)
        return isfinite(y) && y > 0 ? y : nothing
    catch
        return nothing
    end
end

function manifest_value(row, col::Symbol; default = nothing)
    if col in propertynames(row)
        v = getproperty(row, col)
        if v === nothing || ismissing(v)
            return default
        end
        return v
    end
    return default
end

function manifest_string(row, col::Symbol; default = "")
    v = manifest_value(row, col; default = default)
    if v === nothing || ismissing(v)
        return String(default)
    end
    s = strip(String(v))
    return isempty(s) ? String(default) : String(s)
end


function clean_gene_list_for_lr_db(x)
    if x === nothing || ismissing(x)
        return String[]
    end
    s = strip(String(x))
    if isempty(s)
        return String[]
    end

    # Handle Python-list-like strings such as "['ITGA5', 'ITGB1']".
    if startswith(s, "[") && endswith(s, "]")
        # Prefer quoted tokens if present.
        quoted = [m.captures[1] for m in eachmatch(r"'([^']+)'|\"([^\"]+)\"", s)]
        vals = String[]
        for m in eachmatch(r"'([^']+)'|\"([^\"]+)\"", s)
            v = m.captures[1] === nothing ? m.captures[2] : m.captures[1]
            push!(vals, String(v))
        end
        if !isempty(vals)
            vals = [strip(v) for v in vals]
            return unique([v for v in vals if !isempty(v)])
        end
        s = replace(s, "[" => "", "]" => "")
    end

    # Handle semicolon/comma/pipe/plus separated strings.
    s = replace(s, "'" => "", "\"" => "")
    raw_vals = split(s, r"[;,|+]")
    vals = [strip(String(v)) for v in raw_vals]
    vals = [v for v in vals if !isempty(v) && lowercase(v) ∉ ["missing", "none", "nan", "null"]]
    return unique(vals)
end

function make_lr_db_from_csv(path::AbstractString)
    if !isfile(path)
        error("LR DB CSV does not exist: $path")
    end
    lr_df = CSV.read(path, DataFrame)
    names_lower = Dict(lowercase(String(n)) => n for n in names(lr_df))
    ligand_col = get(names_lower, "ligand", nothing)
    receptor_col = get(names_lower, "receptor", nothing)
    pathway_col = get(names_lower, "pathway", nothing)
    if ligand_col === nothing || receptor_col === nothing
        error("LR DB CSV must contain ligand and receptor columns. Columns: $(names(lr_df))")
    end

    records = LRPairRecord[]
    dropped = 0
    for i in 1:nrow(lr_df)
        ligands = clean_gene_list_for_lr_db(lr_df[i, ligand_col])
        receptors = clean_gene_list_for_lr_db(lr_df[i, receptor_col])
        pathway_raw = pathway_col === nothing ? "Pancancer" : String(lr_df[i, pathway_col])
        pathway = sanitize_sample_name(pathway_raw)

        if isempty(ligands) || isempty(receptors)
            dropped += 1
            continue
        end

        pair_name = join(ligands, "+") * "—" * join(receptors, "+")
        push!(records, LRPairRecord(
            pair_name,
            ligands,
            receptors,
            pathway,
            Dict{String, Any}("annotation" => "Pancancer", "version" => "manual")
        ))
    end

    if isempty(records)
        error("No valid LR pairs parsed from LR DB CSV: $path")
    end
    if dropped > 0
        println("Warning: dropped ", dropped, " LR rows with empty ligand/receptor after parsing.")
    end
    println("First parsed LR pair: ", records[1])
    return LRPairDB(records, :custom, "human")
end

function median_knn_distance(coords::AbstractMatrix{<:Real}; k::Int = 10)
    n_cells = size(coords, 1)
    if size(coords, 2) != 2
        error("coords must be n_cells x 2, got size $(size(coords))")
    end
    if n_cells <= k
        error("Need more than k cells. Got n_cells=$n_cells, k=$k")
    end
    kth_distances = Vector{Float64}(undef, n_cells)
    for i in 1:n_cells
        xi = coords[i, 1]
        yi = coords[i, 2]
        dists = Vector{Float64}(undef, n_cells - 1)
        idx = 1
        for j in 1:n_cells
            if j == i
                continue
            end
            dx = coords[j, 1] - xi
            dy = coords[j, 2] - yi
            dists[idx] = sqrt(dx * dx + dy * dy)
            idx += 1
        end
        partialsort!(dists, 1:k)
        kth_distances[i] = dists[k]
    end
    return median(kth_distances), kth_distances
end

function build_graph_for_sample(sample_h5ad::AbstractString, db; radius_override, knn_k::Int, alpha::Float64)
    sample_h5ad = normpath_string(sample_h5ad)
    if !isfile(sample_h5ad)
        error("h5ad file does not exist: $sample_h5ad")
    end
    scdata = load_scdata(sample_h5ad)
    var_df = var_table(scdata)
    gene_col = if :Gene_name in propertynames(var_df)
        :Gene_name
    elseif :gene_name in propertynames(var_df)
        :gene_name
    elseif :feature_name in propertynames(var_df)
        :feature_name
    else
        first(propertynames(var_df))
    end
    gene_names = String.(var_df[!, gene_col])
    coords = Matrix{Float64}(spatial_coords(scdata))

    radius_source = "manifest"
    kth = Float64[]
    if radius_override === nothing
        radius_source = "median_knn_distance"
        radius, kth = median_knn_distance(coords; k = knn_k)
    else
        radius = Float64(radius_override)
    end

    println("Using radius=", radius, " (source=", radius_source, ")")
    pcs = pca(scdata; k = 30)
    graph = build_cell_graph(
        scdata,
        db;
        radius = radius,
        alpha = alpha,
        dim_red = pcs,
        gene_names = gene_names,
    )
    return graph, radius, kth, radius_source
end

function extract_sender_receiver(programs)
    prog_fields = fieldnames(typeof(programs))
    prog_values = Dict(string(f) => getfield(programs, f) for f in prog_fields)
    sender_index = nothing
    receiver_index = nothing
    for (k, v) in prog_values
        try
            if hasproperty(v, :sender_index) && hasproperty(v, :receiver_index)
                sender_index = v.sender_index
                receiver_index = v.receiver_index
                break
            end
        catch
        end
    end
    if sender_index === nothing || receiver_index === nothing
        error("Could not find sender_index / receiver_index in ScCChain program output.")
    end
    return sender_index, receiver_index, prog_values
end

function extract_score_matrix(programs, n_programs::Int)
    sender_index, receiver_index, prog_values = extract_sender_receiver(programs)
    n_edges = length(sender_index)
    candidate_mats = Dict{String, Any}()
    for (k, v) in prog_values
        if v isa AbstractMatrix
            s = size(v)
            if s[1] == n_edges
                candidate_mats[k] = v
            end
        end
    end
    if isempty(candidate_mats)
        error("No matrix found with n_edges rows in ScCChain program output.")
    end

    score_mat_name = nothing
    score_mat = nothing
    for (k, v) in candidate_mats
        if size(v, 2) == n_programs
            score_mat_name = k
            score_mat = v
            break
        end
    end
    if score_mat === nothing
        first_pair = first(candidate_mats)
        score_mat_name = first_pair.first
        score_mat = first_pair.second
        println("Warning: no matrix with exactly $n_programs columns. Using $score_mat_name with size $(size(score_mat)).")
    else
        println("Using ScCChain score matrix field: ", score_mat_name, " with size ", size(score_mat))
    end
    return sender_index, receiver_index, score_mat
end

function looks_like_sccchain_output(path::AbstractString; min_program_cols::Int = 1)
    path = normpath_string(path)
    if !isfile(path)
        return false, "missing"
    end
    try
        header = open(path, "r") do io
            eof(io) ? "" : readline(io)
        end
        cols = split(header, ',')
        if length(cols) < 3
            return false, "fewer than 3 columns"
        end
        program_cols = [c for c in cols if startswith(String(c), "program_")]
        if length(program_cols) < min_program_cols
            return false, "no program_* columns"
        end
        n_lines = countlines(path)
        if n_lines <= 1
            return false, "header only or empty CSV"
        end
        return true, "ok"
    catch e
        return false, "cannot read CSV header: $(repr(e))"
    end
end

function safe_write_csv(output_csv::AbstractString, df::DataFrame)
    output_csv = normpath_string(output_csv)
    parent = dirname(output_csv)
    if isempty(parent)
        parent = pwd()
    end
    mkpath(parent)
    if !isdir(parent)
        error("Output directory could not be created: $parent")
    end

    tmp_csv = joinpath(parent, ".$(basename(output_csv)).tmp_$(getpid()).csv")
    tmp_csv = normpath_string(tmp_csv)
    if isfile(tmp_csv)
        rm(tmp_csv; force = true)
    end

    open(tmp_csv, "w") do io
        CSV.write(io, df)
    end

    if isfile(output_csv)
        rm(output_csv; force = true)
    end
    mv(tmp_csv, output_csv; force = true)
    return output_csv
end

function save_edge_program_scores(programs, output_csv::AbstractString, n_programs::Int)
    sender_index, receiver_index, score_mat = extract_score_matrix(programs, n_programs)
    df = DataFrame(sender_index = sender_index, receiver_index = receiver_index)
    for j in 1:size(score_mat, 2)
        df[!, Symbol("program_$j")] = score_mat[:, j]
    end
    actual_csv = safe_write_csv(output_csv, df)
    println("Saved edge program scores to: ", actual_csv)
    return actual_csv
end

function save_radius_summary(output_dir::AbstractString, radius, kth_distances, knn_k::Int, radius_source::AbstractString)
    output_dir = normpath_string(output_dir)
    mkpath(output_dir)
    safe_write_csv(joinpath(output_dir, "radius_summary.csv"), DataFrame(radius=[radius], knn_k=[knn_k], radius_source=[radius_source]))
    if length(kth_distances) > 0
        safe_write_csv(joinpath(output_dir, "kth_nn_distances.csv"), DataFrame(cell_index=collect(1:length(kth_distances)), kth_nn_distance=kth_distances))
    end
end

function copy_existing_to_expected(existing_csv::AbstractString, expected_csv::AbstractString)
    existing_csv = normpath_string(existing_csv)
    expected_csv = normpath_string(expected_csv)
    if existing_csv == expected_csv
        return existing_csv, "existing"
    end
    mkpath(dirname(expected_csv))
    try
        cp(existing_csv, expected_csv; force = true)
        ok, reason = looks_like_sccchain_output(expected_csv)
        if ok
            println("Copied existing legacy ScCChain output to short path: ", expected_csv)
            return expected_csv, "copied_existing"
        else
            println("Warning: copied output is not usable: ", reason)
            return existing_csv, "existing_legacy"
        end
    catch e
        println("Warning: could not copy existing output to short path: ", repr(e))
        return existing_csv, "existing_legacy"
    end
end

function run_one_sample(sample_name::AbstractString, h5ad_path::AbstractString, radius_override, cfg, db, sample_tag::AbstractString, output_csv::AbstractString, legacy_csv::AbstractString = "")
    sample_safe = sanitize_sample_name(sample_name)
    output_csv = normpath_string(output_csv)
    sample_outdir = dirname(output_csv)

    candidate_existing = String[]
    push!(candidate_existing, output_csv)
    if !isempty(strip(legacy_csv))
        push!(candidate_existing, normpath_string(legacy_csv))
    end

    if !cfg.overwrite
        for p in candidate_existing
            ok, reason = looks_like_sccchain_output(p)
            if ok
                actual_csv, status = copy_existing_to_expected(p, output_csv)
                println("Skipping usable existing ScCChain output: ", actual_csv)
                return (status = status, score_csv = actual_csv, message = "usable existing output found")
            elseif isfile(normpath_string(p))
                println("Existing ScCChain output is not usable and will be regenerated: ", p, " (", reason, ")")
            end
        end
    end

    println("\n------------------------------------------------------")
    println("Processing sample: ", sample_safe)
    println("sample_tag: ", sample_tag)
    println("h5ad: ", h5ad_path)
    println("output_csv: ", output_csv)

    graph, radius, kth, radius_source = build_graph_for_sample(
        h5ad_path,
        db;
        radius_override = radius_override,
        knn_k = cfg.knn_k,
        alpha = cfg.alpha,
    )

    programs = discover_programs_bae(
        graph;
        n_zdims = cfg.n_programs,
        seed = cfg.seed,
        min_obs = 1,
        min_features = 1,
    )

    actual_csv = save_edge_program_scores(programs, output_csv, cfg.n_programs)
    save_radius_summary(sample_outdir, radius, kth, cfg.knn_k, radius_source)
    return (status = "generated", score_csv = actual_csv, message = "generated successfully")
end

function main()
    cfg = parse_cli_args(ARGS)
    println("Pan-cancer ScCChain runner v7 if_test AbstractString-safe no-kwcall")
    println("manifest: ", cfg.manifest)
    println("lr_db_csv: ", cfg.lr_db_csv)
    println("result_root: ", cfg.result_root)
    println("n_programs: ", cfg.n_programs)
    println("sample range: ", cfg.sample_start, " to ", cfg.sample_end)
    println("if_test: ", cfg.if_test)
    println("overwrite: ", cfg.overwrite)
    println("continue_on_error: ", cfg.continue_on_error)

    if !isfile(cfg.manifest)
        error("Manifest does not exist: $(cfg.manifest). Run the spatial notebook's CCC input-export stage first.")
    end

    db = make_lr_db_from_csv(cfg.lr_db_csv)
    println("Loaded custom LR DB with ", n_lrpairs(db), " LR pairs.")

    manifest_df = CSV.read(cfg.manifest, DataFrame)
    if !(:sample_name in propertynames(manifest_df)) || !(:h5ad_path in propertynames(manifest_df))
        error("Manifest must contain sample_name and h5ad_path columns. Columns: $(propertynames(manifest_df))")
    end

    mkpath(cfg.result_root)
    run_manifest_path = normpath_string(joinpath(cfg.result_root, "ScCChain_run_manifest.csv"))

    if cfg.if_test
        first_i = 1
        last_i = min(1, nrow(manifest_df))
        println("if_test=true: running only the first manifest row as a smoke test.")
    else
        first_i = max(1, cfg.sample_start)
        last_i = min(nrow(manifest_df), cfg.sample_end)
    end

    if first_i > last_i
        error("Invalid sample range: $first_i to $last_i for manifest with $(nrow(manifest_df)) rows")
    end

    run_rows = DataFrame(
        manifest_row = Int[],
        sample_index = Int[],
        sample_id = String[],
        sample_name = String[],
        sample_tag = String[],
        h5ad_path = String[],
        score_csv = String[],
        status = String[],
        message = String[],
        timestamp = String[],
    )

    for i in first_i:last_i
        row = manifest_df[i, :]
        sample_name = manifest_string(row, :sample_name)
        h5ad_path = normpath_string(manifest_string(row, :h5ad_path))
        sample_id = manifest_string(row, :sample_id; default = sample_name)

        sample_index_value = manifest_value(row, :sample_index; default = i - 1)
        sample_index = try
            Int(sample_index_value)
        catch
            i - 1
        end

        sample_tag = manifest_string(row, :sample_tag; default = sample_tag_from_index(sample_index))
        sample_tag = sanitize_sample_name(sample_tag)

        output_csv = manifest_string(row, :score_csv; default = "")
        if isempty(output_csv)
            output_csv = joinpath(cfg.result_root, sample_tag, "$(sample_tag)_ScCChain_edge_program_scores.csv")
        end
        output_csv = normpath_string(output_csv)

        legacy_csv = manifest_string(row, :legacy_score_csv; default = "")
        if isempty(legacy_csv)
            sample_safe = sanitize_sample_name(sample_name)
            legacy_csv = joinpath(cfg.result_root, sample_safe, "$(sample_safe)_ScCChain_edge_program_scores.csv")
        end
        legacy_csv = normpath_string(legacy_csv)

        radius_override = nothing
        if :radius in propertynames(manifest_df)
            radius_override = parse_optional_float(row.radius)
        end

        status = "failed"
        score_csv_actual = output_csv
        message = ""

        try
            res = run_one_sample(
                sample_name,
                h5ad_path,
                radius_override,
                cfg,
                db,
                sample_tag,
                output_csv,
                legacy_csv,
            )
            status = String(res.status)
            score_csv_actual = String(res.score_csv)
            message = String(res.message)
        catch e
            status = "failed"
            message = repr(e)
            println("ERROR while processing sample ", sample_name, ": ", message)
            if !cfg.continue_on_error
                push!(run_rows, (i, sample_index, sample_id, sample_name, sample_tag, h5ad_path, score_csv_actual, status, message, string(now())))
                safe_write_csv(run_manifest_path, run_rows)
                rethrow(e)
            end
        end

        push!(run_rows, (i, sample_index, sample_id, sample_name, sample_tag, h5ad_path, score_csv_actual, status, message, string(now())))
        safe_write_csv(run_manifest_path, run_rows)
    end

    println("\nSelected ScCChain pan-cancer samples finished.")
    println("Saved ScCChain run manifest: ", run_manifest_path)
end


end # module ScCChainPancancerRunnerResumeV7

# Always run when executed or included interactively.
Base.invokelatest(ScCChainPancancerRunnerResumeV7.main)
