# Analyze overall survival using tumor-only TCGA MI projection scores.
# Preserve the 11-MI Cox scan, selected-MI tertile KM plots, and the nested models
# adjusted for clinical variables, tumor programs, and optional purity.
# Inputs: projected MI CSVs, GDC clinical/expression data, and CancerSEA markers.
# Tables, KM plotting caches, and figures are written under output/survival/.
# Default KM selection remains MI2/MI3/MI9; --mi changes plotting selection only.

# Resolve the shared runtime relative to this script, independent of the working directory.
.pancancer_file <- if (sys.nframe() > 0L && !is.null(sys.frame(1)$ofile)) {
  sys.frame(1)$ofile
} else {
  sub("^--file=", "", grep("^--file=", commandArgs(), value = TRUE)[1])
}
.pancancer_dir <- dirname(normalizePath(.pancancer_file, winslash = "/", mustWork = TRUE))
source(file.path(.pancancer_dir, "plot_saved_R.R"), local = TRUE)
.pancancer <- pancancer_options("survival", .pancancer_dir)
if (.pancancer$mode != "full") {
  pancancer_dispatch(.pancancer)
  quit(save = "no", status = 0L)
}
pancancer_check(.pancancer)

# -----------------------------
# Result paths and GDC project metadata
# -----------------------------
# Configure file_path_main and work_dir for the local data layout before execution.
# file_path_main includes a trailing slash used by the output filename expressions.
file_path_main <- paste0(file.path(.pancancer$output, "survival"), "/")
dir.create(file_path_main, recursive = TRUE, showWarnings = FALSE)

library(TCGAbiolinks)

# GDC downloads are relative to work_dir; setwd() changes the R session directory.
work_dir <- .pancancer$gdc
dir.create(work_dir, recursive = TRUE, showWarnings = FALSE)
setwd(work_dir)

# the manuscript runs alongside the existing KM/Cox analysis.
run_s27b_nested_lrt <- TRUE
s27b_cancersea_dir <- .pancancer$cancersea
s27b_include_tumor_purity <- TRUE

# -----------------------------
# MI selection, score source, and tumor sample filter
# -----------------------------
MI_unique <- c(
  "MI1", "MI2", "MI3", "MI4", "MI5",
  "MI6", "MI7", "MI8", "MI9", "MI10",
  "MI11"
)

# KM plots to export from TCGA MI decomposition results.
# The full Cox scan still runs for all MIs in MI_unique; this only controls
# which MIs are drawn as Kaplan-Meier PDFs.
km_mi_to_plot <- .pancancer$mi

# The optional marker-gene score uses a pre-existing Phenotype_topgenes_summary.
MI_source_type <- "MIdecomposition"

# Output label. Keep tumor-only survival outputs separate from older analyses
# that may have included normal samples.
MI_type <- paste0(MI_source_type, "_tumor_only")

# Tumor-only MI decomposition generated by TCGA_MI_decomposition_V2_updated_tumor_only.R
mi_decomposition_dir <- pancancer_projection_cache(.pancancer)

# Survival analyses are restricted to tumor_keep samples defined only by coldata$sample_type.
tumor_sample_types <- c(
  "Primary Tumor",
  "Metastatic",
  "Recurrent Tumor",
  "Additional - New Primary"
)

nontumor_sample_types <- c(
  "Solid Tissue Normal",
  "Blood Derived Normal",
  "Buccal Cell Normal",
  "Bone Marrow Normal",
  "Normal"
)

# -----------------------------
# Analysis dependencies
# -----------------------------
library(SummarizedExperiment)
library(dplyr)
library(ggplot2)
library(survival)
library(survminer)
library(edgeR)


## Kaplan-Meier plots use Low, Mid, and High tertile groups.


## ===============================
## TCGA projects
## ===============================
TCGA_project_list <- c(
  "TCGA-BRCA",
  "TCGA-COAD",
  "TCGA-LIHC",
  "TCGA-LUAD",
  "TCGA-LUSC",
  "TCGA-SKCM",
  "TCGA-OV",
  "TCGA-PRAD",
  "TCGA-UCEC"
)

## ===============================
## Result matrices: adjusted
## ===============================
HR_mat <- matrix(NA, nrow = length(MI_unique), ncol = length(TCGA_project_list))
pvalue_mat <- matrix(NA, nrow = length(MI_unique), ncol = length(TCGA_project_list))
pvalue_mat_bettersurvival <- matrix(NA, nrow = length(MI_unique), ncol = length(TCGA_project_list))
pvalue_mat_worsesurvival <- matrix(NA, nrow = length(MI_unique), ncol = length(TCGA_project_list))

rownames(HR_mat) <- MI_unique
colnames(HR_mat) <- TCGA_project_list
rownames(pvalue_mat) <- MI_unique
colnames(pvalue_mat) <- TCGA_project_list
rownames(pvalue_mat_bettersurvival) <- MI_unique
colnames(pvalue_mat_bettersurvival) <- TCGA_project_list
rownames(pvalue_mat_worsesurvival) <- MI_unique
colnames(pvalue_mat_worsesurvival) <- TCGA_project_list

## ===============================
## Result matrices: unadjusted
## ===============================
HR_mat_unadj <- matrix(NA, nrow = length(MI_unique), ncol = length(TCGA_project_list))
pvalue_mat_unadj <- matrix(NA, nrow = length(MI_unique), ncol = length(TCGA_project_list))
pvalue_mat_unadj_bettersurvival <- matrix(NA, nrow = length(MI_unique), ncol = length(TCGA_project_list))
pvalue_mat_unadj_worsesurvival  <- matrix(NA, nrow = length(MI_unique), ncol = length(TCGA_project_list))

rownames(HR_mat_unadj) <- MI_unique
colnames(HR_mat_unadj) <- TCGA_project_list
rownames(pvalue_mat_unadj) <- MI_unique
colnames(pvalue_mat_unadj) <- TCGA_project_list
rownames(pvalue_mat_unadj_bettersurvival) <- MI_unique
colnames(pvalue_mat_unadj_bettersurvival) <- TCGA_project_list
rownames(pvalue_mat_unadj_worsesurvival) <- MI_unique
colnames(pvalue_mat_unadj_worsesurvival) <- TCGA_project_list

## ===============================
## Sample annotations and matched MI estimates
## ===============================
clinical_data_list <- list()
tumor_filter_record_list <- list()
MI_decomposition_list <- list()


## =========================================================
## Add a clinical covariate when available and informative
## =========================================================
add_covariate <- function(df, coldata_use, varname, as_factor = FALSE) {
  if (!(varname %in% colnames(coldata_use))) return(df)

  x <- coldata_use[[varname]]
  if (all(is.na(x))) return(df)

  if (as_factor) {
    x <- as.factor(x)
    if (length(unique(stats::na.omit(x))) < 2) return(df)
  } else {
    x <- suppressWarnings(as.numeric(x))
    if (all(is.na(x))) return(df)
  }

  df[[varname]] <- x
  df
}

## =========================================================
## Standardize continuous MI abundance within the model analysis set.
## The Cox hazard ratio is per one-standard-deviation increase.
## =========================================================
scale_score_for_cox <- function(score_vec) {
  score_vec <- as.numeric(score_vec)
  score_sd <- stats::sd(score_vec, na.rm = TRUE)
  if (!is.finite(score_sd) || score_sd == 0) {
    return(rep(NA_real_, length(score_vec)))
  }
  as.numeric(scale(score_vec))
}

## =========================================================
## Kaplan-Meier curves for score tertiles with sample-count labels.
## Log-rank P compares groups; adjusted HR/Wald P use continuous MI abundance.
## =========================================================

## =========================================================
## Assign score tertiles using type-7 quantiles.
## Low: score <= q1; Mid: q1 < score <= q2; High: score > q2.
## Ties can produce unequal group sizes; coincident cutoffs leave groups missing.
## =========================================================
assign_score_tertile_group <- function(score_vec) {
  score_vec <- as.numeric(score_vec)
  group <- rep(NA_character_, length(score_vec))

  if (sum(is.finite(score_vec)) < 3) {
    return(factor(group, levels = c("Low", "Mid", "High")))
  }

  qs <- stats::quantile(
    score_vec,
    probs = c(1/3, 2/3),
    na.rm = TRUE,
    names = FALSE,
    type = 7
  )

  q1 <- qs[1]
  q2 <- qs[2]

  if (!is.finite(q1) || !is.finite(q2) || q1 == q2) {
    return(factor(group, levels = c("Low", "Mid", "High")))
  }

  group[is.finite(score_vec) & score_vec <= q1] <- "Low"
  group[is.finite(score_vec) & score_vec >  q1 & score_vec <= q2] <- "Mid"
  group[is.finite(score_vec) & score_vec >  q2] <- "High"

  factor(group, levels = c("Low", "Mid", "High"))
}

# =============================================================================
# prognostic value of MI-4 beyond clinical and tumor-program scores
# =============================================================================
# Each cohort is passed from the KM loop after tumor filtering and MI matching;
# no second GDC download, expression transform, or external R script is needed.
# Module scores are mean marker log-CPM, as in the original nested-LRT analysis.
# The two Cox models use identical complete cases and differ by score_scaled.
# The scatter x-axis uses the clinical-only KM-script HR; y uses the nested LRT.
# The retained model includes EMT, optional purity, and tumor_grade. The paper
# describes invasion/angiogenesis/hypoxia and stage; see the review for this gap.
create_s27b_analysis <- function(result_dir, cancerseadb_path, MI_unique,
                                  TCGA_project_list, MI_source_type, MI_type,
                                  include_tumor_purity = TRUE) {
  if (!requireNamespace("ggrepel", quietly = TRUE)) {
    stop("the manuscript requires the ggrepel package.")
  }
  km_hr_path <- file.path(result_dir, paste0("TCGA_MIs_HR_matrix_", MI_type, ".csv"))
  file_path_main <- paste0(file.path(result_dir, "S27b_nestedLRT"), "/")
  cancerseadb_path <- paste0(sub("[/\\\\]+$", "", cancerseadb_path), "/")
  dir.create(file_path_main, recursive = TRUE, showWarnings = FALSE)
  km_mi_to_plot <- "MI4"
  ## If TRUE, tumor purity is added to BOTH nested LRT models:
  ##   Model A  = clinical covariates + CancerSEA module scores + tumor_purity
  ##   Model AB = Model A + score_scaled
  ## The script searches common TCGA / PanCancerAtlas-style purity columns in
  ## colData(expdat). If no usable tumor-purity column is found for a cohort,
  ## that cohort is analyzed without tumor purity and a message is printed.
  If_add_tumor_purity <- include_tumor_purity

  If_add_tumorpurity <- If_add_tumor_purity

  tumor_purity_covariate_name <- "tumor_purity"

  tumor_purity_candidate_cols <- c(
    "tumor_purity",
    "Tumor_purity",
    "Tumor.Purity",
    "Tumor_purity_ESTIMATE",
    "tumor_purity_estimate",
    "tumor.purity",
    "purity",
    "Purity",
    "ABSOLUTE_purity",
    "absolute_purity",
    "ABSOLUTE.Purity",
    "paper_Tumor.Purity",
    "paper_Tumor.purity",
    "paper_tumor_purity",
    "CPE",
    "ESTIMATE_tumor_purity",
    "ESTIMATE.TumorPurity"
  )
  MI_type_addmodules <- paste0(MI_type, "_addInvasionAngiogenesisEMTHypoxia")
  if (isTRUE(If_add_tumor_purity)) {
    MI_type_addmodules <- paste0(MI_type_addmodules, "_addTumorPurity")
  }
  Invasion_path     <- paste0(cancerseadb_path, "Invasion.txt")
  Angiogenesis_path <- paste0(cancerseadb_path, "Angiogenesis.txt")
  EMT_path          <- paste0(cancerseadb_path, "EMT.txt")
  Hypoxia_path      <- paste0(cancerseadb_path, "Hypoxia.txt")

  marker_paths <- c(
    Invasion     = Invasion_path,
    Angiogenesis = Angiogenesis_path,
    EMT          = EMT_path,
    Hypoxia      = Hypoxia_path
  )

  missing_marker_files <- marker_paths[!file.exists(marker_paths)]
  if (length(missing_marker_files) > 0) {
    stop(
      paste0(
        "Missing CancerSEA marker files:\n",
        paste(names(missing_marker_files), missing_marker_files, sep = ": ", collapse = "\n")
      )
    )
  }

  Invasion_markers <- read.table(
    Invasion_path,
    header = TRUE,
    stringsAsFactors = FALSE
  )$GeneName

  Angiogenesis_markers <- read.table(
    Angiogenesis_path,
    header = TRUE,
    stringsAsFactors = FALSE
  )$GeneName

  EMT_markers <- read.table(
    EMT_path,
    header = TRUE,
    stringsAsFactors = FALSE
  )$GeneName

  Hypoxia_markers <- read.table(
    Hypoxia_path,
    header = TRUE,
    stringsAsFactors = FALSE
  )$GeneName

  ## Optional: union of all marker genes if needed later

  marker_list <- list(
    Invasion     = Invasion_markers,
    Angiogenesis = Angiogenesis_markers,
    EMT          = EMT_markers,
    Hypoxia      = Hypoxia_markers
  )

  ## Standardize marker vectors: remove NA/empty/duplicated genes
  marker_list <- lapply(marker_list, function(x) {
    x <- unique(as.character(x))
    x <- x[!is.na(x) & x != ""]
    x
  })

  .required_marker_names <- c(
    "Invasion",
    "Angiogenesis",
    "EMT",
    "Hypoxia"
  )

  missing_marker_sets <- setdiff(.required_marker_names, names(marker_list))
  if (length(missing_marker_sets) > 0) {
    stop(
      paste0(
        "marker_list is missing required gene sets: ",
        paste(missing_marker_sets, collapse = ", ")
      )
    )
  }

  empty_marker_sets <- names(marker_list)[lengths(marker_list) == 0]
  if (length(empty_marker_sets) > 0) {
    stop(
      paste0(
        "These CancerSEA marker sets are empty after loading: ",
        paste(empty_marker_sets, collapse = ", ")
      )
    )
  }

  marker_list <- marker_list[.required_marker_names]

  message(
    "[Marker loading] CancerSEA marker_list loaded from ",
    cancerseadb_path,
    ": ",
    paste(names(marker_list), lengths(marker_list), sep = "=", collapse = "; ")
  )
  add_covariate <- function(df, coldata_use, varname, as_factor = FALSE) {
    if (!(varname %in% colnames(coldata_use))) return(df)
  
    x <- coldata_use[[varname]]
    if (all(is.na(x))) return(df)
  
    if (as_factor) {
      x <- as.factor(x)
      if (length(unique(stats::na.omit(x))) < 2) return(df)
    } else {
      x <- suppressWarnings(as.numeric(x))
      if (all(is.na(x))) return(df)
    }
  
    df[[varname]] <- x
    df
  }

  ## =========================================================
  ## Helper: find and add tumor purity covariate
  ## =========================================================
  find_tumor_purity_column <- function(coldata_use,
                                       candidate_cols = tumor_purity_candidate_cols,
                                       min_nonmissing = 10) {
    if (is.null(coldata_use) || ncol(coldata_use) == 0) {
      return(NA_character_)
    }

    col_names <- colnames(coldata_use)

    ## First try explicitly provided candidate names, then any column name
    ## containing "purity", "absolute" or exact/near-exact "CPE".
    candidate_existing <- intersect(candidate_cols, col_names)

    pattern_cols <- unique(c(
      grep("purity", col_names, ignore.case = TRUE, value = TRUE),
      grep("absolute", col_names, ignore.case = TRUE, value = TRUE),
      grep("^CPE$|_CPE$|\\.CPE$", col_names, ignore.case = TRUE, value = TRUE)
    ))

    candidate_existing <- unique(c(candidate_existing, pattern_cols))

    if (length(candidate_existing) == 0) {
      return(NA_character_)
    }

    for (col_cur in candidate_existing) {
      x <- suppressWarnings(as.numeric(coldata_use[[col_cur]]))
      x_sd <- stats::sd(x, na.rm = TRUE)

      if (sum(is.finite(x)) >= min_nonmissing &&
          is.finite(x_sd) && x_sd > 0) {
        return(col_cur)
      }
    }

    NA_character_
  }

  summarize_tumor_purity_source <- function(project_cur, coldata_use,
                                            if_add = If_add_tumor_purity,
                                            source_col = NA_character_) {
    if (!isTRUE(if_add)) {
      return(data.frame(
        project = project_cur,
        If_add_tumor_purity = FALSE,
        tumor_purity_source_col = NA_character_,
        n_nonmissing = NA_integer_,
        mean_tumor_purity = NA_real_,
        sd_tumor_purity = NA_real_,
        stringsAsFactors = FALSE,
        check.names = FALSE
      ))
    }

    if (is.na(source_col) || !(source_col %in% colnames(coldata_use))) {
      return(data.frame(
        project = project_cur,
        If_add_tumor_purity = TRUE,
        tumor_purity_source_col = NA_character_,
        n_nonmissing = 0L,
        mean_tumor_purity = NA_real_,
        sd_tumor_purity = NA_real_,
        stringsAsFactors = FALSE,
        check.names = FALSE
      ))
    }

    x <- suppressWarnings(as.numeric(coldata_use[[source_col]]))

    data.frame(
      project = project_cur,
      If_add_tumor_purity = TRUE,
      tumor_purity_source_col = source_col,
      n_nonmissing = sum(is.finite(x)),
      mean_tumor_purity = mean(x, na.rm = TRUE),
      sd_tumor_purity = stats::sd(x, na.rm = TRUE),
      stringsAsFactors = FALSE,
      check.names = FALSE
    )
  }

  add_tumor_purity_covariate <- function(df, coldata_use,
                                         if_add = If_add_tumor_purity,
                                         out_col = tumor_purity_covariate_name,
                                         source_col = NULL) {
    if (!isTRUE(if_add)) {
      return(df)
    }

    if (is.null(source_col)) {
      source_col <- find_tumor_purity_column(coldata_use)
    }

    if (is.na(source_col) || !(source_col %in% colnames(coldata_use))) {
      return(df)
    }

    if (nrow(coldata_use) != nrow(df)) {
      if ("sample" %in% colnames(df) && all(df$sample %in% rownames(coldata_use))) {
        coldata_use <- coldata_use[df$sample, , drop = FALSE]
      } else {
        stop("Cannot safely align tumor purity covariate to survival dataframe.")
      }
    }

    x <- suppressWarnings(as.numeric(coldata_use[[source_col]]))
    x_sd <- stats::sd(x, na.rm = TRUE)

    if (sum(is.finite(x)) < 10 || !is.finite(x_sd) || x_sd == 0) {
      message("  -> Tumor-purity column found (", source_col, ") but it is not usable; continuing without tumor purity.")
      return(df)
    }

    df[[out_col]] <- x
    df
  }

  ## =========================================================
  ## Helper: z-score continuous MI strength within the current
  ## analysis cohort. The Cox HR is therefore per 1 SD increase
  ## in MI strength, not High-vs-Low group.
  ## =========================================================
  scale_score_for_cox <- function(score_vec) {
    score_vec <- as.numeric(score_vec)
    score_sd <- stats::sd(score_vec, na.rm = TRUE)
    if (!is.finite(score_sd) || score_sd == 0) {
      return(rep(NA_real_, length(score_vec)))
    }
    as.numeric(scale(score_vec))
  }

  ## =========================================================
  ## Helper: compute per-sample module scores from marker lists
  ## Module score = average logCPM expression across marker genes
  ## detected in the current TCGA expression matrix.
  ## =========================================================
  .safe_colname <- function(x) {
    x <- gsub("[^A-Za-z0-9_]+", "_", as.character(x))
    x <- gsub("_+", "_", x)
    x <- gsub("^_|_$", "", x)
    x
  }

  compute_marker_module_scores <- function(expr_mat, marker_list) {
    if (is.null(marker_list) || length(marker_list) == 0) {
      return(data.frame(row.names = colnames(expr_mat)))
    }

    gene_names <- rownames(expr_mat)
    gene_names_upper <- toupper(gene_names)

    module_score_df <- data.frame(
      sample = colnames(expr_mat),
      stringsAsFactors = FALSE
    )
    rownames(module_score_df) <- module_score_df$sample

    for (module_name in names(marker_list)) {
      markers_cur <- unique(toupper(as.character(marker_list[[module_name]])))
      markers_cur <- markers_cur[!is.na(markers_cur) & markers_cur != ""]

      row_idx <- which(gene_names_upper %in% markers_cur)
      score_col <- paste0(.safe_colname(module_name), "_module_score")

      message(
        "  -> ", module_name, ": ",
        length(unique(gene_names_upper[row_idx])), "/", length(markers_cur),
        " marker genes detected"
      )

      if (length(row_idx) == 0) {
        module_score_df[[score_col]] <- NA_real_
      } else {
        module_score_df[[score_col]] <- as.numeric(
          colMeans(expr_mat[row_idx, , drop = FALSE], na.rm = TRUE)
        )
      }
    }

    module_score_df$sample <- NULL
    module_score_df
  }

  ## Add usable module-score columns to a survival data.frame by sample ID.
  add_module_scores_to_df <- function(df, module_score_df) {
    if (is.null(module_score_df) || ncol(module_score_df) == 0) return(df)
    if (!("sample" %in% colnames(df))) return(df)

    module_score_df <- as.data.frame(module_score_df)
    module_use <- module_score_df[df$sample, , drop = FALSE]

    for (score_col in colnames(module_use)) {
      x <- suppressWarnings(as.numeric(module_use[[score_col]]))
      x_sd <- stats::sd(x, na.rm = TRUE)

      ## Skip unavailable or non-informative module scores to avoid Cox failures.
      if (sum(is.finite(x)) < 10) next
      if (!is.finite(x_sd) || x_sd == 0) next

      df[[score_col]] <- x
    }

    df
  }

  ## Filter Cox covariates to avoid one-level factors or zero-variance numerics.
  filter_usable_covars <- function(df, candidate_covars) {
    candidate_covars <- candidate_covars[candidate_covars %in% colnames(df)]

    Filter(function(v) {
      x <- df[[v]]
      if (is.factor(x) || is.character(x)) {
        length(unique(stats::na.omit(as.character(x)))) >= 2
      } else {
        x <- suppressWarnings(as.numeric(x))
        x_sd <- stats::sd(x, na.rm = TRUE)
        sum(is.finite(x)) >= 2 && is.finite(x_sd) && x_sd > 0
      }
    }, candidate_covars)
  }

  ## Extract the LRT row from anova(fit_A, fit_AB, test = "LRT") robustly.
  extract_nested_lrt <- function(lrt_tab) {
    if (is.null(lrt_tab) || nrow(lrt_tab) < 2) {
      return(list(chisq = NA_real_, df = NA_real_, pvalue = NA_real_))
    }

    lrt_df <- as.data.frame(lrt_tab)
    lrt_row <- lrt_df[nrow(lrt_df), , drop = FALSE]

    chisq_col <- intersect(c("Chisq", "Chi-square", "ChiSq"), colnames(lrt_df))
    df_col <- intersect(c("Df", "df", "DF"), colnames(lrt_df))
    p_col <- grep("Pr|P", colnames(lrt_df), value = TRUE)

    chisq_val <- if (length(chisq_col) > 0) as.numeric(lrt_row[[chisq_col[1]]]) else NA_real_
    df_val <- if (length(df_col) > 0) as.numeric(lrt_row[[df_col[1]]]) else NA_real_
    p_val <- if (length(p_col) > 0) as.numeric(lrt_row[[p_col[1]]]) else NA_real_

    list(chisq = chisq_val, df = df_val, pvalue = p_val)
  }

  choose_score_threshold <- function(score_vec) {
    score_vec <- as.numeric(score_vec)
    score_vec <- score_vec[is.finite(score_vec)]
  
    if (length(score_vec) == 0) return(NA_real_)
  
    threshold_score <- median(score_vec, na.rm = TRUE)
  
    if (threshold_score > 0.7) {
      threshold_score <- quantile(score_vec, 0.25, na.rm = TRUE)
    }
  
    return(threshold_score)
  }
  HR_mat <- matrix(NA, nrow = length(MI_unique), ncol = length(TCGA_project_list))
  pvalue_mat <- matrix(NA, nrow = length(MI_unique), ncol = length(TCGA_project_list))
  pvalue_mat_bettersurvival <- matrix(NA, nrow = length(MI_unique), ncol = length(TCGA_project_list))
  pvalue_mat_worsesurvival <- matrix(NA, nrow = length(MI_unique), ncol = length(TCGA_project_list))

  ## Nested Cox likelihood-ratio test:
  ##   Model A  = clinical covariates + optional tumor_purity + marker module scores
  ##   Model AB = Model A + score_scaled
  ## This tests whether score_scaled adds survival-associated information
  ## beyond the simpler clinical/tumor-purity/module-score model.
  nestedLRT_chisq_mat <- matrix(NA, nrow = length(MI_unique), ncol = length(TCGA_project_list))
  nestedLRT_df_mat <- matrix(NA, nrow = length(MI_unique), ncol = length(TCGA_project_list))
  nestedLRT_pvalue_mat <- matrix(NA, nrow = length(MI_unique), ncol = length(TCGA_project_list))

  rownames(HR_mat) <- MI_unique
  colnames(HR_mat) <- TCGA_project_list
  rownames(pvalue_mat) <- MI_unique
  colnames(pvalue_mat) <- TCGA_project_list
  rownames(pvalue_mat_bettersurvival) <- MI_unique
  colnames(pvalue_mat_bettersurvival) <- TCGA_project_list
  rownames(pvalue_mat_worsesurvival) <- MI_unique
  colnames(pvalue_mat_worsesurvival) <- TCGA_project_list
  rownames(nestedLRT_chisq_mat) <- MI_unique
  colnames(nestedLRT_chisq_mat) <- TCGA_project_list
  rownames(nestedLRT_df_mat) <- MI_unique
  colnames(nestedLRT_df_mat) <- TCGA_project_list
  rownames(nestedLRT_pvalue_mat) <- MI_unique
  colnames(nestedLRT_pvalue_mat) <- TCGA_project_list

  ## ===============================
  ## Result matrices: unadjusted (NO covariates)
  ## ===============================
  HR_mat_unadj <- matrix(NA, nrow = length(MI_unique), ncol = length(TCGA_project_list))
  pvalue_mat_unadj <- matrix(NA, nrow = length(MI_unique), ncol = length(TCGA_project_list))
  pvalue_mat_unadj_bettersurvival <- matrix(NA, nrow = length(MI_unique), ncol = length(TCGA_project_list))
  pvalue_mat_unadj_worsesurvival  <- matrix(NA, nrow = length(MI_unique), ncol = length(TCGA_project_list))

  rownames(HR_mat_unadj) <- MI_unique
  colnames(HR_mat_unadj) <- TCGA_project_list
  rownames(pvalue_mat_unadj) <- MI_unique
  colnames(pvalue_mat_unadj) <- TCGA_project_list
  rownames(pvalue_mat_unadj_bettersurvival) <- MI_unique
  colnames(pvalue_mat_unadj_bettersurvival) <- TCGA_project_list
  rownames(pvalue_mat_unadj_worsesurvival) <- MI_unique
  colnames(pvalue_mat_unadj_worsesurvival) <- TCGA_project_list

  MI_decomposition_list <- list()
  module_score_list <- list()
  tumor_purity_source_list <- list()
  model_audit_list <- list()

  add_cohort <- function(project_cur, expr_cpm, MI_decomposition, common_samples,
                         coldata, idx_in_expr, expr, time_use, status_use) {
      module_score_df <- compute_marker_module_scores(
        expr_mat = expr_cpm,
        marker_list = marker_list
      )

      MI_decomposition_list[[project_cur]] <<- MI_decomposition
      module_score_list[[project_cur]] <<- module_score_df
  

      ## Align clinical covariates to common_samples once per project.
      coldata_common <- coldata[idx_in_expr, , drop = FALSE]
      rownames(coldata_common) <- colnames(expr)[idx_in_expr]
      coldata_common <- coldata_common[common_samples, , drop = FALSE]

      ## Tumor purity source is cohort-specific; record it for QC and reuse in
      ## all MI-specific Cox models for this project.
      tumor_purity_col_project <- if (isTRUE(If_add_tumor_purity)) {
        find_tumor_purity_column(coldata_common)
      } else {
        NA_character_
      }

      if (isTRUE(If_add_tumor_purity)) {
        if (is.na(tumor_purity_col_project)) {
          message("  -> Tumor purity requested but no usable tumor-purity column found for ", project_cur, ".")
        } else {
          message("  -> Tumor purity covariate for ", project_cur, ": ", tumor_purity_col_project)
        }
      }

      tumor_purity_source_list[[project_cur]] <<- summarize_tumor_purity_source(
        project_cur = project_cur,
        coldata_use = coldata_common,
        if_add = If_add_tumor_purity,
        source_col = tumor_purity_col_project
      )

      ## ===============================
      ## per-project result vectors
      ## ===============================
      HR_list <- rep(NA, length(MI_unique))
      pvalue_list <- rep(NA, length(MI_unique))
      pvalue_list_bettersurvival <- rep(NA, length(MI_unique))
      pvalue_list_worsesurvival <- rep(NA, length(MI_unique))

      ## Nested Cox LRT vectors for testing added value of score_scaled
      ## beyond clinical covariates + marker module scores.
      nestedLRT_chisq_list <- rep(NA, length(MI_unique))
      nestedLRT_df_list <- rep(NA, length(MI_unique))
      nestedLRT_pvalue_list <- rep(NA, length(MI_unique))
  
      HR_list_unadj <- rep(NA, length(MI_unique))
      pvalue_list_unadj <- rep(NA, length(MI_unique))
      pvalue_list_unadj_bettersurvival <- rep(NA, length(MI_unique))
      pvalue_list_unadj_worsesurvival <- rep(NA, length(MI_unique))

      for (i in seq_along(MI_unique)) {
        MI_cur <- MI_unique[i]
    
        ## -------------------------------
        ## score per sample
        ## -------------------------------
        if (MI_source_type == "Markergene") {
          Markergene_list <- unique(
            Phenotype_topgenes_summary$Genes[
              Phenotype_topgenes_summary$MI == MI_cur
            ]
          )
      
          expr_cpm_marker <- expr_cpm[rownames(expr_cpm) %in% Markergene_list, , drop = FALSE]
          if (nrow(expr_cpm_marker) == 0) next
      
          sample_score <- colMeans(expr_cpm_marker, na.rm = TRUE)
        } else {
          if (!(MI_cur %in% colnames(MI_decomposition))) next
          sample_score <- MI_decomposition[, MI_cur]
        }
    
        ## -------------------------------
        ## survival df (base)
        ## -------------------------------
        df_surv <- data.frame(
          sample  = common_samples,
          score   = as.numeric(sample_score),
          time    = as.numeric(time_use),
          status  = as.numeric(status_use),
          stringsAsFactors = FALSE
        )
    
        df_surv <- df_surv[complete.cases(df_surv[, c("score", "time", "status")]), , drop = FALSE]
        if (nrow(df_surv) < 10 || length(unique(df_surv$status)) < 2) next
        if (sum(df_surv$status == 1) < 3) next
    
        ## Scaled continuous MI strength for Cox regression.
        ## The High/Low group below is only used for KM visualization/log-rank.
        df_surv$score_scaled <- scale_score_for_cox(df_surv$score)
        if (all(is.na(df_surv$score_scaled))) next
    
        threshold_score <- choose_score_threshold(df_surv$score)
    
        if (MI_cur %in% km_mi_to_plot) {
          print(paste("Project:", project_cur, "MI:", MI_cur,
                      "Threshold used:", signif(threshold_score, 4)))
          print(summary(df_surv$score))
        }
    
        df_surv$group <- ifelse(
          df_surv$score >= threshold_score,
          "High", "Low"
        )
        ## The original binary-group gate is retained before continuous Cox fitting.
        df_surv$group <- factor(df_surv$group, levels = c("Low", "High"))
    
        if (length(unique(df_surv$group[!is.na(df_surv$group)])) < 2) next
    
        ## ===============================
        ## (A) Unadjusted Cox: scaled continuous MI strength only
        ##     HR = per 1 SD increase in MI strength
        ## ===============================
        fit_unadj <- try(coxph(Surv(time, status) ~ score_scaled, data = df_surv), silent = TRUE)
        if (!inherits(fit_unadj, "try-error")) {
          s_unadj <- summary(fit_unadj)
          if ("score_scaled" %in% rownames(s_unadj$coefficients)) {
            HR_list_unadj[i] <- s_unadj$coefficients["score_scaled", "exp(coef)"]
            pvalue_list_unadj[i] <- s_unadj$coefficients["score_scaled", "Pr(>|z|)"]
        
            z_unadj <- s_unadj$coefficients["score_scaled", "z"]
            pvalue_list_unadj_worsesurvival[i]  <- pnorm(z_unadj, lower.tail = FALSE)
            pvalue_list_unadj_bettersurvival[i] <- pnorm(z_unadj, lower.tail = TRUE)
          }
        }
    
        ## ===============================
        ## (B) Adjusted Cox using scaled continuous MI strength
        ##     + age/gender/tumor grade + marker module scores
        ##     HR = per 1 SD increase in MI strength
        ## ===============================
        df_surv2 <- data.frame(
          sample  = common_samples,
          score   = as.numeric(sample_score),
          time    = as.numeric(time_use),
          status  = as.numeric(status_use),
          stringsAsFactors = FALSE
        )
    
        df_surv2 <- add_covariate(df_surv2, coldata_common, "age_at_diagnosis", as_factor = FALSE)
        df_surv2 <- add_covariate(df_surv2, coldata_common, "gender", as_factor = TRUE)
        df_surv2 <- add_covariate(df_surv2, coldata_common, "tumor_grade", as_factor = TRUE)

        ## Optionally add tumor purity to BOTH nested Cox regression models.
        df_surv2 <- add_tumor_purity_covariate(
          df = df_surv2,
          coldata_use = coldata_common,
          if_add = If_add_tumor_purity,
          out_col = tumor_purity_covariate_name,
          source_col = tumor_purity_col_project
        )

        ## Add Invasion / Angiogenesis / EMT / Hypoxia module scores
        ## as additional continuous Cox covariates.
        df_surv2 <- add_module_scores_to_df(df_surv2, module_score_df)
    
        df_surv2 <- df_surv2[complete.cases(df_surv2), , drop = FALSE]
    
        if (nrow(df_surv2) < 10 || length(unique(df_surv2$status)) < 2) next
        if (sum(df_surv2$status == 1) < 3) next
    
        ## Scale MI strength after covariate filtering so the HR is per 1 SD
        ## within the samples actually used in the adjusted Cox model.
        df_surv2$score_scaled <- scale_score_for_cox(df_surv2$score)
        if (all(is.na(df_surv2$score_scaled))) next
    
        candidate_covars <- setdiff(colnames(df_surv2), c("sample", "score", "time", "status"))
        candidate_covars <- filter_usable_covars(df_surv2, candidate_covars)

        ## Model AB must include score_scaled.
        if (!("score_scaled" %in% candidate_covars)) next

        ## Nested Cox models:
        ##   Model A  = clinical covariates + optional tumor_purity + marker module scores
        ##   Model AB = Model A + score_scaled
        covars_AB <- candidate_covars
        covars_A <- setdiff(covars_AB, "score_scaled")

        if (length(covars_A) > 0) {
          cox_formula_A <- as.formula(
            paste("Surv(time, status) ~", paste(covars_A, collapse = " + "))
          )
        } else {
          ## Fallback if all adjustment covariates are unavailable/filtered out.
          ## This should be rare; normally covars_A includes clinical covariates
          ## and/or optional tumor_purity / Invasion / Angiogenesis / EMT / Hypoxia module scores.
          cox_formula_A <- as.formula("Surv(time, status) ~ 1")
        }

        cox_formula_AB <- as.formula(
          paste("Surv(time, status) ~", paste(covars_AB, collapse = " + "))
        )
    
        model_audit_list[[paste(project_cur, MI_cur, sep = "::")]] <<- data.frame(
          project = project_cur, MI = MI_cur, n = nrow(df_surv2),
          events = sum(df_surv2$status == 1),
          formula_A = paste(deparse(cox_formula_A), collapse = " "),
          formula_AB = paste(deparse(cox_formula_AB), collapse = " "),
          stringsAsFactors = FALSE
        )
        fit_A <- try(coxph(cox_formula_A, data = df_surv2), silent = TRUE)
        fit_adj <- try(coxph(cox_formula_AB, data = df_surv2), silent = TRUE)
        if (inherits(fit_adj, "try-error")) next

        ## Likelihood-ratio test for whether adding score_scaled improves model fit.
        if (!inherits(fit_A, "try-error")) {
          lrt_tab <- try(anova(fit_A, fit_adj, test = "LRT"), silent = TRUE)
          if (!inherits(lrt_tab, "try-error")) {
            lrt_res <- extract_nested_lrt(lrt_tab)
            nestedLRT_chisq_list[i] <- lrt_res$chisq
            nestedLRT_df_list[i] <- lrt_res$df
            nestedLRT_pvalue_list[i] <- lrt_res$pvalue
          }
        }
    
        s_adj <- summary(fit_adj)
    
        if ("score_scaled" %in% rownames(s_adj$coefficients)) {
          z_adj <- s_adj$coefficients["score_scaled", "z"]
          p_one_sided_worsesurvival  <- pnorm(z_adj, lower.tail = FALSE)
          p_one_sided_bettersurvival <- pnorm(z_adj, lower.tail = TRUE)
      
          HR_list[i] <- s_adj$coefficients["score_scaled", "exp(coef)"]
          pvalue_list[i] <- s_adj$coefficients["score_scaled", "Pr(>|z|)"]
          pvalue_list_bettersurvival[i] <- p_one_sided_bettersurvival
          pvalue_list_worsesurvival[i] <- p_one_sided_worsesurvival
        }
      }
      HR_mat[, project_cur] <<- HR_list
      pvalue_mat[, project_cur] <<- pvalue_list
      pvalue_mat_bettersurvival[, project_cur] <<- pvalue_list_bettersurvival
      pvalue_mat_worsesurvival[, project_cur] <<- pvalue_list_worsesurvival

      nestedLRT_chisq_mat[, project_cur] <<- nestedLRT_chisq_list
      nestedLRT_df_mat[, project_cur] <<- nestedLRT_df_list
      nestedLRT_pvalue_mat[, project_cur] <<- nestedLRT_pvalue_list
  
      HR_mat_unadj[, project_cur] <<- HR_list_unadj
      pvalue_mat_unadj[, project_cur] <<- pvalue_list_unadj
      pvalue_mat_unadj_bettersurvival[, project_cur] <<- pvalue_list_unadj_bettersurvival
      pvalue_mat_unadj_worsesurvival[, project_cur]  <<- pvalue_list_unadj_worsesurvival
  }

  finish <- function() {
    save(module_score_list, file = paste0(file_path_main, "TCGA_marker_module_score_list_", MI_type_addmodules, ".Rdata"))
    tumor_purity_source_df <- do.call(rbind, tumor_purity_source_list)
    write.csv(
      tumor_purity_source_df,
      file = paste0(file_path_main, "TCGA_tumor_purity_source_record_", MI_type_addmodules, ".csv"),
      row.names = FALSE
    )
    write.csv(HR_mat, file = paste0(file_path_main, "TCGA_MIs_HR_matrix_", MI_type_addmodules, ".csv"))
    write.csv(pvalue_mat, file = paste0(file_path_main, "TCGA_MIs_pvalue_matrix_", MI_type_addmodules, ".csv"))
    write.csv(pvalue_mat_bettersurvival, file = paste0(file_path_main, "TCGA_MIs_pvalue_bettersurvival_matrix_", MI_type_addmodules, ".csv"))
    write.csv(pvalue_mat_worsesurvival, file = paste0(file_path_main, "TCGA_MIs_pvalue_worsesurvival_matrix_", MI_type_addmodules, ".csv"))

    ## Nested Cox likelihood-ratio test outputs.
    ## P-value tests whether Model AB (= Model A + score_scaled) improves fit
    ## over Model A (= clinical covariates + marker module scores + optional tumor_purity).
    write.csv(nestedLRT_chisq_mat, file = paste0(file_path_main, "TCGA_MIs_nestedLRT_chisq_add_score_matrix_", MI_type_addmodules, ".csv"))
    write.csv(nestedLRT_df_mat, file = paste0(file_path_main, "TCGA_MIs_nestedLRT_df_add_score_matrix_", MI_type_addmodules, ".csv"))
    write.csv(nestedLRT_pvalue_mat, file = paste0(file_path_main, "TCGA_MIs_nestedLRT_pvalue_add_score_matrix_", MI_type_addmodules, ".csv"))

    write.csv(HR_mat_unadj, file = paste0(file_path_main, "TCGA_MIs_HR_matrix_unadjusted_", MI_type_addmodules, ".csv"))
    write.csv(pvalue_mat_unadj, file = paste0(file_path_main, "TCGA_MIs_pvalue_matrix_unadjusted_", MI_type_addmodules, ".csv"))
    write.csv(pvalue_mat_unadj_bettersurvival, file = paste0(file_path_main, "TCGA_MIs_pvalue_bettersurvival_matrix_unadjusted_", MI_type_addmodules, ".csv"))
    write.csv(pvalue_mat_unadj_worsesurvival, file = paste0(file_path_main, "TCGA_MIs_pvalue_worsesurvival_matrix_unadjusted_", MI_type_addmodules, ".csv"))
    if (length(model_audit_list) > 0) {
      write.csv(do.call(rbind, model_audit_list),
                file.path(file_path_main, "S27b_model_formulas_and_counts.csv"), row.names = FALSE)
    }
    write.csv(data.frame(setting = c("MI", "module_scores", "clinical_covariates", "include_tumor_purity", "HR_source"),
                         value = c("MI4", paste(names(marker_list), collapse = ";"),
                                   "age_at_diagnosis;gender;tumor_grade", as.character(If_add_tumor_purity), km_hr_path)),
              file.path(file_path_main, "S27b_settings.csv"), row.names = FALSE)
    scatter_result <- plot_nested_lrt(
      km_hr_path,
      paste0(file_path_main, "TCGA_MIs_nestedLRT_pvalue_add_score_matrix_", MI_type_addmodules, ".csv"),
      file_path_main
    )
    df_scatter <- scatter_result$scatter
    nestedLRT_pvalue_mat <- scatter_result$LRT_pvalue
    invisible(list(HR = HR_mat, LRT_pvalue = nestedLRT_pvalue_mat,
                   scatter = df_scatter, output_dir = file_path_main))
  }
  list(add_cohort = add_cohort, finish = finish, output_dir = file_path_main)
}

s27b_analysis <- if (isTRUE(run_s27b_nested_lrt)) {
  create_s27b_analysis(file_path_main, s27b_cancersea_dir, MI_unique,
                      TCGA_project_list, MI_source_type, MI_type,
                      include_tumor_purity = s27b_include_tumor_purity)
} else NULL

## =========================================================
## Main loop
## =========================================================
for (project_cur in TCGA_project_list) {

  message("====================================================")
  message("Analyzing project: ", project_cur)

  ## ===============================
  ## Download & prepare data
  ## ===============================
  query_exp <- GDCquery(
    project = project_cur,
    data.category = "Transcriptome Profiling",
    data.type = "Gene Expression Quantification",
    workflow.type = "STAR - Counts"
  )
  GDCdownload(query_exp)
  expdat <- GDCprepare(query_exp)

  expr <- assay(expdat)
  gene_annot <- rowData(expdat)
  coldata <- as.data.frame(colData(expdat))

  if (!("sample_type" %in% colnames(coldata))) {
    stop("coldata$sample_type is missing for ", project_cur,
         ". Cannot define tumor_keep from sample_type.")
  }

  # Align sample annotations with expression columns before applying the tumor filter.
  if (!identical(colnames(expr), rownames(coldata))) {
    if (all(colnames(expr) %in% rownames(coldata))) {
      coldata <- coldata[colnames(expr), , drop = FALSE]
    } else {
      stop("Expression column names do not match coldata rownames for ", project_cur,
           ". Cannot safely apply tumor_keep.")
    }
  }


  sample_type_chr <- as.character(coldata$sample_type)
  tumor_keep <- sample_type_chr %in% tumor_sample_types
  nontumor_keep <- sample_type_chr %in% nontumor_sample_types

  sample_filter_df <- data.frame(
    sample = colnames(expr),
    project = project_cur,
    sample_type = sample_type_chr,
    tumor_keep = tumor_keep,
    nontumor_keep = nontumor_keep,
    stringsAsFactors = FALSE,
    check.names = FALSE
  )
  tumor_filter_record_list[[project_cur]] <- sample_filter_df

  message("Sample types in ", project_cur, ":")
  print(table(sample_type_chr, useNA = "ifany"))
  message("Tumor-only survival filter for ", project_cur, ": keeping ",
          sum(tumor_keep), " / ", length(tumor_keep), " samples.")

  if (sum(tumor_keep) == 0) {
    stop(
      "No tumor samples were identified for ", project_cur,
      " using coldata$sample_type. Observed sample_type values: ",
      paste(sort(unique(sample_type_chr)), collapse = "; "),
      ". Expected tumor sample types: ",
      paste(tumor_sample_types, collapse = "; ")
    )
  }

  # Restrict expression and clinical annotations before deriving scores and endpoints.
  expr <- expr[, tumor_keep, drop = FALSE]
  coldata <- coldata[tumor_keep, , drop = FALSE]

  clinical_data_list[[project_cur]] <- coldata

  ## ===============================
  ## Construct Overall Survival time/status
  ## ===============================
  vital <- as.character(coldata$vital_status)
  status_all <- ifelse(tolower(vital) == "dead", 1, 0)

  days_to_death <- suppressWarnings(as.numeric(coldata$days_to_death))

  dtlfu <- NULL
  if ("days_to_last_follow_up" %in% colnames(coldata)) {
    dtlfu <- suppressWarnings(as.numeric(coldata$days_to_last_follow_up))
  } else if ("days_to_last_followup" %in% colnames(coldata)) {
    dtlfu <- suppressWarnings(as.numeric(coldata$days_to_last_followup))
  } else if ("paper_Days.to.Last.Follow.Up" %in% colnames(coldata)) {
    dtlfu <- suppressWarnings(as.numeric(coldata$paper_Days.to.Last.Follow.Up))
  } else {
    dtlfu <- rep(NA_real_, nrow(coldata))
  }

  time_all <- ifelse(status_all == 1, days_to_death, dtlfu)
  time_all[time_all == 0] <- NA

  ## ===============================
  ## Valid samples / events checks
  ## ===============================
  valid_idx <- which(is.finite(time_all) & !is.na(status_all))
  if (length(valid_idx) < 10) {
    message("  -> too few valid samples. Skip project.")
    next
  }
  if (sum(status_all[valid_idx] == 1) < 3) {
    message("  -> too few events. Skip project.")
    next
  }

  ## ===============================
  ## Log2 CPM for sample alignment and optional marker-gene scores
  ## ===============================
  expr_cpm <- cpm(expr, log = TRUE, prior.count = 1)
  rownames(expr_cpm) <- gene_annot$gene_name
  expr_cpm <- expr_cpm[!is.na(rownames(expr_cpm)), , drop = FALSE]

  ## ===============================
  ## Read MI decomposition once per project
  ## ===============================
  mi_decomposition_path <- file.path(
    mi_decomposition_dir,
    paste0("MI_decomposition_", project_cur, ".csv")
  )
  if (!file.exists(mi_decomposition_path)) {
    stop("Tumor-only MI decomposition file not found for ", project_cur, ": ",
         mi_decomposition_path,
         "\nRun TCGA_MI_decomposition_V2_updated_tumor_only.R first.")
  }
  MI_decomposition <- read.csv(
    mi_decomposition_path,
    row.names = 1
  )
  rownames(MI_decomposition) <- gsub("\\.", "-", rownames(MI_decomposition))

  common_samples <- intersect(colnames(expr_cpm), rownames(MI_decomposition))
  if (length(common_samples) < 10) {
    message("  -> too few overlapping samples between expr and MI_decomposition. Skip project.")
    next
  }

  expr_cpm <- expr_cpm[, common_samples, drop = FALSE]
  MI_decomposition <- MI_decomposition[common_samples, , drop = FALSE]

  MI_decomposition_list[[project_cur]] <- MI_decomposition

  idx_in_expr <- match(common_samples, colnames(expr))
  time_use <- time_all[idx_in_expr]
  status_use <- status_all[idx_in_expr]

  # Compute the separate nested Cox analysis on these same aligned inputs.
  if (!is.null(s27b_analysis)) {
    s27b_analysis$add_cohort(project_cur, expr_cpm, MI_decomposition, common_samples,
                            coldata, idx_in_expr, expr, time_use, status_use)
  }

  ## ===============================
  ## per-project result vectors

  ## ===============================
  HR_list <- rep(NA, length(MI_unique))
  pvalue_list <- rep(NA, length(MI_unique))
  pvalue_list_bettersurvival <- rep(NA, length(MI_unique))
  pvalue_list_worsesurvival <- rep(NA, length(MI_unique))

  HR_list_unadj <- rep(NA, length(MI_unique))
  pvalue_list_unadj <- rep(NA, length(MI_unique))
  pvalue_list_unadj_bettersurvival <- rep(NA, length(MI_unique))
  pvalue_list_unadj_worsesurvival <- rep(NA, length(MI_unique))

  km_outdir <- paste0(file_path_main, "/KM_plots_tumor_only")
  message("  -> KM plots will be exported for: ", paste(km_mi_to_plot, collapse = ", "))

  ## ===============================
  ## MI loop
  ## ===============================
  for (i in seq_along(MI_unique)) {

    MI_cur <- MI_unique[i]

    ## -------------------------------
    ## score per sample
    ## -------------------------------
    if (MI_source_type == "Markergene") {
      Markergene_list <- unique(
        Phenotype_topgenes_summary$Genes[
          Phenotype_topgenes_summary$MI == MI_cur
        ]
      )

      expr_cpm_marker <- expr_cpm[rownames(expr_cpm) %in% Markergene_list, , drop = FALSE]
      if (nrow(expr_cpm_marker) == 0) next

      sample_score <- colMeans(expr_cpm_marker, na.rm = TRUE)
    } else {
      if (!(MI_cur %in% colnames(MI_decomposition))) next
      sample_score <- MI_decomposition[, MI_cur]
    }

    ## -------------------------------
    ## survival df (base)
    ## -------------------------------
    df_surv <- data.frame(
      sample  = common_samples,
      score   = as.numeric(sample_score),
      time    = as.numeric(time_use),
      status  = as.numeric(status_use),
      stringsAsFactors = FALSE
    )

    df_surv <- df_surv[complete.cases(df_surv[, c("score", "time", "status")]), , drop = FALSE]
    if (nrow(df_surv) < 10 || length(unique(df_surv$status)) < 2) next
    if (sum(df_surv$status == 1) < 3) next

    ## Standardize MI abundance for Cox regression.
    ## Low/Mid/High groups define KM curves and the log-rank comparison.
    df_surv$score_scaled <- scale_score_for_cox(df_surv$score)
    if (all(is.na(df_surv$score_scaled))) next

    tertile_cutoffs <- stats::quantile(
      df_surv$score,
      probs = c(1/3, 2/3),
      na.rm = TRUE,
      names = FALSE,
      type = 7
    )

    if (MI_cur %in% km_mi_to_plot) {
      print(paste(
        "Project:", project_cur,
        "MI:", MI_cur,
        "Tertile cutoffs:",
        paste(signif(tertile_cutoffs, 4), collapse = ", ")
      ))
      print(summary(df_surv$score))
    }

    df_surv$group <- assign_score_tertile_group(df_surv$score)

    if (length(unique(df_surv$group[!is.na(df_surv$group)])) < 2) next

    ## ===============================
    ## (A) Unadjusted Cox: scaled continuous MI strength only
    ##     HR = per 1 SD increase in MI strength
    ## ===============================
    fit_unadj <- try(coxph(Surv(time, status) ~ score_scaled, data = df_surv), silent = TRUE)
    if (!inherits(fit_unadj, "try-error")) {
      s_unadj <- summary(fit_unadj)
      if ("score_scaled" %in% rownames(s_unadj$coefficients)) {
        HR_list_unadj[i] <- s_unadj$coefficients["score_scaled", "exp(coef)"]
        pvalue_list_unadj[i] <- s_unadj$coefficients["score_scaled", "Pr(>|z|)"]

        z_unadj <- s_unadj$coefficients["score_scaled", "z"]
        pvalue_list_unadj_worsesurvival[i]  <- pnorm(z_unadj, lower.tail = FALSE)
        pvalue_list_unadj_bettersurvival[i] <- pnorm(z_unadj, lower.tail = TRUE)
      }
    }

    ## ===============================
    ## (B) Adjusted Cox using scaled continuous MI strength
    ##     HR = per 1 SD increase in MI strength
    ## ===============================
    df_surv2 <- data.frame(
      sample  = common_samples,
      score   = as.numeric(sample_score),
      time    = as.numeric(time_use),
      status  = as.numeric(status_use),
      stringsAsFactors = FALSE
    )

    coldata_use <- coldata[idx_in_expr, , drop = FALSE]
    rownames(coldata_use) <- colnames(expr)[idx_in_expr]
    coldata_use <- coldata_use[common_samples, , drop = FALSE]

    df_surv2 <- add_covariate(df_surv2, coldata_use, "age_at_diagnosis", as_factor = FALSE)
    df_surv2 <- add_covariate(df_surv2, coldata_use, "gender", as_factor = TRUE)
    df_surv2 <- add_covariate(df_surv2, coldata_use, "tumor_grade", as_factor = TRUE)

    df_surv2 <- df_surv2[complete.cases(df_surv2), , drop = FALSE]

    if (nrow(df_surv2) < 10 || length(unique(df_surv2$status)) < 2) next
    if (sum(df_surv2$status == 1) < 3) next

    ## Scale MI strength after covariate filtering so the HR is per 1 SD
    ## within the samples actually used in the adjusted Cox model.
    df_surv2$score_scaled <- scale_score_for_cox(df_surv2$score)
    if (all(is.na(df_surv2$score_scaled))) next

    # score_scaled remains in the formula alongside the available clinical covariates.
    candidate_covars <- setdiff(colnames(df_surv2), c("sample", "score", "time", "status"))

    candidate_covars <- Filter(function(v) {
      x <- df_surv2[[v]]
      if (is.factor(x)) nlevels(x) >= 2 else TRUE
    }, candidate_covars)

    if (length(candidate_covars) == 0) next

    cox_formula <- as.formula(
      paste("Surv(time, status) ~", paste(candidate_covars, collapse = " + "))
    )

    fit_adj <- try(coxph(cox_formula, data = df_surv2), silent = TRUE)
    if (inherits(fit_adj, "try-error")) next

    s_adj <- summary(fit_adj)

    if ("score_scaled" %in% rownames(s_adj$coefficients)) {
      z_adj <- s_adj$coefficients["score_scaled", "z"]
      p_one_sided_worsesurvival  <- pnorm(z_adj, lower.tail = FALSE)
      p_one_sided_bettersurvival <- pnorm(z_adj, lower.tail = TRUE)

      HR_list[i] <- s_adj$coefficients["score_scaled", "exp(coef)"]
      pvalue_list[i] <- s_adj$coefficients["score_scaled", "Pr(>|z|)"]
      pvalue_list_bettersurvival[i] <- p_one_sided_bettersurvival
      pvalue_list_worsesurvival[i] <- p_one_sided_worsesurvival
    }

    ## ===============================
    ## (C) Refit adjusted continuous-score Cox model for plot annotation
    ##     KM curves use Low/Mid/High groups from df_surv.
    ## ===============================
    adj_hr_plot <- NA_real_
    adj_p_plot  <- NA_real_

    if (MI_cur %in% km_mi_to_plot) {

      df_plot_adj <- data.frame(
        sample  = common_samples,
        score   = as.numeric(sample_score),
        time    = as.numeric(time_use),
        status  = as.numeric(status_use),
        stringsAsFactors = FALSE
      )

      tertile_cutoffs_plot <- stats::quantile(
        df_plot_adj$score,
        probs = c(1/3, 2/3),
        na.rm = TRUE,
        names = FALSE,
        type = 7
      )

      print(paste(
        "Project:", project_cur,
        "MI:", MI_cur,
        "Plot tertile cutoffs:",
        paste(signif(tertile_cutoffs_plot, 4), collapse = ", ")
      ))
      print(summary(df_plot_adj$score))

      df_plot_adj$group <- assign_score_tertile_group(df_plot_adj$score)

      if (length(unique(df_plot_adj$group[!is.na(df_plot_adj$group)])) >= 2) {

        df_plot_adj <- add_covariate(df_plot_adj, coldata_use, "age_at_diagnosis", as_factor = FALSE)
        df_plot_adj <- add_covariate(df_plot_adj, coldata_use, "gender", as_factor = TRUE)
        df_plot_adj <- add_covariate(df_plot_adj, coldata_use, "tumor_grade", as_factor = TRUE)

        df_plot_adj <- df_plot_adj[complete.cases(df_plot_adj), , drop = FALSE]

        if (nrow(df_plot_adj) >= 10 &&
            length(unique(df_plot_adj$status)) >= 2 &&
            sum(df_plot_adj$status == 1) >= 3) {

          ## For the HR/P-value shown on the KM plot, use the same
          ## scaled continuous MI strength as the main Cox scan.
          df_plot_adj$score_scaled <- scale_score_for_cox(df_plot_adj$score)

          covars_plot <- setdiff(colnames(df_plot_adj), c("sample", "score", "group", "time", "status"))
          covars_plot <- Filter(function(v) {
            x <- df_plot_adj[[v]]
            if (is.factor(x)) nlevels(x) >= 2 else TRUE
          }, covars_plot)

          if ("score_scaled" %in% covars_plot && !all(is.na(df_plot_adj$score_scaled))) {
            cox_formula_plot <- as.formula(
              paste("Surv(time, status) ~", paste(covars_plot, collapse = " + "))
            )

            fit_adj_plot <- try(coxph(cox_formula_plot, data = df_plot_adj), silent = TRUE)

            if (!inherits(fit_adj_plot, "try-error")) {
              s_adj_plot <- summary(fit_adj_plot)

              if ("score_scaled" %in% rownames(s_adj_plot$coefficients)) {
                adj_hr_plot <- s_adj_plot$coefficients["score_scaled", "exp(coef)"]
                adj_p_plot  <- s_adj_plot$coefficients["score_scaled", "Pr(>|z|)"]
              }
            }
          }
        }
      }

      dir.create(file.path(file_path_main, "KM_plot_inputs"), recursive = TRUE, showWarnings = FALSE)
      saveRDS(list(df_surv = df_surv, project_cur = project_cur, MI_cur = MI_cur,
                   adj_hr = adj_hr_plot, adj_p = adj_p_plot),
              file.path(file_path_main, "KM_plot_inputs", paste0(project_cur, "_", MI_cur, ".rds")))
      try(
        plot_km_nature(
          df_surv = df_surv,
          project_cur = project_cur,
          MI_cur = MI_cur,
          outdir = km_outdir,
          adj_hr = adj_hr_plot,
          adj_p = adj_p_plot
        ),
        silent = TRUE
      )
    }
  }

  ## ===============================
  ## Store cohort-specific Cox results
  ## ===============================
  HR_mat[, project_cur] <- HR_list
  pvalue_mat[, project_cur] <- pvalue_list
  pvalue_mat_bettersurvival[, project_cur] <- pvalue_list_bettersurvival
  pvalue_mat_worsesurvival[, project_cur] <- pvalue_list_worsesurvival

  HR_mat_unadj[, project_cur] <- HR_list_unadj
  pvalue_mat_unadj[, project_cur] <- pvalue_list_unadj
  pvalue_mat_unadj_bettersurvival[, project_cur] <- pvalue_list_unadj_bettersurvival
  pvalue_mat_unadj_worsesurvival[, project_cur]  <- pvalue_list_unadj_worsesurvival
}

## ===============================
## Save tumor-filter records, matched data, and uncorrected Wald P-value matrices
## ===============================
tumor_filter_record_all <- do.call(rbind, tumor_filter_record_list)
write.csv(
  tumor_filter_record_all,
  file = paste0(file_path_main, "TCGA_survival_sample_type_tumor_filter_", MI_type, ".csv"),
  row.names = FALSE
)

tumor_filter_count_df <- do.call(
  rbind,
  lapply(names(tumor_filter_record_list), function(project_name) {
    df <- tumor_filter_record_list[[project_name]]
    data.frame(
      project = project_name,
      n_total = nrow(df),
      n_tumor_keep = sum(df$tumor_keep),
      n_nontumor = sum(df$nontumor_keep),
      n_other_or_unknown = sum(!df$tumor_keep & !df$nontumor_keep),
      stringsAsFactors = FALSE,
      check.names = FALSE
    )
  })
)
write.csv(
  tumor_filter_count_df,
  file = paste0(file_path_main, "TCGA_survival_sample_type_tumor_filter_counts_", MI_type, ".csv"),
  row.names = FALSE
)

save(MI_decomposition_list, file = paste0(file_path_main, "MI_decomposition_list_", MI_type, ".Rdata"))
save(clinical_data_list, file = paste0(file_path_main, "clinical_data_list_", MI_type, ".Rdata"))

write.csv(HR_mat, file = paste0(file_path_main, "TCGA_MIs_HR_matrix_", MI_type, ".csv"))
write.csv(pvalue_mat, file = paste0(file_path_main, "TCGA_MIs_pvalue_matrix_", MI_type, ".csv"))
write.csv(pvalue_mat_bettersurvival, file = paste0(file_path_main, "TCGA_MIs_pvalue_bettersurvival_matrix_", MI_type, ".csv"))
write.csv(pvalue_mat_worsesurvival, file = paste0(file_path_main, "TCGA_MIs_pvalue_worsesurvival_matrix_", MI_type, ".csv"))
write.csv(HR_mat_unadj, file = paste0(file_path_main, "TCGA_MIs_HR_matrix_unadjusted_", MI_type, ".csv"))
write.csv(pvalue_mat_unadj, file = paste0(file_path_main, "TCGA_MIs_pvalue_matrix_unadjusted_", MI_type, ".csv"))
write.csv(pvalue_mat_unadj_bettersurvival, file = paste0(file_path_main, "TCGA_MIs_pvalue_bettersurvival_matrix_unadjusted_", MI_type, ".csv"))
write.csv(pvalue_mat_unadj_worsesurvival, file = paste0(file_path_main, "TCGA_MIs_pvalue_worsesurvival_matrix_unadjusted_", MI_type, ".csv"))

cat("✅ Tumor-only KM tertile survival analysis finished.
")

# The clinical-only HR matrix is now available for the the manuscript x-axis.
if (!is.null(s27b_analysis)) {
  s27b_results <- s27b_analysis$finish()
  message("the manuscript nested-LRT outputs: ", s27b_results$output_dir)
}
